// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: pilab/pivirtd/v1/resource_service.proto

package pivirtdv1

import (
	v1 "go.pilab.hu/cloud/virtpb/v3/pilab/resource/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApplyResourceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resource is the resource to apply. The kind field determines which
	// admission hooks are invoked.
	Resource *v1.Resource `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	// Options controls dry_run, if_match_generation, and client_token.
	Options       *v1.ApplyOptions `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyResourceRequest) Reset() {
	*x = ApplyResourceRequest{}
	mi := &file_pilab_pivirtd_v1_resource_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyResourceRequest) ProtoMessage() {}

func (x *ApplyResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pilab_pivirtd_v1_resource_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyResourceRequest.ProtoReflect.Descriptor instead.
func (*ApplyResourceRequest) Descriptor() ([]byte, []int) {
	return file_pilab_pivirtd_v1_resource_service_proto_rawDescGZIP(), []int{0}
}

func (x *ApplyResourceRequest) GetResource() *v1.Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *ApplyResourceRequest) GetOptions() *v1.ApplyOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type ApplyResourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *v1.ApplyResult        `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyResourceResponse) Reset() {
	*x = ApplyResourceResponse{}
	mi := &file_pilab_pivirtd_v1_resource_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyResourceResponse) ProtoMessage() {}

func (x *ApplyResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pilab_pivirtd_v1_resource_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyResourceResponse.ProtoReflect.Descriptor instead.
func (*ApplyResourceResponse) Descriptor() ([]byte, []int) {
	return file_pilab_pivirtd_v1_resource_service_proto_rawDescGZIP(), []int{1}
}

func (x *ApplyResourceResponse) GetResult() *v1.ApplyResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type ApplyResourcesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resources are the resources to apply. They are sorted into
	// kind-dependency order before admission.
	Resources []*v1.Resource `protobuf:"bytes,1,rep,name=resources,proto3" json:"resources,omitempty"`
	// Options controls dry_run, if_match_generation, and client_token
	// for every resource in the batch.
	Options       *v1.ApplyOptions `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyResourcesRequest) Reset() {
	*x = ApplyResourcesRequest{}
	mi := &file_pilab_pivirtd_v1_resource_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyResourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyResourcesRequest) ProtoMessage() {}

func (x *ApplyResourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pilab_pivirtd_v1_resource_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyResourcesRequest.ProtoReflect.Descriptor instead.
func (*ApplyResourcesRequest) Descriptor() ([]byte, []int) {
	return file_pilab_pivirtd_v1_resource_service_proto_rawDescGZIP(), []int{2}
}

func (x *ApplyResourcesRequest) GetResources() []*v1.Resource {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *ApplyResourcesRequest) GetOptions() *v1.ApplyOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type ApplyResourcesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Results is one entry per input resource, in the same order as
	// the input after sorting. Each entry carries the per-object outcome.
	Results []*v1.ApplyResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	// Pruned lists the objects prune removed, or would remove under dry_run.
	// Empty unless ApplyOptions.prune was set.
	Pruned        []*v1.PruneResult `protobuf:"bytes,2,rep,name=pruned,proto3" json:"pruned,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyResourcesResponse) Reset() {
	*x = ApplyResourcesResponse{}
	mi := &file_pilab_pivirtd_v1_resource_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyResourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyResourcesResponse) ProtoMessage() {}

func (x *ApplyResourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pilab_pivirtd_v1_resource_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyResourcesResponse.ProtoReflect.Descriptor instead.
func (*ApplyResourcesResponse) Descriptor() ([]byte, []int) {
	return file_pilab_pivirtd_v1_resource_service_proto_rawDescGZIP(), []int{3}
}

func (x *ApplyResourcesResponse) GetResults() []*v1.ApplyResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ApplyResourcesResponse) GetPruned() []*v1.PruneResult {
	if x != nil {
		return x.Pruned
	}
	return nil
}

type GetResourceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Kind is the resource kind, e.g. "VirtualMachine".
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// Name is the resource name, unique within the kind.
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResourceRequest) Reset() {
	*x = GetResourceRequest{}
	mi := &file_pilab_pivirtd_v1_resource_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResourceRequest) ProtoMessage() {}

func (x *GetResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pilab_pivirtd_v1_resource_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResourceRequest.ProtoReflect.Descriptor instead.
func (*GetResourceRequest) Descriptor() ([]byte, []int) {
	return file_pilab_pivirtd_v1_resource_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetResourceRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *GetResourceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetResourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      *v1.Resource           `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResourceResponse) Reset() {
	*x = GetResourceResponse{}
	mi := &file_pilab_pivirtd_v1_resource_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResourceResponse) ProtoMessage() {}

func (x *GetResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pilab_pivirtd_v1_resource_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResourceResponse.ProtoReflect.Descriptor instead.
func (*GetResourceResponse) Descriptor() ([]byte, []int) {
	return file_pilab_pivirtd_v1_resource_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetResourceResponse) GetResource() *v1.Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

type ListResourcesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Kind is the resource kind to list.
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// Selector is an optional label selector. An empty or absent selector
	// matches everything. Uses pkg/resource.Selector semantics: equality,
	// set membership (in, notin), and existence (!exists).
	Selector      string `protobuf:"bytes,2,opt,name=selector,proto3" json:"selector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResourcesRequest) Reset() {
	*x = ListResourcesRequest{}
	mi := &file_pilab_pivirtd_v1_resource_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResourcesRequest) ProtoMessage() {}

func (x *ListResourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pilab_pivirtd_v1_resource_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResourcesRequest.ProtoReflect.Descriptor instead.
func (*ListResourcesRequest) Descriptor() ([]byte, []int) {
	return file_pilab_pivirtd_v1_resource_service_proto_rawDescGZIP(), []int{6}
}

func (x *ListResourcesRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ListResourcesRequest) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

type ListResourcesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resources     []*v1.Resource         `protobuf:"bytes,1,rep,name=resources,proto3" json:"resources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResourcesResponse) Reset() {
	*x = ListResourcesResponse{}
	mi := &file_pilab_pivirtd_v1_resource_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResourcesResponse) ProtoMessage() {}

func (x *ListResourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pilab_pivirtd_v1_resource_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResourcesResponse.ProtoReflect.Descriptor instead.
func (*ListResourcesResponse) Descriptor() ([]byte, []int) {
	return file_pilab_pivirtd_v1_resource_service_proto_rawDescGZIP(), []int{7}
}

func (x *ListResourcesResponse) GetResources() []*v1.Resource {
	if x != nil {
		return x.Resources
	}
	return nil
}

type DeleteResourceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Kind is the resource kind to delete.
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// Name is the resource name to delete.
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResourceRequest) Reset() {
	*x = DeleteResourceRequest{}
	mi := &file_pilab_pivirtd_v1_resource_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResourceRequest) ProtoMessage() {}

func (x *DeleteResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pilab_pivirtd_v1_resource_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResourceRequest.ProtoReflect.Descriptor instead.
func (*DeleteResourceRequest) Descriptor() ([]byte, []int) {
	return file_pilab_pivirtd_v1_resource_service_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteResourceRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *DeleteResourceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteResourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResourceResponse) Reset() {
	*x = DeleteResourceResponse{}
	mi := &file_pilab_pivirtd_v1_resource_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResourceResponse) ProtoMessage() {}

func (x *DeleteResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pilab_pivirtd_v1_resource_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResourceResponse.ProtoReflect.Descriptor instead.
func (*DeleteResourceResponse) Descriptor() ([]byte, []int) {
	return file_pilab_pivirtd_v1_resource_service_proto_rawDescGZIP(), []int{9}
}

type ListKindsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListKindsRequest) Reset() {
	*x = ListKindsRequest{}
	mi := &file_pilab_pivirtd_v1_resource_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListKindsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKindsRequest) ProtoMessage() {}

func (x *ListKindsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pilab_pivirtd_v1_resource_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKindsRequest.ProtoReflect.Descriptor instead.
func (*ListKindsRequest) Descriptor() ([]byte, []int) {
	return file_pilab_pivirtd_v1_resource_service_proto_rawDescGZIP(), []int{10}
}

type ListKindsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Kinds is the set of resource kinds this tier has registered,
	// sorted alphabetically.
	Kinds         []string `protobuf:"bytes,1,rep,name=kinds,proto3" json:"kinds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListKindsResponse) Reset() {
	*x = ListKindsResponse{}
	mi := &file_pilab_pivirtd_v1_resource_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListKindsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKindsResponse) ProtoMessage() {}

func (x *ListKindsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pilab_pivirtd_v1_resource_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKindsResponse.ProtoReflect.Descriptor instead.
func (*ListKindsResponse) Descriptor() ([]byte, []int) {
	return file_pilab_pivirtd_v1_resource_service_proto_rawDescGZIP(), []int{11}
}

func (x *ListKindsResponse) GetKinds() []string {
	if x != nil {
		return x.Kinds
	}
	return nil
}

var File_pilab_pivirtd_v1_resource_service_proto protoreflect.FileDescriptor

const file_pilab_pivirtd_v1_resource_service_proto_rawDesc = "" +
	"\n" +
	"'pilab/pivirtd/v1/resource_service.proto\x12\x10pilab.pivirtd.v1\x1a pilab/resource/v1/resource.proto\"\x8a\x01\n" +
	"\x14ApplyResourceRequest\x127\n" +
	"\bresource\x18\x01 \x01(\v2\x1b.pilab.resource.v1.ResourceR\bresource\x129\n" +
	"\aoptions\x18\x02 \x01(\v2\x1f.pilab.resource.v1.ApplyOptionsR\aoptions\"O\n" +
	"\x15ApplyResourceResponse\x126\n" +
	"\x06result\x18\x01 \x01(\v2\x1e.pilab.resource.v1.ApplyResultR\x06result\"\x8d\x01\n" +
	"\x15ApplyResourcesRequest\x129\n" +
	"\tresources\x18\x01 \x03(\v2\x1b.pilab.resource.v1.ResourceR\tresources\x129\n" +
	"\aoptions\x18\x02 \x01(\v2\x1f.pilab.resource.v1.ApplyOptionsR\aoptions\"\x8a\x01\n" +
	"\x16ApplyResourcesResponse\x128\n" +
	"\aresults\x18\x01 \x03(\v2\x1e.pilab.resource.v1.ApplyResultR\aresults\x126\n" +
	"\x06pruned\x18\x02 \x03(\v2\x1e.pilab.resource.v1.PruneResultR\x06pruned\"<\n" +
	"\x12GetResourceRequest\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"N\n" +
	"\x13GetResourceResponse\x127\n" +
	"\bresource\x18\x01 \x01(\v2\x1b.pilab.resource.v1.ResourceR\bresource\"F\n" +
	"\x14ListResourcesRequest\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x1a\n" +
	"\bselector\x18\x02 \x01(\tR\bselector\"R\n" +
	"\x15ListResourcesResponse\x129\n" +
	"\tresources\x18\x01 \x03(\v2\x1b.pilab.resource.v1.ResourceR\tresources\"?\n" +
	"\x15DeleteResourceRequest\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x18\n" +
	"\x16DeleteResourceResponse\"\x12\n" +
	"\x10ListKindsRequest\")\n" +
	"\x11ListKindsResponse\x12\x14\n" +
	"\x05kinds\x18\x01 \x03(\tR\x05kinds2\xd8\x04\n" +
	"\x16PivirtdResourceService\x12`\n" +
	"\rApplyResource\x12&.pilab.pivirtd.v1.ApplyResourceRequest\x1a'.pilab.pivirtd.v1.ApplyResourceResponse\x12c\n" +
	"\x0eApplyResources\x12'.pilab.pivirtd.v1.ApplyResourcesRequest\x1a(.pilab.pivirtd.v1.ApplyResourcesResponse\x12Z\n" +
	"\vGetResource\x12$.pilab.pivirtd.v1.GetResourceRequest\x1a%.pilab.pivirtd.v1.GetResourceResponse\x12`\n" +
	"\rListResources\x12&.pilab.pivirtd.v1.ListResourcesRequest\x1a'.pilab.pivirtd.v1.ListResourcesResponse\x12c\n" +
	"\x0eDeleteResource\x12'.pilab.pivirtd.v1.DeleteResourceRequest\x1a(.pilab.pivirtd.v1.DeleteResourceResponse\x12T\n" +
	"\tListKinds\x12\".pilab.pivirtd.v1.ListKindsRequest\x1a#.pilab.pivirtd.v1.ListKindsResponseB8Z6go.pilab.hu/cloud/virtpb/v3/pilab/pivirtd/v1;pivirtdv1b\x06proto3"

var (
	file_pilab_pivirtd_v1_resource_service_proto_rawDescOnce sync.Once
	file_pilab_pivirtd_v1_resource_service_proto_rawDescData []byte
)

func file_pilab_pivirtd_v1_resource_service_proto_rawDescGZIP() []byte {
	file_pilab_pivirtd_v1_resource_service_proto_rawDescOnce.Do(func() {
		file_pilab_pivirtd_v1_resource_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pilab_pivirtd_v1_resource_service_proto_rawDesc), len(file_pilab_pivirtd_v1_resource_service_proto_rawDesc)))
	})
	return file_pilab_pivirtd_v1_resource_service_proto_rawDescData
}

var file_pilab_pivirtd_v1_resource_service_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_pilab_pivirtd_v1_resource_service_proto_goTypes = []any{
	(*ApplyResourceRequest)(nil),   // 0: pilab.pivirtd.v1.ApplyResourceRequest
	(*ApplyResourceResponse)(nil),  // 1: pilab.pivirtd.v1.ApplyResourceResponse
	(*ApplyResourcesRequest)(nil),  // 2: pilab.pivirtd.v1.ApplyResourcesRequest
	(*ApplyResourcesResponse)(nil), // 3: pilab.pivirtd.v1.ApplyResourcesResponse
	(*GetResourceRequest)(nil),     // 4: pilab.pivirtd.v1.GetResourceRequest
	(*GetResourceResponse)(nil),    // 5: pilab.pivirtd.v1.GetResourceResponse
	(*ListResourcesRequest)(nil),   // 6: pilab.pivirtd.v1.ListResourcesRequest
	(*ListResourcesResponse)(nil),  // 7: pilab.pivirtd.v1.ListResourcesResponse
	(*DeleteResourceRequest)(nil),  // 8: pilab.pivirtd.v1.DeleteResourceRequest
	(*DeleteResourceResponse)(nil), // 9: pilab.pivirtd.v1.DeleteResourceResponse
	(*ListKindsRequest)(nil),       // 10: pilab.pivirtd.v1.ListKindsRequest
	(*ListKindsResponse)(nil),      // 11: pilab.pivirtd.v1.ListKindsResponse
	(*v1.Resource)(nil),            // 12: pilab.resource.v1.Resource
	(*v1.ApplyOptions)(nil),        // 13: pilab.resource.v1.ApplyOptions
	(*v1.ApplyResult)(nil),         // 14: pilab.resource.v1.ApplyResult
	(*v1.PruneResult)(nil),         // 15: pilab.resource.v1.PruneResult
}
var file_pilab_pivirtd_v1_resource_service_proto_depIdxs = []int32{
	12, // 0: pilab.pivirtd.v1.ApplyResourceRequest.resource:type_name -> pilab.resource.v1.Resource
	13, // 1: pilab.pivirtd.v1.ApplyResourceRequest.options:type_name -> pilab.resource.v1.ApplyOptions
	14, // 2: pilab.pivirtd.v1.ApplyResourceResponse.result:type_name -> pilab.resource.v1.ApplyResult
	12, // 3: pilab.pivirtd.v1.ApplyResourcesRequest.resources:type_name -> pilab.resource.v1.Resource
	13, // 4: pilab.pivirtd.v1.ApplyResourcesRequest.options:type_name -> pilab.resource.v1.ApplyOptions
	14, // 5: pilab.pivirtd.v1.ApplyResourcesResponse.results:type_name -> pilab.resource.v1.ApplyResult
	15, // 6: pilab.pivirtd.v1.ApplyResourcesResponse.pruned:type_name -> pilab.resource.v1.PruneResult
	12, // 7: pilab.pivirtd.v1.GetResourceResponse.resource:type_name -> pilab.resource.v1.Resource
	12, // 8: pilab.pivirtd.v1.ListResourcesResponse.resources:type_name -> pilab.resource.v1.Resource
	0,  // 9: pilab.pivirtd.v1.PivirtdResourceService.ApplyResource:input_type -> pilab.pivirtd.v1.ApplyResourceRequest
	2,  // 10: pilab.pivirtd.v1.PivirtdResourceService.ApplyResources:input_type -> pilab.pivirtd.v1.ApplyResourcesRequest
	4,  // 11: pilab.pivirtd.v1.PivirtdResourceService.GetResource:input_type -> pilab.pivirtd.v1.GetResourceRequest
	6,  // 12: pilab.pivirtd.v1.PivirtdResourceService.ListResources:input_type -> pilab.pivirtd.v1.ListResourcesRequest
	8,  // 13: pilab.pivirtd.v1.PivirtdResourceService.DeleteResource:input_type -> pilab.pivirtd.v1.DeleteResourceRequest
	10, // 14: pilab.pivirtd.v1.PivirtdResourceService.ListKinds:input_type -> pilab.pivirtd.v1.ListKindsRequest
	1,  // 15: pilab.pivirtd.v1.PivirtdResourceService.ApplyResource:output_type -> pilab.pivirtd.v1.ApplyResourceResponse
	3,  // 16: pilab.pivirtd.v1.PivirtdResourceService.ApplyResources:output_type -> pilab.pivirtd.v1.ApplyResourcesResponse
	5,  // 17: pilab.pivirtd.v1.PivirtdResourceService.GetResource:output_type -> pilab.pivirtd.v1.GetResourceResponse
	7,  // 18: pilab.pivirtd.v1.PivirtdResourceService.ListResources:output_type -> pilab.pivirtd.v1.ListResourcesResponse
	9,  // 19: pilab.pivirtd.v1.PivirtdResourceService.DeleteResource:output_type -> pilab.pivirtd.v1.DeleteResourceResponse
	11, // 20: pilab.pivirtd.v1.PivirtdResourceService.ListKinds:output_type -> pilab.pivirtd.v1.ListKindsResponse
	15, // [15:21] is the sub-list for method output_type
	9,  // [9:15] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_pilab_pivirtd_v1_resource_service_proto_init() }
func file_pilab_pivirtd_v1_resource_service_proto_init() {
	if File_pilab_pivirtd_v1_resource_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pilab_pivirtd_v1_resource_service_proto_rawDesc), len(file_pilab_pivirtd_v1_resource_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pilab_pivirtd_v1_resource_service_proto_goTypes,
		DependencyIndexes: file_pilab_pivirtd_v1_resource_service_proto_depIdxs,
		MessageInfos:      file_pilab_pivirtd_v1_resource_service_proto_msgTypes,
	}.Build()
	File_pilab_pivirtd_v1_resource_service_proto = out.File
	file_pilab_pivirtd_v1_resource_service_proto_goTypes = nil
	file_pilab_pivirtd_v1_resource_service_proto_depIdxs = nil
}
