// =============================================================================
// Error Response - Common Error Structure
// =============================================================================
// Purpose: Standardized error response message used across all agent services.
// Provides consistent error handling with code, message, and optional details.
//
// Usage: Included in response messages as optional ErrorResponse field
// =============================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pilab/agent/v1/error.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Common error response structure
type ErrorResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	ErrorMessage string                 `protobuf:"bytes,1,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// Optionally include an error code
	ErrorCode     string `protobuf:"bytes,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Details       []byte `protobuf:"bytes,3,opt,name=details,proto3,oneof" json:"details,omitempty"` // Additional details about the error
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_pilab_agent_v1_error_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pilab_agent_v1_error_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_pilab_agent_v1_error_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ErrorResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *ErrorResponse) GetDetails() []byte {
	if x != nil {
		return x.Details
	}
	return nil
}

var File_pilab_agent_v1_error_proto protoreflect.FileDescriptor

const file_pilab_agent_v1_error_proto_rawDesc = "" +
	"\n" +
	"\x1apilab/agent/v1/error.proto\x12\x14pilab.cloud.agent.v1\"~\n" +
	"\rErrorResponse\x12#\n" +
	"\rerror_message\x18\x01 \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\n" +
	"error_code\x18\x02 \x01(\tR\terrorCode\x12\x1d\n" +
	"\adetails\x18\x03 \x01(\fH\x00R\adetails\x88\x01\x01B\n" +
	"\n" +
	"\b_detailsB1Z/go.pilab.hu/cloud/virtpb/pilab/agent/v1;agentv1b\x06proto3"

var (
	file_pilab_agent_v1_error_proto_rawDescOnce sync.Once
	file_pilab_agent_v1_error_proto_rawDescData []byte
)

func file_pilab_agent_v1_error_proto_rawDescGZIP() []byte {
	file_pilab_agent_v1_error_proto_rawDescOnce.Do(func() {
		file_pilab_agent_v1_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pilab_agent_v1_error_proto_rawDesc), len(file_pilab_agent_v1_error_proto_rawDesc)))
	})
	return file_pilab_agent_v1_error_proto_rawDescData
}

var file_pilab_agent_v1_error_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pilab_agent_v1_error_proto_goTypes = []any{
	(*ErrorResponse)(nil), // 0: pilab.cloud.agent.v1.ErrorResponse
}
var file_pilab_agent_v1_error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pilab_agent_v1_error_proto_init() }
func file_pilab_agent_v1_error_proto_init() {
	if File_pilab_agent_v1_error_proto != nil {
		return
	}
	file_pilab_agent_v1_error_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pilab_agent_v1_error_proto_rawDesc), len(file_pilab_agent_v1_error_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pilab_agent_v1_error_proto_goTypes,
		DependencyIndexes: file_pilab_agent_v1_error_proto_depIdxs,
		MessageInfos:      file_pilab_agent_v1_error_proto_msgTypes,
	}.Build()
	File_pilab_agent_v1_error_proto = out.File
	file_pilab_agent_v1_error_proto_goTypes = nil
	file_pilab_agent_v1_error_proto_depIdxs = nil
}
