// Package network provides virtual networking services including networks,
// ports, VLAN/VXLAN management, IPAM, QoS, security, DVS, and statistics.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: pilab/network/v2/network_service.proto

package networkv2connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v2 "go.pilab.hu/cloud/virtpb/pilab/network/v2"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// NetworkServiceName is the fully-qualified name of the NetworkService service.
	NetworkServiceName = "pilab.network.v2.NetworkService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// NetworkServiceCreateNetworkProcedure is the fully-qualified name of the NetworkService's
	// CreateNetwork RPC.
	NetworkServiceCreateNetworkProcedure = "/pilab.network.v2.NetworkService/CreateNetwork"
	// NetworkServiceGetNetworkProcedure is the fully-qualified name of the NetworkService's GetNetwork
	// RPC.
	NetworkServiceGetNetworkProcedure = "/pilab.network.v2.NetworkService/GetNetwork"
	// NetworkServiceListNetworksProcedure is the fully-qualified name of the NetworkService's
	// ListNetworks RPC.
	NetworkServiceListNetworksProcedure = "/pilab.network.v2.NetworkService/ListNetworks"
	// NetworkServiceUpdateNetworkProcedure is the fully-qualified name of the NetworkService's
	// UpdateNetwork RPC.
	NetworkServiceUpdateNetworkProcedure = "/pilab.network.v2.NetworkService/UpdateNetwork"
	// NetworkServiceDeleteNetworkProcedure is the fully-qualified name of the NetworkService's
	// DeleteNetwork RPC.
	NetworkServiceDeleteNetworkProcedure = "/pilab.network.v2.NetworkService/DeleteNetwork"
	// NetworkServiceAttachHostsProcedure is the fully-qualified name of the NetworkService's
	// AttachHosts RPC.
	NetworkServiceAttachHostsProcedure = "/pilab.network.v2.NetworkService/AttachHosts"
	// NetworkServiceDetachHostsProcedure is the fully-qualified name of the NetworkService's
	// DetachHosts RPC.
	NetworkServiceDetachHostsProcedure = "/pilab.network.v2.NetworkService/DetachHosts"
	// NetworkServiceCreatePortProcedure is the fully-qualified name of the NetworkService's CreatePort
	// RPC.
	NetworkServiceCreatePortProcedure = "/pilab.network.v2.NetworkService/CreatePort"
	// NetworkServiceGetPortProcedure is the fully-qualified name of the NetworkService's GetPort RPC.
	NetworkServiceGetPortProcedure = "/pilab.network.v2.NetworkService/GetPort"
	// NetworkServiceListPortsProcedure is the fully-qualified name of the NetworkService's ListPorts
	// RPC.
	NetworkServiceListPortsProcedure = "/pilab.network.v2.NetworkService/ListPorts"
	// NetworkServiceUpdatePortProcedure is the fully-qualified name of the NetworkService's UpdatePort
	// RPC.
	NetworkServiceUpdatePortProcedure = "/pilab.network.v2.NetworkService/UpdatePort"
	// NetworkServiceDeletePortProcedure is the fully-qualified name of the NetworkService's DeletePort
	// RPC.
	NetworkServiceDeletePortProcedure = "/pilab.network.v2.NetworkService/DeletePort"
	// NetworkServiceAttachPortProcedure is the fully-qualified name of the NetworkService's AttachPort
	// RPC.
	NetworkServiceAttachPortProcedure = "/pilab.network.v2.NetworkService/AttachPort"
	// NetworkServiceDetachPortProcedure is the fully-qualified name of the NetworkService's DetachPort
	// RPC.
	NetworkServiceDetachPortProcedure = "/pilab.network.v2.NetworkService/DetachPort"
	// NetworkServiceCreateVLANRangeProcedure is the fully-qualified name of the NetworkService's
	// CreateVLANRange RPC.
	NetworkServiceCreateVLANRangeProcedure = "/pilab.network.v2.NetworkService/CreateVLANRange"
	// NetworkServiceListVLANRangesProcedure is the fully-qualified name of the NetworkService's
	// ListVLANRanges RPC.
	NetworkServiceListVLANRangesProcedure = "/pilab.network.v2.NetworkService/ListVLANRanges"
	// NetworkServiceAllocateVLANProcedure is the fully-qualified name of the NetworkService's
	// AllocateVLAN RPC.
	NetworkServiceAllocateVLANProcedure = "/pilab.network.v2.NetworkService/AllocateVLAN"
	// NetworkServiceReleaseVLANProcedure is the fully-qualified name of the NetworkService's
	// ReleaseVLAN RPC.
	NetworkServiceReleaseVLANProcedure = "/pilab.network.v2.NetworkService/ReleaseVLAN"
	// NetworkServiceCreateVirtualCloudProcedure is the fully-qualified name of the NetworkService's
	// CreateVirtualCloud RPC.
	NetworkServiceCreateVirtualCloudProcedure = "/pilab.network.v2.NetworkService/CreateVirtualCloud"
	// NetworkServiceGetVirtualCloudProcedure is the fully-qualified name of the NetworkService's
	// GetVirtualCloud RPC.
	NetworkServiceGetVirtualCloudProcedure = "/pilab.network.v2.NetworkService/GetVirtualCloud"
	// NetworkServiceListVirtualCloudsProcedure is the fully-qualified name of the NetworkService's
	// ListVirtualClouds RPC.
	NetworkServiceListVirtualCloudsProcedure = "/pilab.network.v2.NetworkService/ListVirtualClouds"
	// NetworkServiceUpdateVirtualCloudProcedure is the fully-qualified name of the NetworkService's
	// UpdateVirtualCloud RPC.
	NetworkServiceUpdateVirtualCloudProcedure = "/pilab.network.v2.NetworkService/UpdateVirtualCloud"
	// NetworkServiceDeleteVirtualCloudProcedure is the fully-qualified name of the NetworkService's
	// DeleteVirtualCloud RPC.
	NetworkServiceDeleteVirtualCloudProcedure = "/pilab.network.v2.NetworkService/DeleteVirtualCloud"
	// NetworkServiceAddVNIEndpointProcedure is the fully-qualified name of the NetworkService's
	// AddVNIEndpoint RPC.
	NetworkServiceAddVNIEndpointProcedure = "/pilab.network.v2.NetworkService/AddVNIEndpoint"
	// NetworkServiceRemoveVNIEndpointProcedure is the fully-qualified name of the NetworkService's
	// RemoveVNIEndpoint RPC.
	NetworkServiceRemoveVNIEndpointProcedure = "/pilab.network.v2.NetworkService/RemoveVNIEndpoint"
	// NetworkServiceAllocateVNIProcedure is the fully-qualified name of the NetworkService's
	// AllocateVNI RPC.
	NetworkServiceAllocateVNIProcedure = "/pilab.network.v2.NetworkService/AllocateVNI"
	// NetworkServiceReleaseVNIProcedure is the fully-qualified name of the NetworkService's ReleaseVNI
	// RPC.
	NetworkServiceReleaseVNIProcedure = "/pilab.network.v2.NetworkService/ReleaseVNI"
)

// NetworkServiceClient is a client for the pilab.network.v2.NetworkService service.
type NetworkServiceClient interface {
	// Network operations
	CreateNetwork(context.Context, *connect.Request[v2.CreateNetworkRequest]) (*connect.Response[v2.VirtualNetwork], error)
	GetNetwork(context.Context, *connect.Request[v2.GetNetworkRequest]) (*connect.Response[v2.VirtualNetwork], error)
	ListNetworks(context.Context, *connect.Request[v2.ListNetworksRequest]) (*connect.Response[v2.ListNetworksResponse], error)
	UpdateNetwork(context.Context, *connect.Request[v2.UpdateNetworkRequest]) (*connect.Response[v2.VirtualNetwork], error)
	DeleteNetwork(context.Context, *connect.Request[v2.DeleteNetworkRequest]) (*connect.Response[emptypb.Empty], error)
	AttachHosts(context.Context, *connect.Request[v2.AttachHostsRequest]) (*connect.Response[emptypb.Empty], error)
	DetachHosts(context.Context, *connect.Request[v2.DetachHostsRequest]) (*connect.Response[emptypb.Empty], error)
	// Port operations
	CreatePort(context.Context, *connect.Request[v2.CreatePortRequest]) (*connect.Response[v2.VirtualPort], error)
	GetPort(context.Context, *connect.Request[v2.GetPortRequest]) (*connect.Response[v2.VirtualPort], error)
	ListPorts(context.Context, *connect.Request[v2.ListPortsRequest]) (*connect.Response[v2.ListPortsResponse], error)
	UpdatePort(context.Context, *connect.Request[v2.UpdatePortRequest]) (*connect.Response[v2.VirtualPort], error)
	DeletePort(context.Context, *connect.Request[v2.DeletePortRequest]) (*connect.Response[emptypb.Empty], error)
	AttachPort(context.Context, *connect.Request[v2.AttachPortRequest]) (*connect.Response[emptypb.Empty], error)
	DetachPort(context.Context, *connect.Request[v2.DetachPortRequest]) (*connect.Response[emptypb.Empty], error)
	// VLAN operations
	CreateVLANRange(context.Context, *connect.Request[v2.CreateVLANRangeRequest]) (*connect.Response[v2.VLANRange], error)
	ListVLANRanges(context.Context, *connect.Request[v2.ListVLANRangesRequest]) (*connect.Response[v2.ListVLANRangesResponse], error)
	AllocateVLAN(context.Context, *connect.Request[v2.AllocateVLANRequest]) (*connect.Response[v2.VLANAllocation], error)
	ReleaseVLAN(context.Context, *connect.Request[v2.ReleaseVLANRequest]) (*connect.Response[emptypb.Empty], error)
	// Virtual cloud (VXLAN) operations
	CreateVirtualCloud(context.Context, *connect.Request[v2.CreateVirtualCloudRequest]) (*connect.Response[v2.VirtualCloud], error)
	GetVirtualCloud(context.Context, *connect.Request[v2.GetVirtualCloudRequest]) (*connect.Response[v2.VirtualCloud], error)
	ListVirtualClouds(context.Context, *connect.Request[v2.ListVirtualCloudsRequest]) (*connect.Response[v2.ListVirtualCloudsResponse], error)
	UpdateVirtualCloud(context.Context, *connect.Request[v2.UpdateVirtualCloudRequest]) (*connect.Response[v2.VirtualCloud], error)
	DeleteVirtualCloud(context.Context, *connect.Request[v2.DeleteVirtualCloudRequest]) (*connect.Response[emptypb.Empty], error)
	AddVNIEndpoint(context.Context, *connect.Request[v2.AddVNIEndpointRequest]) (*connect.Response[emptypb.Empty], error)
	RemoveVNIEndpoint(context.Context, *connect.Request[v2.RemoveVNIEndpointRequest]) (*connect.Response[emptypb.Empty], error)
	AllocateVNI(context.Context, *connect.Request[v2.AllocateVNIRequest]) (*connect.Response[v2.VNIAllocation], error)
	ReleaseVNI(context.Context, *connect.Request[v2.ReleaseVNIRequest]) (*connect.Response[emptypb.Empty], error)
}

// NewNetworkServiceClient constructs a client for the pilab.network.v2.NetworkService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewNetworkServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) NetworkServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	networkServiceMethods := v2.File_pilab_network_v2_network_service_proto.Services().ByName("NetworkService").Methods()
	return &networkServiceClient{
		createNetwork: connect.NewClient[v2.CreateNetworkRequest, v2.VirtualNetwork](
			httpClient,
			baseURL+NetworkServiceCreateNetworkProcedure,
			connect.WithSchema(networkServiceMethods.ByName("CreateNetwork")),
			connect.WithClientOptions(opts...),
		),
		getNetwork: connect.NewClient[v2.GetNetworkRequest, v2.VirtualNetwork](
			httpClient,
			baseURL+NetworkServiceGetNetworkProcedure,
			connect.WithSchema(networkServiceMethods.ByName("GetNetwork")),
			connect.WithClientOptions(opts...),
		),
		listNetworks: connect.NewClient[v2.ListNetworksRequest, v2.ListNetworksResponse](
			httpClient,
			baseURL+NetworkServiceListNetworksProcedure,
			connect.WithSchema(networkServiceMethods.ByName("ListNetworks")),
			connect.WithClientOptions(opts...),
		),
		updateNetwork: connect.NewClient[v2.UpdateNetworkRequest, v2.VirtualNetwork](
			httpClient,
			baseURL+NetworkServiceUpdateNetworkProcedure,
			connect.WithSchema(networkServiceMethods.ByName("UpdateNetwork")),
			connect.WithClientOptions(opts...),
		),
		deleteNetwork: connect.NewClient[v2.DeleteNetworkRequest, emptypb.Empty](
			httpClient,
			baseURL+NetworkServiceDeleteNetworkProcedure,
			connect.WithSchema(networkServiceMethods.ByName("DeleteNetwork")),
			connect.WithClientOptions(opts...),
		),
		attachHosts: connect.NewClient[v2.AttachHostsRequest, emptypb.Empty](
			httpClient,
			baseURL+NetworkServiceAttachHostsProcedure,
			connect.WithSchema(networkServiceMethods.ByName("AttachHosts")),
			connect.WithClientOptions(opts...),
		),
		detachHosts: connect.NewClient[v2.DetachHostsRequest, emptypb.Empty](
			httpClient,
			baseURL+NetworkServiceDetachHostsProcedure,
			connect.WithSchema(networkServiceMethods.ByName("DetachHosts")),
			connect.WithClientOptions(opts...),
		),
		createPort: connect.NewClient[v2.CreatePortRequest, v2.VirtualPort](
			httpClient,
			baseURL+NetworkServiceCreatePortProcedure,
			connect.WithSchema(networkServiceMethods.ByName("CreatePort")),
			connect.WithClientOptions(opts...),
		),
		getPort: connect.NewClient[v2.GetPortRequest, v2.VirtualPort](
			httpClient,
			baseURL+NetworkServiceGetPortProcedure,
			connect.WithSchema(networkServiceMethods.ByName("GetPort")),
			connect.WithClientOptions(opts...),
		),
		listPorts: connect.NewClient[v2.ListPortsRequest, v2.ListPortsResponse](
			httpClient,
			baseURL+NetworkServiceListPortsProcedure,
			connect.WithSchema(networkServiceMethods.ByName("ListPorts")),
			connect.WithClientOptions(opts...),
		),
		updatePort: connect.NewClient[v2.UpdatePortRequest, v2.VirtualPort](
			httpClient,
			baseURL+NetworkServiceUpdatePortProcedure,
			connect.WithSchema(networkServiceMethods.ByName("UpdatePort")),
			connect.WithClientOptions(opts...),
		),
		deletePort: connect.NewClient[v2.DeletePortRequest, emptypb.Empty](
			httpClient,
			baseURL+NetworkServiceDeletePortProcedure,
			connect.WithSchema(networkServiceMethods.ByName("DeletePort")),
			connect.WithClientOptions(opts...),
		),
		attachPort: connect.NewClient[v2.AttachPortRequest, emptypb.Empty](
			httpClient,
			baseURL+NetworkServiceAttachPortProcedure,
			connect.WithSchema(networkServiceMethods.ByName("AttachPort")),
			connect.WithClientOptions(opts...),
		),
		detachPort: connect.NewClient[v2.DetachPortRequest, emptypb.Empty](
			httpClient,
			baseURL+NetworkServiceDetachPortProcedure,
			connect.WithSchema(networkServiceMethods.ByName("DetachPort")),
			connect.WithClientOptions(opts...),
		),
		createVLANRange: connect.NewClient[v2.CreateVLANRangeRequest, v2.VLANRange](
			httpClient,
			baseURL+NetworkServiceCreateVLANRangeProcedure,
			connect.WithSchema(networkServiceMethods.ByName("CreateVLANRange")),
			connect.WithClientOptions(opts...),
		),
		listVLANRanges: connect.NewClient[v2.ListVLANRangesRequest, v2.ListVLANRangesResponse](
			httpClient,
			baseURL+NetworkServiceListVLANRangesProcedure,
			connect.WithSchema(networkServiceMethods.ByName("ListVLANRanges")),
			connect.WithClientOptions(opts...),
		),
		allocateVLAN: connect.NewClient[v2.AllocateVLANRequest, v2.VLANAllocation](
			httpClient,
			baseURL+NetworkServiceAllocateVLANProcedure,
			connect.WithSchema(networkServiceMethods.ByName("AllocateVLAN")),
			connect.WithClientOptions(opts...),
		),
		releaseVLAN: connect.NewClient[v2.ReleaseVLANRequest, emptypb.Empty](
			httpClient,
			baseURL+NetworkServiceReleaseVLANProcedure,
			connect.WithSchema(networkServiceMethods.ByName("ReleaseVLAN")),
			connect.WithClientOptions(opts...),
		),
		createVirtualCloud: connect.NewClient[v2.CreateVirtualCloudRequest, v2.VirtualCloud](
			httpClient,
			baseURL+NetworkServiceCreateVirtualCloudProcedure,
			connect.WithSchema(networkServiceMethods.ByName("CreateVirtualCloud")),
			connect.WithClientOptions(opts...),
		),
		getVirtualCloud: connect.NewClient[v2.GetVirtualCloudRequest, v2.VirtualCloud](
			httpClient,
			baseURL+NetworkServiceGetVirtualCloudProcedure,
			connect.WithSchema(networkServiceMethods.ByName("GetVirtualCloud")),
			connect.WithClientOptions(opts...),
		),
		listVirtualClouds: connect.NewClient[v2.ListVirtualCloudsRequest, v2.ListVirtualCloudsResponse](
			httpClient,
			baseURL+NetworkServiceListVirtualCloudsProcedure,
			connect.WithSchema(networkServiceMethods.ByName("ListVirtualClouds")),
			connect.WithClientOptions(opts...),
		),
		updateVirtualCloud: connect.NewClient[v2.UpdateVirtualCloudRequest, v2.VirtualCloud](
			httpClient,
			baseURL+NetworkServiceUpdateVirtualCloudProcedure,
			connect.WithSchema(networkServiceMethods.ByName("UpdateVirtualCloud")),
			connect.WithClientOptions(opts...),
		),
		deleteVirtualCloud: connect.NewClient[v2.DeleteVirtualCloudRequest, emptypb.Empty](
			httpClient,
			baseURL+NetworkServiceDeleteVirtualCloudProcedure,
			connect.WithSchema(networkServiceMethods.ByName("DeleteVirtualCloud")),
			connect.WithClientOptions(opts...),
		),
		addVNIEndpoint: connect.NewClient[v2.AddVNIEndpointRequest, emptypb.Empty](
			httpClient,
			baseURL+NetworkServiceAddVNIEndpointProcedure,
			connect.WithSchema(networkServiceMethods.ByName("AddVNIEndpoint")),
			connect.WithClientOptions(opts...),
		),
		removeVNIEndpoint: connect.NewClient[v2.RemoveVNIEndpointRequest, emptypb.Empty](
			httpClient,
			baseURL+NetworkServiceRemoveVNIEndpointProcedure,
			connect.WithSchema(networkServiceMethods.ByName("RemoveVNIEndpoint")),
			connect.WithClientOptions(opts...),
		),
		allocateVNI: connect.NewClient[v2.AllocateVNIRequest, v2.VNIAllocation](
			httpClient,
			baseURL+NetworkServiceAllocateVNIProcedure,
			connect.WithSchema(networkServiceMethods.ByName("AllocateVNI")),
			connect.WithClientOptions(opts...),
		),
		releaseVNI: connect.NewClient[v2.ReleaseVNIRequest, emptypb.Empty](
			httpClient,
			baseURL+NetworkServiceReleaseVNIProcedure,
			connect.WithSchema(networkServiceMethods.ByName("ReleaseVNI")),
			connect.WithClientOptions(opts...),
		),
	}
}

// networkServiceClient implements NetworkServiceClient.
type networkServiceClient struct {
	createNetwork      *connect.Client[v2.CreateNetworkRequest, v2.VirtualNetwork]
	getNetwork         *connect.Client[v2.GetNetworkRequest, v2.VirtualNetwork]
	listNetworks       *connect.Client[v2.ListNetworksRequest, v2.ListNetworksResponse]
	updateNetwork      *connect.Client[v2.UpdateNetworkRequest, v2.VirtualNetwork]
	deleteNetwork      *connect.Client[v2.DeleteNetworkRequest, emptypb.Empty]
	attachHosts        *connect.Client[v2.AttachHostsRequest, emptypb.Empty]
	detachHosts        *connect.Client[v2.DetachHostsRequest, emptypb.Empty]
	createPort         *connect.Client[v2.CreatePortRequest, v2.VirtualPort]
	getPort            *connect.Client[v2.GetPortRequest, v2.VirtualPort]
	listPorts          *connect.Client[v2.ListPortsRequest, v2.ListPortsResponse]
	updatePort         *connect.Client[v2.UpdatePortRequest, v2.VirtualPort]
	deletePort         *connect.Client[v2.DeletePortRequest, emptypb.Empty]
	attachPort         *connect.Client[v2.AttachPortRequest, emptypb.Empty]
	detachPort         *connect.Client[v2.DetachPortRequest, emptypb.Empty]
	createVLANRange    *connect.Client[v2.CreateVLANRangeRequest, v2.VLANRange]
	listVLANRanges     *connect.Client[v2.ListVLANRangesRequest, v2.ListVLANRangesResponse]
	allocateVLAN       *connect.Client[v2.AllocateVLANRequest, v2.VLANAllocation]
	releaseVLAN        *connect.Client[v2.ReleaseVLANRequest, emptypb.Empty]
	createVirtualCloud *connect.Client[v2.CreateVirtualCloudRequest, v2.VirtualCloud]
	getVirtualCloud    *connect.Client[v2.GetVirtualCloudRequest, v2.VirtualCloud]
	listVirtualClouds  *connect.Client[v2.ListVirtualCloudsRequest, v2.ListVirtualCloudsResponse]
	updateVirtualCloud *connect.Client[v2.UpdateVirtualCloudRequest, v2.VirtualCloud]
	deleteVirtualCloud *connect.Client[v2.DeleteVirtualCloudRequest, emptypb.Empty]
	addVNIEndpoint     *connect.Client[v2.AddVNIEndpointRequest, emptypb.Empty]
	removeVNIEndpoint  *connect.Client[v2.RemoveVNIEndpointRequest, emptypb.Empty]
	allocateVNI        *connect.Client[v2.AllocateVNIRequest, v2.VNIAllocation]
	releaseVNI         *connect.Client[v2.ReleaseVNIRequest, emptypb.Empty]
}

// CreateNetwork calls pilab.network.v2.NetworkService.CreateNetwork.
func (c *networkServiceClient) CreateNetwork(ctx context.Context, req *connect.Request[v2.CreateNetworkRequest]) (*connect.Response[v2.VirtualNetwork], error) {
	return c.createNetwork.CallUnary(ctx, req)
}

// GetNetwork calls pilab.network.v2.NetworkService.GetNetwork.
func (c *networkServiceClient) GetNetwork(ctx context.Context, req *connect.Request[v2.GetNetworkRequest]) (*connect.Response[v2.VirtualNetwork], error) {
	return c.getNetwork.CallUnary(ctx, req)
}

// ListNetworks calls pilab.network.v2.NetworkService.ListNetworks.
func (c *networkServiceClient) ListNetworks(ctx context.Context, req *connect.Request[v2.ListNetworksRequest]) (*connect.Response[v2.ListNetworksResponse], error) {
	return c.listNetworks.CallUnary(ctx, req)
}

// UpdateNetwork calls pilab.network.v2.NetworkService.UpdateNetwork.
func (c *networkServiceClient) UpdateNetwork(ctx context.Context, req *connect.Request[v2.UpdateNetworkRequest]) (*connect.Response[v2.VirtualNetwork], error) {
	return c.updateNetwork.CallUnary(ctx, req)
}

// DeleteNetwork calls pilab.network.v2.NetworkService.DeleteNetwork.
func (c *networkServiceClient) DeleteNetwork(ctx context.Context, req *connect.Request[v2.DeleteNetworkRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.deleteNetwork.CallUnary(ctx, req)
}

// AttachHosts calls pilab.network.v2.NetworkService.AttachHosts.
func (c *networkServiceClient) AttachHosts(ctx context.Context, req *connect.Request[v2.AttachHostsRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.attachHosts.CallUnary(ctx, req)
}

// DetachHosts calls pilab.network.v2.NetworkService.DetachHosts.
func (c *networkServiceClient) DetachHosts(ctx context.Context, req *connect.Request[v2.DetachHostsRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.detachHosts.CallUnary(ctx, req)
}

// CreatePort calls pilab.network.v2.NetworkService.CreatePort.
func (c *networkServiceClient) CreatePort(ctx context.Context, req *connect.Request[v2.CreatePortRequest]) (*connect.Response[v2.VirtualPort], error) {
	return c.createPort.CallUnary(ctx, req)
}

// GetPort calls pilab.network.v2.NetworkService.GetPort.
func (c *networkServiceClient) GetPort(ctx context.Context, req *connect.Request[v2.GetPortRequest]) (*connect.Response[v2.VirtualPort], error) {
	return c.getPort.CallUnary(ctx, req)
}

// ListPorts calls pilab.network.v2.NetworkService.ListPorts.
func (c *networkServiceClient) ListPorts(ctx context.Context, req *connect.Request[v2.ListPortsRequest]) (*connect.Response[v2.ListPortsResponse], error) {
	return c.listPorts.CallUnary(ctx, req)
}

// UpdatePort calls pilab.network.v2.NetworkService.UpdatePort.
func (c *networkServiceClient) UpdatePort(ctx context.Context, req *connect.Request[v2.UpdatePortRequest]) (*connect.Response[v2.VirtualPort], error) {
	return c.updatePort.CallUnary(ctx, req)
}

// DeletePort calls pilab.network.v2.NetworkService.DeletePort.
func (c *networkServiceClient) DeletePort(ctx context.Context, req *connect.Request[v2.DeletePortRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.deletePort.CallUnary(ctx, req)
}

// AttachPort calls pilab.network.v2.NetworkService.AttachPort.
func (c *networkServiceClient) AttachPort(ctx context.Context, req *connect.Request[v2.AttachPortRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.attachPort.CallUnary(ctx, req)
}

// DetachPort calls pilab.network.v2.NetworkService.DetachPort.
func (c *networkServiceClient) DetachPort(ctx context.Context, req *connect.Request[v2.DetachPortRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.detachPort.CallUnary(ctx, req)
}

// CreateVLANRange calls pilab.network.v2.NetworkService.CreateVLANRange.
func (c *networkServiceClient) CreateVLANRange(ctx context.Context, req *connect.Request[v2.CreateVLANRangeRequest]) (*connect.Response[v2.VLANRange], error) {
	return c.createVLANRange.CallUnary(ctx, req)
}

// ListVLANRanges calls pilab.network.v2.NetworkService.ListVLANRanges.
func (c *networkServiceClient) ListVLANRanges(ctx context.Context, req *connect.Request[v2.ListVLANRangesRequest]) (*connect.Response[v2.ListVLANRangesResponse], error) {
	return c.listVLANRanges.CallUnary(ctx, req)
}

// AllocateVLAN calls pilab.network.v2.NetworkService.AllocateVLAN.
func (c *networkServiceClient) AllocateVLAN(ctx context.Context, req *connect.Request[v2.AllocateVLANRequest]) (*connect.Response[v2.VLANAllocation], error) {
	return c.allocateVLAN.CallUnary(ctx, req)
}

// ReleaseVLAN calls pilab.network.v2.NetworkService.ReleaseVLAN.
func (c *networkServiceClient) ReleaseVLAN(ctx context.Context, req *connect.Request[v2.ReleaseVLANRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.releaseVLAN.CallUnary(ctx, req)
}

// CreateVirtualCloud calls pilab.network.v2.NetworkService.CreateVirtualCloud.
func (c *networkServiceClient) CreateVirtualCloud(ctx context.Context, req *connect.Request[v2.CreateVirtualCloudRequest]) (*connect.Response[v2.VirtualCloud], error) {
	return c.createVirtualCloud.CallUnary(ctx, req)
}

// GetVirtualCloud calls pilab.network.v2.NetworkService.GetVirtualCloud.
func (c *networkServiceClient) GetVirtualCloud(ctx context.Context, req *connect.Request[v2.GetVirtualCloudRequest]) (*connect.Response[v2.VirtualCloud], error) {
	return c.getVirtualCloud.CallUnary(ctx, req)
}

// ListVirtualClouds calls pilab.network.v2.NetworkService.ListVirtualClouds.
func (c *networkServiceClient) ListVirtualClouds(ctx context.Context, req *connect.Request[v2.ListVirtualCloudsRequest]) (*connect.Response[v2.ListVirtualCloudsResponse], error) {
	return c.listVirtualClouds.CallUnary(ctx, req)
}

// UpdateVirtualCloud calls pilab.network.v2.NetworkService.UpdateVirtualCloud.
func (c *networkServiceClient) UpdateVirtualCloud(ctx context.Context, req *connect.Request[v2.UpdateVirtualCloudRequest]) (*connect.Response[v2.VirtualCloud], error) {
	return c.updateVirtualCloud.CallUnary(ctx, req)
}

// DeleteVirtualCloud calls pilab.network.v2.NetworkService.DeleteVirtualCloud.
func (c *networkServiceClient) DeleteVirtualCloud(ctx context.Context, req *connect.Request[v2.DeleteVirtualCloudRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.deleteVirtualCloud.CallUnary(ctx, req)
}

// AddVNIEndpoint calls pilab.network.v2.NetworkService.AddVNIEndpoint.
func (c *networkServiceClient) AddVNIEndpoint(ctx context.Context, req *connect.Request[v2.AddVNIEndpointRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.addVNIEndpoint.CallUnary(ctx, req)
}

// RemoveVNIEndpoint calls pilab.network.v2.NetworkService.RemoveVNIEndpoint.
func (c *networkServiceClient) RemoveVNIEndpoint(ctx context.Context, req *connect.Request[v2.RemoveVNIEndpointRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.removeVNIEndpoint.CallUnary(ctx, req)
}

// AllocateVNI calls pilab.network.v2.NetworkService.AllocateVNI.
func (c *networkServiceClient) AllocateVNI(ctx context.Context, req *connect.Request[v2.AllocateVNIRequest]) (*connect.Response[v2.VNIAllocation], error) {
	return c.allocateVNI.CallUnary(ctx, req)
}

// ReleaseVNI calls pilab.network.v2.NetworkService.ReleaseVNI.
func (c *networkServiceClient) ReleaseVNI(ctx context.Context, req *connect.Request[v2.ReleaseVNIRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.releaseVNI.CallUnary(ctx, req)
}

// NetworkServiceHandler is an implementation of the pilab.network.v2.NetworkService service.
type NetworkServiceHandler interface {
	// Network operations
	CreateNetwork(context.Context, *connect.Request[v2.CreateNetworkRequest]) (*connect.Response[v2.VirtualNetwork], error)
	GetNetwork(context.Context, *connect.Request[v2.GetNetworkRequest]) (*connect.Response[v2.VirtualNetwork], error)
	ListNetworks(context.Context, *connect.Request[v2.ListNetworksRequest]) (*connect.Response[v2.ListNetworksResponse], error)
	UpdateNetwork(context.Context, *connect.Request[v2.UpdateNetworkRequest]) (*connect.Response[v2.VirtualNetwork], error)
	DeleteNetwork(context.Context, *connect.Request[v2.DeleteNetworkRequest]) (*connect.Response[emptypb.Empty], error)
	AttachHosts(context.Context, *connect.Request[v2.AttachHostsRequest]) (*connect.Response[emptypb.Empty], error)
	DetachHosts(context.Context, *connect.Request[v2.DetachHostsRequest]) (*connect.Response[emptypb.Empty], error)
	// Port operations
	CreatePort(context.Context, *connect.Request[v2.CreatePortRequest]) (*connect.Response[v2.VirtualPort], error)
	GetPort(context.Context, *connect.Request[v2.GetPortRequest]) (*connect.Response[v2.VirtualPort], error)
	ListPorts(context.Context, *connect.Request[v2.ListPortsRequest]) (*connect.Response[v2.ListPortsResponse], error)
	UpdatePort(context.Context, *connect.Request[v2.UpdatePortRequest]) (*connect.Response[v2.VirtualPort], error)
	DeletePort(context.Context, *connect.Request[v2.DeletePortRequest]) (*connect.Response[emptypb.Empty], error)
	AttachPort(context.Context, *connect.Request[v2.AttachPortRequest]) (*connect.Response[emptypb.Empty], error)
	DetachPort(context.Context, *connect.Request[v2.DetachPortRequest]) (*connect.Response[emptypb.Empty], error)
	// VLAN operations
	CreateVLANRange(context.Context, *connect.Request[v2.CreateVLANRangeRequest]) (*connect.Response[v2.VLANRange], error)
	ListVLANRanges(context.Context, *connect.Request[v2.ListVLANRangesRequest]) (*connect.Response[v2.ListVLANRangesResponse], error)
	AllocateVLAN(context.Context, *connect.Request[v2.AllocateVLANRequest]) (*connect.Response[v2.VLANAllocation], error)
	ReleaseVLAN(context.Context, *connect.Request[v2.ReleaseVLANRequest]) (*connect.Response[emptypb.Empty], error)
	// Virtual cloud (VXLAN) operations
	CreateVirtualCloud(context.Context, *connect.Request[v2.CreateVirtualCloudRequest]) (*connect.Response[v2.VirtualCloud], error)
	GetVirtualCloud(context.Context, *connect.Request[v2.GetVirtualCloudRequest]) (*connect.Response[v2.VirtualCloud], error)
	ListVirtualClouds(context.Context, *connect.Request[v2.ListVirtualCloudsRequest]) (*connect.Response[v2.ListVirtualCloudsResponse], error)
	UpdateVirtualCloud(context.Context, *connect.Request[v2.UpdateVirtualCloudRequest]) (*connect.Response[v2.VirtualCloud], error)
	DeleteVirtualCloud(context.Context, *connect.Request[v2.DeleteVirtualCloudRequest]) (*connect.Response[emptypb.Empty], error)
	AddVNIEndpoint(context.Context, *connect.Request[v2.AddVNIEndpointRequest]) (*connect.Response[emptypb.Empty], error)
	RemoveVNIEndpoint(context.Context, *connect.Request[v2.RemoveVNIEndpointRequest]) (*connect.Response[emptypb.Empty], error)
	AllocateVNI(context.Context, *connect.Request[v2.AllocateVNIRequest]) (*connect.Response[v2.VNIAllocation], error)
	ReleaseVNI(context.Context, *connect.Request[v2.ReleaseVNIRequest]) (*connect.Response[emptypb.Empty], error)
}

// NewNetworkServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewNetworkServiceHandler(svc NetworkServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	networkServiceMethods := v2.File_pilab_network_v2_network_service_proto.Services().ByName("NetworkService").Methods()
	networkServiceCreateNetworkHandler := connect.NewUnaryHandler(
		NetworkServiceCreateNetworkProcedure,
		svc.CreateNetwork,
		connect.WithSchema(networkServiceMethods.ByName("CreateNetwork")),
		connect.WithHandlerOptions(opts...),
	)
	networkServiceGetNetworkHandler := connect.NewUnaryHandler(
		NetworkServiceGetNetworkProcedure,
		svc.GetNetwork,
		connect.WithSchema(networkServiceMethods.ByName("GetNetwork")),
		connect.WithHandlerOptions(opts...),
	)
	networkServiceListNetworksHandler := connect.NewUnaryHandler(
		NetworkServiceListNetworksProcedure,
		svc.ListNetworks,
		connect.WithSchema(networkServiceMethods.ByName("ListNetworks")),
		connect.WithHandlerOptions(opts...),
	)
	networkServiceUpdateNetworkHandler := connect.NewUnaryHandler(
		NetworkServiceUpdateNetworkProcedure,
		svc.UpdateNetwork,
		connect.WithSchema(networkServiceMethods.ByName("UpdateNetwork")),
		connect.WithHandlerOptions(opts...),
	)
	networkServiceDeleteNetworkHandler := connect.NewUnaryHandler(
		NetworkServiceDeleteNetworkProcedure,
		svc.DeleteNetwork,
		connect.WithSchema(networkServiceMethods.ByName("DeleteNetwork")),
		connect.WithHandlerOptions(opts...),
	)
	networkServiceAttachHostsHandler := connect.NewUnaryHandler(
		NetworkServiceAttachHostsProcedure,
		svc.AttachHosts,
		connect.WithSchema(networkServiceMethods.ByName("AttachHosts")),
		connect.WithHandlerOptions(opts...),
	)
	networkServiceDetachHostsHandler := connect.NewUnaryHandler(
		NetworkServiceDetachHostsProcedure,
		svc.DetachHosts,
		connect.WithSchema(networkServiceMethods.ByName("DetachHosts")),
		connect.WithHandlerOptions(opts...),
	)
	networkServiceCreatePortHandler := connect.NewUnaryHandler(
		NetworkServiceCreatePortProcedure,
		svc.CreatePort,
		connect.WithSchema(networkServiceMethods.ByName("CreatePort")),
		connect.WithHandlerOptions(opts...),
	)
	networkServiceGetPortHandler := connect.NewUnaryHandler(
		NetworkServiceGetPortProcedure,
		svc.GetPort,
		connect.WithSchema(networkServiceMethods.ByName("GetPort")),
		connect.WithHandlerOptions(opts...),
	)
	networkServiceListPortsHandler := connect.NewUnaryHandler(
		NetworkServiceListPortsProcedure,
		svc.ListPorts,
		connect.WithSchema(networkServiceMethods.ByName("ListPorts")),
		connect.WithHandlerOptions(opts...),
	)
	networkServiceUpdatePortHandler := connect.NewUnaryHandler(
		NetworkServiceUpdatePortProcedure,
		svc.UpdatePort,
		connect.WithSchema(networkServiceMethods.ByName("UpdatePort")),
		connect.WithHandlerOptions(opts...),
	)
	networkServiceDeletePortHandler := connect.NewUnaryHandler(
		NetworkServiceDeletePortProcedure,
		svc.DeletePort,
		connect.WithSchema(networkServiceMethods.ByName("DeletePort")),
		connect.WithHandlerOptions(opts...),
	)
	networkServiceAttachPortHandler := connect.NewUnaryHandler(
		NetworkServiceAttachPortProcedure,
		svc.AttachPort,
		connect.WithSchema(networkServiceMethods.ByName("AttachPort")),
		connect.WithHandlerOptions(opts...),
	)
	networkServiceDetachPortHandler := connect.NewUnaryHandler(
		NetworkServiceDetachPortProcedure,
		svc.DetachPort,
		connect.WithSchema(networkServiceMethods.ByName("DetachPort")),
		connect.WithHandlerOptions(opts...),
	)
	networkServiceCreateVLANRangeHandler := connect.NewUnaryHandler(
		NetworkServiceCreateVLANRangeProcedure,
		svc.CreateVLANRange,
		connect.WithSchema(networkServiceMethods.ByName("CreateVLANRange")),
		connect.WithHandlerOptions(opts...),
	)
	networkServiceListVLANRangesHandler := connect.NewUnaryHandler(
		NetworkServiceListVLANRangesProcedure,
		svc.ListVLANRanges,
		connect.WithSchema(networkServiceMethods.ByName("ListVLANRanges")),
		connect.WithHandlerOptions(opts...),
	)
	networkServiceAllocateVLANHandler := connect.NewUnaryHandler(
		NetworkServiceAllocateVLANProcedure,
		svc.AllocateVLAN,
		connect.WithSchema(networkServiceMethods.ByName("AllocateVLAN")),
		connect.WithHandlerOptions(opts...),
	)
	networkServiceReleaseVLANHandler := connect.NewUnaryHandler(
		NetworkServiceReleaseVLANProcedure,
		svc.ReleaseVLAN,
		connect.WithSchema(networkServiceMethods.ByName("ReleaseVLAN")),
		connect.WithHandlerOptions(opts...),
	)
	networkServiceCreateVirtualCloudHandler := connect.NewUnaryHandler(
		NetworkServiceCreateVirtualCloudProcedure,
		svc.CreateVirtualCloud,
		connect.WithSchema(networkServiceMethods.ByName("CreateVirtualCloud")),
		connect.WithHandlerOptions(opts...),
	)
	networkServiceGetVirtualCloudHandler := connect.NewUnaryHandler(
		NetworkServiceGetVirtualCloudProcedure,
		svc.GetVirtualCloud,
		connect.WithSchema(networkServiceMethods.ByName("GetVirtualCloud")),
		connect.WithHandlerOptions(opts...),
	)
	networkServiceListVirtualCloudsHandler := connect.NewUnaryHandler(
		NetworkServiceListVirtualCloudsProcedure,
		svc.ListVirtualClouds,
		connect.WithSchema(networkServiceMethods.ByName("ListVirtualClouds")),
		connect.WithHandlerOptions(opts...),
	)
	networkServiceUpdateVirtualCloudHandler := connect.NewUnaryHandler(
		NetworkServiceUpdateVirtualCloudProcedure,
		svc.UpdateVirtualCloud,
		connect.WithSchema(networkServiceMethods.ByName("UpdateVirtualCloud")),
		connect.WithHandlerOptions(opts...),
	)
	networkServiceDeleteVirtualCloudHandler := connect.NewUnaryHandler(
		NetworkServiceDeleteVirtualCloudProcedure,
		svc.DeleteVirtualCloud,
		connect.WithSchema(networkServiceMethods.ByName("DeleteVirtualCloud")),
		connect.WithHandlerOptions(opts...),
	)
	networkServiceAddVNIEndpointHandler := connect.NewUnaryHandler(
		NetworkServiceAddVNIEndpointProcedure,
		svc.AddVNIEndpoint,
		connect.WithSchema(networkServiceMethods.ByName("AddVNIEndpoint")),
		connect.WithHandlerOptions(opts...),
	)
	networkServiceRemoveVNIEndpointHandler := connect.NewUnaryHandler(
		NetworkServiceRemoveVNIEndpointProcedure,
		svc.RemoveVNIEndpoint,
		connect.WithSchema(networkServiceMethods.ByName("RemoveVNIEndpoint")),
		connect.WithHandlerOptions(opts...),
	)
	networkServiceAllocateVNIHandler := connect.NewUnaryHandler(
		NetworkServiceAllocateVNIProcedure,
		svc.AllocateVNI,
		connect.WithSchema(networkServiceMethods.ByName("AllocateVNI")),
		connect.WithHandlerOptions(opts...),
	)
	networkServiceReleaseVNIHandler := connect.NewUnaryHandler(
		NetworkServiceReleaseVNIProcedure,
		svc.ReleaseVNI,
		connect.WithSchema(networkServiceMethods.ByName("ReleaseVNI")),
		connect.WithHandlerOptions(opts...),
	)
	return "/pilab.network.v2.NetworkService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case NetworkServiceCreateNetworkProcedure:
			networkServiceCreateNetworkHandler.ServeHTTP(w, r)
		case NetworkServiceGetNetworkProcedure:
			networkServiceGetNetworkHandler.ServeHTTP(w, r)
		case NetworkServiceListNetworksProcedure:
			networkServiceListNetworksHandler.ServeHTTP(w, r)
		case NetworkServiceUpdateNetworkProcedure:
			networkServiceUpdateNetworkHandler.ServeHTTP(w, r)
		case NetworkServiceDeleteNetworkProcedure:
			networkServiceDeleteNetworkHandler.ServeHTTP(w, r)
		case NetworkServiceAttachHostsProcedure:
			networkServiceAttachHostsHandler.ServeHTTP(w, r)
		case NetworkServiceDetachHostsProcedure:
			networkServiceDetachHostsHandler.ServeHTTP(w, r)
		case NetworkServiceCreatePortProcedure:
			networkServiceCreatePortHandler.ServeHTTP(w, r)
		case NetworkServiceGetPortProcedure:
			networkServiceGetPortHandler.ServeHTTP(w, r)
		case NetworkServiceListPortsProcedure:
			networkServiceListPortsHandler.ServeHTTP(w, r)
		case NetworkServiceUpdatePortProcedure:
			networkServiceUpdatePortHandler.ServeHTTP(w, r)
		case NetworkServiceDeletePortProcedure:
			networkServiceDeletePortHandler.ServeHTTP(w, r)
		case NetworkServiceAttachPortProcedure:
			networkServiceAttachPortHandler.ServeHTTP(w, r)
		case NetworkServiceDetachPortProcedure:
			networkServiceDetachPortHandler.ServeHTTP(w, r)
		case NetworkServiceCreateVLANRangeProcedure:
			networkServiceCreateVLANRangeHandler.ServeHTTP(w, r)
		case NetworkServiceListVLANRangesProcedure:
			networkServiceListVLANRangesHandler.ServeHTTP(w, r)
		case NetworkServiceAllocateVLANProcedure:
			networkServiceAllocateVLANHandler.ServeHTTP(w, r)
		case NetworkServiceReleaseVLANProcedure:
			networkServiceReleaseVLANHandler.ServeHTTP(w, r)
		case NetworkServiceCreateVirtualCloudProcedure:
			networkServiceCreateVirtualCloudHandler.ServeHTTP(w, r)
		case NetworkServiceGetVirtualCloudProcedure:
			networkServiceGetVirtualCloudHandler.ServeHTTP(w, r)
		case NetworkServiceListVirtualCloudsProcedure:
			networkServiceListVirtualCloudsHandler.ServeHTTP(w, r)
		case NetworkServiceUpdateVirtualCloudProcedure:
			networkServiceUpdateVirtualCloudHandler.ServeHTTP(w, r)
		case NetworkServiceDeleteVirtualCloudProcedure:
			networkServiceDeleteVirtualCloudHandler.ServeHTTP(w, r)
		case NetworkServiceAddVNIEndpointProcedure:
			networkServiceAddVNIEndpointHandler.ServeHTTP(w, r)
		case NetworkServiceRemoveVNIEndpointProcedure:
			networkServiceRemoveVNIEndpointHandler.ServeHTTP(w, r)
		case NetworkServiceAllocateVNIProcedure:
			networkServiceAllocateVNIHandler.ServeHTTP(w, r)
		case NetworkServiceReleaseVNIProcedure:
			networkServiceReleaseVNIHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedNetworkServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedNetworkServiceHandler struct{}

func (UnimplementedNetworkServiceHandler) CreateNetwork(context.Context, *connect.Request[v2.CreateNetworkRequest]) (*connect.Response[v2.VirtualNetwork], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pilab.network.v2.NetworkService.CreateNetwork is not implemented"))
}

func (UnimplementedNetworkServiceHandler) GetNetwork(context.Context, *connect.Request[v2.GetNetworkRequest]) (*connect.Response[v2.VirtualNetwork], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pilab.network.v2.NetworkService.GetNetwork is not implemented"))
}

func (UnimplementedNetworkServiceHandler) ListNetworks(context.Context, *connect.Request[v2.ListNetworksRequest]) (*connect.Response[v2.ListNetworksResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pilab.network.v2.NetworkService.ListNetworks is not implemented"))
}

func (UnimplementedNetworkServiceHandler) UpdateNetwork(context.Context, *connect.Request[v2.UpdateNetworkRequest]) (*connect.Response[v2.VirtualNetwork], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pilab.network.v2.NetworkService.UpdateNetwork is not implemented"))
}

func (UnimplementedNetworkServiceHandler) DeleteNetwork(context.Context, *connect.Request[v2.DeleteNetworkRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pilab.network.v2.NetworkService.DeleteNetwork is not implemented"))
}

func (UnimplementedNetworkServiceHandler) AttachHosts(context.Context, *connect.Request[v2.AttachHostsRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pilab.network.v2.NetworkService.AttachHosts is not implemented"))
}

func (UnimplementedNetworkServiceHandler) DetachHosts(context.Context, *connect.Request[v2.DetachHostsRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pilab.network.v2.NetworkService.DetachHosts is not implemented"))
}

func (UnimplementedNetworkServiceHandler) CreatePort(context.Context, *connect.Request[v2.CreatePortRequest]) (*connect.Response[v2.VirtualPort], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pilab.network.v2.NetworkService.CreatePort is not implemented"))
}

func (UnimplementedNetworkServiceHandler) GetPort(context.Context, *connect.Request[v2.GetPortRequest]) (*connect.Response[v2.VirtualPort], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pilab.network.v2.NetworkService.GetPort is not implemented"))
}

func (UnimplementedNetworkServiceHandler) ListPorts(context.Context, *connect.Request[v2.ListPortsRequest]) (*connect.Response[v2.ListPortsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pilab.network.v2.NetworkService.ListPorts is not implemented"))
}

func (UnimplementedNetworkServiceHandler) UpdatePort(context.Context, *connect.Request[v2.UpdatePortRequest]) (*connect.Response[v2.VirtualPort], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pilab.network.v2.NetworkService.UpdatePort is not implemented"))
}

func (UnimplementedNetworkServiceHandler) DeletePort(context.Context, *connect.Request[v2.DeletePortRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pilab.network.v2.NetworkService.DeletePort is not implemented"))
}

func (UnimplementedNetworkServiceHandler) AttachPort(context.Context, *connect.Request[v2.AttachPortRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pilab.network.v2.NetworkService.AttachPort is not implemented"))
}

func (UnimplementedNetworkServiceHandler) DetachPort(context.Context, *connect.Request[v2.DetachPortRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pilab.network.v2.NetworkService.DetachPort is not implemented"))
}

func (UnimplementedNetworkServiceHandler) CreateVLANRange(context.Context, *connect.Request[v2.CreateVLANRangeRequest]) (*connect.Response[v2.VLANRange], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pilab.network.v2.NetworkService.CreateVLANRange is not implemented"))
}

func (UnimplementedNetworkServiceHandler) ListVLANRanges(context.Context, *connect.Request[v2.ListVLANRangesRequest]) (*connect.Response[v2.ListVLANRangesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pilab.network.v2.NetworkService.ListVLANRanges is not implemented"))
}

func (UnimplementedNetworkServiceHandler) AllocateVLAN(context.Context, *connect.Request[v2.AllocateVLANRequest]) (*connect.Response[v2.VLANAllocation], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pilab.network.v2.NetworkService.AllocateVLAN is not implemented"))
}

func (UnimplementedNetworkServiceHandler) ReleaseVLAN(context.Context, *connect.Request[v2.ReleaseVLANRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pilab.network.v2.NetworkService.ReleaseVLAN is not implemented"))
}

func (UnimplementedNetworkServiceHandler) CreateVirtualCloud(context.Context, *connect.Request[v2.CreateVirtualCloudRequest]) (*connect.Response[v2.VirtualCloud], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pilab.network.v2.NetworkService.CreateVirtualCloud is not implemented"))
}

func (UnimplementedNetworkServiceHandler) GetVirtualCloud(context.Context, *connect.Request[v2.GetVirtualCloudRequest]) (*connect.Response[v2.VirtualCloud], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pilab.network.v2.NetworkService.GetVirtualCloud is not implemented"))
}

func (UnimplementedNetworkServiceHandler) ListVirtualClouds(context.Context, *connect.Request[v2.ListVirtualCloudsRequest]) (*connect.Response[v2.ListVirtualCloudsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pilab.network.v2.NetworkService.ListVirtualClouds is not implemented"))
}

func (UnimplementedNetworkServiceHandler) UpdateVirtualCloud(context.Context, *connect.Request[v2.UpdateVirtualCloudRequest]) (*connect.Response[v2.VirtualCloud], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pilab.network.v2.NetworkService.UpdateVirtualCloud is not implemented"))
}

func (UnimplementedNetworkServiceHandler) DeleteVirtualCloud(context.Context, *connect.Request[v2.DeleteVirtualCloudRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pilab.network.v2.NetworkService.DeleteVirtualCloud is not implemented"))
}

func (UnimplementedNetworkServiceHandler) AddVNIEndpoint(context.Context, *connect.Request[v2.AddVNIEndpointRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pilab.network.v2.NetworkService.AddVNIEndpoint is not implemented"))
}

func (UnimplementedNetworkServiceHandler) RemoveVNIEndpoint(context.Context, *connect.Request[v2.RemoveVNIEndpointRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pilab.network.v2.NetworkService.RemoveVNIEndpoint is not implemented"))
}

func (UnimplementedNetworkServiceHandler) AllocateVNI(context.Context, *connect.Request[v2.AllocateVNIRequest]) (*connect.Response[v2.VNIAllocation], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pilab.network.v2.NetworkService.AllocateVNI is not implemented"))
}

func (UnimplementedNetworkServiceHandler) ReleaseVNI(context.Context, *connect.Request[v2.ReleaseVNIRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pilab.network.v2.NetworkService.ReleaseVNI is not implemented"))
}
