// Package network provides virtual networking services including networks,
// ports, VLAN/VXLAN management, IPAM, QoS, security, DVS, and statistics.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: pilab/network/v2/statistics_service.proto

package networkv2connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v2 "go.pilab.hu/cloud/virtpb/pilab/network/v2"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// StatisticsServiceName is the fully-qualified name of the StatisticsService service.
	StatisticsServiceName = "pilab.network.v2.StatisticsService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// StatisticsServiceGetNetworkStatsProcedure is the fully-qualified name of the StatisticsService's
	// GetNetworkStats RPC.
	StatisticsServiceGetNetworkStatsProcedure = "/pilab.network.v2.StatisticsService/GetNetworkStats"
	// StatisticsServiceGetPortStatsProcedure is the fully-qualified name of the StatisticsService's
	// GetPortStats RPC.
	StatisticsServiceGetPortStatsProcedure = "/pilab.network.v2.StatisticsService/GetPortStats"
	// StatisticsServiceGetQoSStatsProcedure is the fully-qualified name of the StatisticsService's
	// GetQoSStats RPC.
	StatisticsServiceGetQoSStatsProcedure = "/pilab.network.v2.StatisticsService/GetQoSStats"
	// StatisticsServiceGetPublicIPUsageProcedure is the fully-qualified name of the StatisticsService's
	// GetPublicIPUsage RPC.
	StatisticsServiceGetPublicIPUsageProcedure = "/pilab.network.v2.StatisticsService/GetPublicIPUsage"
)

// StatisticsServiceClient is a client for the pilab.network.v2.StatisticsService service.
type StatisticsServiceClient interface {
	GetNetworkStats(context.Context, *connect.Request[v2.GetNetworkStatsRequest]) (*connect.Response[v2.NetworkStats], error)
	GetPortStats(context.Context, *connect.Request[v2.GetPortStatsRequest]) (*connect.Response[v2.PortStats], error)
	GetQoSStats(context.Context, *connect.Request[v2.GetQoSStatsRequest]) (*connect.Response[v2.QoSStats], error)
	GetPublicIPUsage(context.Context, *connect.Request[v2.GetPublicIPUsageRequest]) (*connect.Response[v2.PublicIPUsage], error)
}

// NewStatisticsServiceClient constructs a client for the pilab.network.v2.StatisticsService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewStatisticsServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) StatisticsServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	statisticsServiceMethods := v2.File_pilab_network_v2_statistics_service_proto.Services().ByName("StatisticsService").Methods()
	return &statisticsServiceClient{
		getNetworkStats: connect.NewClient[v2.GetNetworkStatsRequest, v2.NetworkStats](
			httpClient,
			baseURL+StatisticsServiceGetNetworkStatsProcedure,
			connect.WithSchema(statisticsServiceMethods.ByName("GetNetworkStats")),
			connect.WithClientOptions(opts...),
		),
		getPortStats: connect.NewClient[v2.GetPortStatsRequest, v2.PortStats](
			httpClient,
			baseURL+StatisticsServiceGetPortStatsProcedure,
			connect.WithSchema(statisticsServiceMethods.ByName("GetPortStats")),
			connect.WithClientOptions(opts...),
		),
		getQoSStats: connect.NewClient[v2.GetQoSStatsRequest, v2.QoSStats](
			httpClient,
			baseURL+StatisticsServiceGetQoSStatsProcedure,
			connect.WithSchema(statisticsServiceMethods.ByName("GetQoSStats")),
			connect.WithClientOptions(opts...),
		),
		getPublicIPUsage: connect.NewClient[v2.GetPublicIPUsageRequest, v2.PublicIPUsage](
			httpClient,
			baseURL+StatisticsServiceGetPublicIPUsageProcedure,
			connect.WithSchema(statisticsServiceMethods.ByName("GetPublicIPUsage")),
			connect.WithClientOptions(opts...),
		),
	}
}

// statisticsServiceClient implements StatisticsServiceClient.
type statisticsServiceClient struct {
	getNetworkStats  *connect.Client[v2.GetNetworkStatsRequest, v2.NetworkStats]
	getPortStats     *connect.Client[v2.GetPortStatsRequest, v2.PortStats]
	getQoSStats      *connect.Client[v2.GetQoSStatsRequest, v2.QoSStats]
	getPublicIPUsage *connect.Client[v2.GetPublicIPUsageRequest, v2.PublicIPUsage]
}

// GetNetworkStats calls pilab.network.v2.StatisticsService.GetNetworkStats.
func (c *statisticsServiceClient) GetNetworkStats(ctx context.Context, req *connect.Request[v2.GetNetworkStatsRequest]) (*connect.Response[v2.NetworkStats], error) {
	return c.getNetworkStats.CallUnary(ctx, req)
}

// GetPortStats calls pilab.network.v2.StatisticsService.GetPortStats.
func (c *statisticsServiceClient) GetPortStats(ctx context.Context, req *connect.Request[v2.GetPortStatsRequest]) (*connect.Response[v2.PortStats], error) {
	return c.getPortStats.CallUnary(ctx, req)
}

// GetQoSStats calls pilab.network.v2.StatisticsService.GetQoSStats.
func (c *statisticsServiceClient) GetQoSStats(ctx context.Context, req *connect.Request[v2.GetQoSStatsRequest]) (*connect.Response[v2.QoSStats], error) {
	return c.getQoSStats.CallUnary(ctx, req)
}

// GetPublicIPUsage calls pilab.network.v2.StatisticsService.GetPublicIPUsage.
func (c *statisticsServiceClient) GetPublicIPUsage(ctx context.Context, req *connect.Request[v2.GetPublicIPUsageRequest]) (*connect.Response[v2.PublicIPUsage], error) {
	return c.getPublicIPUsage.CallUnary(ctx, req)
}

// StatisticsServiceHandler is an implementation of the pilab.network.v2.StatisticsService service.
type StatisticsServiceHandler interface {
	GetNetworkStats(context.Context, *connect.Request[v2.GetNetworkStatsRequest]) (*connect.Response[v2.NetworkStats], error)
	GetPortStats(context.Context, *connect.Request[v2.GetPortStatsRequest]) (*connect.Response[v2.PortStats], error)
	GetQoSStats(context.Context, *connect.Request[v2.GetQoSStatsRequest]) (*connect.Response[v2.QoSStats], error)
	GetPublicIPUsage(context.Context, *connect.Request[v2.GetPublicIPUsageRequest]) (*connect.Response[v2.PublicIPUsage], error)
}

// NewStatisticsServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewStatisticsServiceHandler(svc StatisticsServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	statisticsServiceMethods := v2.File_pilab_network_v2_statistics_service_proto.Services().ByName("StatisticsService").Methods()
	statisticsServiceGetNetworkStatsHandler := connect.NewUnaryHandler(
		StatisticsServiceGetNetworkStatsProcedure,
		svc.GetNetworkStats,
		connect.WithSchema(statisticsServiceMethods.ByName("GetNetworkStats")),
		connect.WithHandlerOptions(opts...),
	)
	statisticsServiceGetPortStatsHandler := connect.NewUnaryHandler(
		StatisticsServiceGetPortStatsProcedure,
		svc.GetPortStats,
		connect.WithSchema(statisticsServiceMethods.ByName("GetPortStats")),
		connect.WithHandlerOptions(opts...),
	)
	statisticsServiceGetQoSStatsHandler := connect.NewUnaryHandler(
		StatisticsServiceGetQoSStatsProcedure,
		svc.GetQoSStats,
		connect.WithSchema(statisticsServiceMethods.ByName("GetQoSStats")),
		connect.WithHandlerOptions(opts...),
	)
	statisticsServiceGetPublicIPUsageHandler := connect.NewUnaryHandler(
		StatisticsServiceGetPublicIPUsageProcedure,
		svc.GetPublicIPUsage,
		connect.WithSchema(statisticsServiceMethods.ByName("GetPublicIPUsage")),
		connect.WithHandlerOptions(opts...),
	)
	return "/pilab.network.v2.StatisticsService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case StatisticsServiceGetNetworkStatsProcedure:
			statisticsServiceGetNetworkStatsHandler.ServeHTTP(w, r)
		case StatisticsServiceGetPortStatsProcedure:
			statisticsServiceGetPortStatsHandler.ServeHTTP(w, r)
		case StatisticsServiceGetQoSStatsProcedure:
			statisticsServiceGetQoSStatsHandler.ServeHTTP(w, r)
		case StatisticsServiceGetPublicIPUsageProcedure:
			statisticsServiceGetPublicIPUsageHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedStatisticsServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedStatisticsServiceHandler struct{}

func (UnimplementedStatisticsServiceHandler) GetNetworkStats(context.Context, *connect.Request[v2.GetNetworkStatsRequest]) (*connect.Response[v2.NetworkStats], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pilab.network.v2.StatisticsService.GetNetworkStats is not implemented"))
}

func (UnimplementedStatisticsServiceHandler) GetPortStats(context.Context, *connect.Request[v2.GetPortStatsRequest]) (*connect.Response[v2.PortStats], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pilab.network.v2.StatisticsService.GetPortStats is not implemented"))
}

func (UnimplementedStatisticsServiceHandler) GetQoSStats(context.Context, *connect.Request[v2.GetQoSStatsRequest]) (*connect.Response[v2.QoSStats], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pilab.network.v2.StatisticsService.GetQoSStats is not implemented"))
}

func (UnimplementedStatisticsServiceHandler) GetPublicIPUsage(context.Context, *connect.Request[v2.GetPublicIPUsageRequest]) (*connect.Response[v2.PublicIPUsage], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pilab.network.v2.StatisticsService.GetPublicIPUsage is not implemented"))
}
