// Package director provides distributed task orchestration and agent coordination.
// This package includes task queue management, job tracking, and director-agent communication.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pilab/director/v1/clouddirector.proto

package directorv1

import (
	v1 "go.pilab.hu/cloud/virtpb/pilab/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VmGuestInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Info          string                 `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VmGuestInfo) Reset() {
	*x = VmGuestInfo{}
	mi := &file_pilab_director_v1_clouddirector_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VmGuestInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmGuestInfo) ProtoMessage() {}

func (x *VmGuestInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pilab_director_v1_clouddirector_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmGuestInfo.ProtoReflect.Descriptor instead.
func (*VmGuestInfo) Descriptor() ([]byte, []int) {
	return file_pilab_director_v1_clouddirector_proto_rawDescGZIP(), []int{0}
}

func (x *VmGuestInfo) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *VmGuestInfo) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

type AgentEventsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*AgentEventsRequest_VmStateEvent
	//	*AgentEventsRequest_Heartbeat
	//	*AgentEventsRequest_VmDefinition
	//	*AgentEventsRequest_HostStats
	//	*AgentEventsRequest_VmMetrics
	//	*AgentEventsRequest_JobStatus
	//	*AgentEventsRequest_VmGuestInfo
	Event         isAgentEventsRequest_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentEventsRequest) Reset() {
	*x = AgentEventsRequest{}
	mi := &file_pilab_director_v1_clouddirector_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentEventsRequest) ProtoMessage() {}

func (x *AgentEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pilab_director_v1_clouddirector_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentEventsRequest.ProtoReflect.Descriptor instead.
func (*AgentEventsRequest) Descriptor() ([]byte, []int) {
	return file_pilab_director_v1_clouddirector_proto_rawDescGZIP(), []int{1}
}

func (x *AgentEventsRequest) GetEvent() isAgentEventsRequest_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *AgentEventsRequest) GetVmStateEvent() *VmStateEvent {
	if x != nil {
		if x, ok := x.Event.(*AgentEventsRequest_VmStateEvent); ok {
			return x.VmStateEvent
		}
	}
	return nil
}

func (x *AgentEventsRequest) GetHeartbeat() *HeartbeatEvent {
	if x != nil {
		if x, ok := x.Event.(*AgentEventsRequest_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentEventsRequest) GetVmDefinition() *VmDefinition {
	if x != nil {
		if x, ok := x.Event.(*AgentEventsRequest_VmDefinition); ok {
			return x.VmDefinition
		}
	}
	return nil
}

func (x *AgentEventsRequest) GetHostStats() *v1.HostStats {
	if x != nil {
		if x, ok := x.Event.(*AgentEventsRequest_HostStats); ok {
			return x.HostStats
		}
	}
	return nil
}

func (x *AgentEventsRequest) GetVmMetrics() *v1.VmMetrics {
	if x != nil {
		if x, ok := x.Event.(*AgentEventsRequest_VmMetrics); ok {
			return x.VmMetrics
		}
	}
	return nil
}

func (x *AgentEventsRequest) GetJobStatus() *v1.JobStatus {
	if x != nil {
		if x, ok := x.Event.(*AgentEventsRequest_JobStatus); ok {
			return x.JobStatus
		}
	}
	return nil
}

func (x *AgentEventsRequest) GetVmGuestInfo() *VmGuestInfo {
	if x != nil {
		if x, ok := x.Event.(*AgentEventsRequest_VmGuestInfo); ok {
			return x.VmGuestInfo
		}
	}
	return nil
}

type isAgentEventsRequest_Event interface {
	isAgentEventsRequest_Event()
}

type AgentEventsRequest_VmStateEvent struct {
	VmStateEvent *VmStateEvent `protobuf:"bytes,1,opt,name=vm_state_event,json=vmStateEvent,proto3,oneof"`
}

type AgentEventsRequest_Heartbeat struct {
	Heartbeat *HeartbeatEvent `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type AgentEventsRequest_VmDefinition struct {
	VmDefinition *VmDefinition `protobuf:"bytes,3,opt,name=vm_definition,json=vmDefinition,proto3,oneof"`
}

type AgentEventsRequest_HostStats struct {
	HostStats *v1.HostStats `protobuf:"bytes,4,opt,name=host_stats,json=hostStats,proto3,oneof"`
}

type AgentEventsRequest_VmMetrics struct {
	VmMetrics *v1.VmMetrics `protobuf:"bytes,5,opt,name=vm_metrics,json=vmMetrics,proto3,oneof"`
}

type AgentEventsRequest_JobStatus struct {
	JobStatus *v1.JobStatus `protobuf:"bytes,6,opt,name=job_status,json=jobStatus,proto3,oneof"`
}

type AgentEventsRequest_VmGuestInfo struct {
	VmGuestInfo *VmGuestInfo `protobuf:"bytes,7,opt,name=vm_guest_info,json=vmGuestInfo,proto3,oneof"`
}

func (*AgentEventsRequest_VmStateEvent) isAgentEventsRequest_Event() {}

func (*AgentEventsRequest_Heartbeat) isAgentEventsRequest_Event() {}

func (*AgentEventsRequest_VmDefinition) isAgentEventsRequest_Event() {}

func (*AgentEventsRequest_HostStats) isAgentEventsRequest_Event() {}

func (*AgentEventsRequest_VmMetrics) isAgentEventsRequest_Event() {}

func (*AgentEventsRequest_JobStatus) isAgentEventsRequest_Event() {}

func (*AgentEventsRequest_VmGuestInfo) isAgentEventsRequest_Event() {}

type HeartbeatEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostId        string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	ElapsedTime   uint32                 `protobuf:"varint,2,opt,name=elapsed_time,json=elapsedTime,proto3" json:"elapsed_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatEvent) Reset() {
	*x = HeartbeatEvent{}
	mi := &file_pilab_director_v1_clouddirector_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatEvent) ProtoMessage() {}

func (x *HeartbeatEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pilab_director_v1_clouddirector_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatEvent.ProtoReflect.Descriptor instead.
func (*HeartbeatEvent) Descriptor() ([]byte, []int) {
	return file_pilab_director_v1_clouddirector_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatEvent) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *HeartbeatEvent) GetElapsedTime() uint32 {
	if x != nil {
		return x.ElapsedTime
	}
	return 0
}

type VmDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DomainXml     string                 `protobuf:"bytes,1,opt,name=domain_xml,json=domainXml,proto3" json:"domain_xml,omitempty"`
	DomainUuid    string                 `protobuf:"bytes,2,opt,name=domain_uuid,json=domainUuid,proto3" json:"domain_uuid,omitempty"`
	State         uint32                 `protobuf:"varint,3,opt,name=state,proto3" json:"state,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VmDefinition) Reset() {
	*x = VmDefinition{}
	mi := &file_pilab_director_v1_clouddirector_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VmDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmDefinition) ProtoMessage() {}

func (x *VmDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_pilab_director_v1_clouddirector_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmDefinition.ProtoReflect.Descriptor instead.
func (*VmDefinition) Descriptor() ([]byte, []int) {
	return file_pilab_director_v1_clouddirector_proto_rawDescGZIP(), []int{3}
}

func (x *VmDefinition) GetDomainXml() string {
	if x != nil {
		return x.DomainXml
	}
	return ""
}

func (x *VmDefinition) GetDomainUuid() string {
	if x != nil {
		return x.DomainUuid
	}
	return ""
}

func (x *VmDefinition) GetState() uint32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *VmDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type VmStateEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	VmName        string                 `protobuf:"bytes,2,opt,name=vm_name,json=vmName,proto3" json:"vm_name,omitempty"`
	Event         string                 `protobuf:"bytes,3,opt,name=event,proto3" json:"event,omitempty"`
	Detail        string                 `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VmStateEvent) Reset() {
	*x = VmStateEvent{}
	mi := &file_pilab_director_v1_clouddirector_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VmStateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmStateEvent) ProtoMessage() {}

func (x *VmStateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pilab_director_v1_clouddirector_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmStateEvent.ProtoReflect.Descriptor instead.
func (*VmStateEvent) Descriptor() ([]byte, []int) {
	return file_pilab_director_v1_clouddirector_proto_rawDescGZIP(), []int{4}
}

func (x *VmStateEvent) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *VmStateEvent) GetVmName() string {
	if x != nil {
		return x.VmName
	}
	return ""
}

func (x *VmStateEvent) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *VmStateEvent) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type DiskStateEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Event         string                 `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskStateEvent) Reset() {
	*x = DiskStateEvent{}
	mi := &file_pilab_director_v1_clouddirector_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskStateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskStateEvent) ProtoMessage() {}

func (x *DiskStateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pilab_director_v1_clouddirector_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskStateEvent.ProtoReflect.Descriptor instead.
func (*DiskStateEvent) Descriptor() ([]byte, []int) {
	return file_pilab_director_v1_clouddirector_proto_rawDescGZIP(), []int{5}
}

func (x *DiskStateEvent) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DiskStateEvent) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

type ManagerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*ManagerMessage_ResourceRefreshRequest
	//	*ManagerMessage_ClusterJoin
	//	*ManagerMessage_ClusterLeave
	Message       isManagerMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManagerMessage) Reset() {
	*x = ManagerMessage{}
	mi := &file_pilab_director_v1_clouddirector_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagerMessage) ProtoMessage() {}

func (x *ManagerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pilab_director_v1_clouddirector_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagerMessage.ProtoReflect.Descriptor instead.
func (*ManagerMessage) Descriptor() ([]byte, []int) {
	return file_pilab_director_v1_clouddirector_proto_rawDescGZIP(), []int{6}
}

func (x *ManagerMessage) GetMessage() isManagerMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ManagerMessage) GetResourceRefreshRequest() *ResourceRefreshRequest {
	if x != nil {
		if x, ok := x.Message.(*ManagerMessage_ResourceRefreshRequest); ok {
			return x.ResourceRefreshRequest
		}
	}
	return nil
}

func (x *ManagerMessage) GetClusterJoin() *ClusterJoinRequest {
	if x != nil {
		if x, ok := x.Message.(*ManagerMessage_ClusterJoin); ok {
			return x.ClusterJoin
		}
	}
	return nil
}

func (x *ManagerMessage) GetClusterLeave() *ClusterLeaveRequest {
	if x != nil {
		if x, ok := x.Message.(*ManagerMessage_ClusterLeave); ok {
			return x.ClusterLeave
		}
	}
	return nil
}

type isManagerMessage_Message interface {
	isManagerMessage_Message()
}

type ManagerMessage_ResourceRefreshRequest struct {
	ResourceRefreshRequest *ResourceRefreshRequest `protobuf:"bytes,2,opt,name=resource_refresh_request,json=resourceRefreshRequest,proto3,oneof"`
}

type ManagerMessage_ClusterJoin struct {
	ClusterJoin *ClusterJoinRequest `protobuf:"bytes,3,opt,name=cluster_join,json=clusterJoin,proto3,oneof"`
}

type ManagerMessage_ClusterLeave struct {
	ClusterLeave *ClusterLeaveRequest `protobuf:"bytes,4,opt,name=cluster_leave,json=clusterLeave,proto3,oneof"`
}

func (*ManagerMessage_ResourceRefreshRequest) isManagerMessage_Message() {}

func (*ManagerMessage_ClusterJoin) isManagerMessage_Message() {}

func (*ManagerMessage_ClusterLeave) isManagerMessage_Message() {}

type ResourceRefreshRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceRefreshRequest) Reset() {
	*x = ResourceRefreshRequest{}
	mi := &file_pilab_director_v1_clouddirector_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceRefreshRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceRefreshRequest) ProtoMessage() {}

func (x *ResourceRefreshRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pilab_director_v1_clouddirector_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceRefreshRequest.ProtoReflect.Descriptor instead.
func (*ResourceRefreshRequest) Descriptor() ([]byte, []int) {
	return file_pilab_director_v1_clouddirector_proto_rawDescGZIP(), []int{7}
}

type ClusterJoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Bridges       []*ClusterBridgeConfig `protobuf:"bytes,2,rep,name=bridges,proto3" json:"bridges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterJoinRequest) Reset() {
	*x = ClusterJoinRequest{}
	mi := &file_pilab_director_v1_clouddirector_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterJoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterJoinRequest) ProtoMessage() {}

func (x *ClusterJoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pilab_director_v1_clouddirector_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterJoinRequest.ProtoReflect.Descriptor instead.
func (*ClusterJoinRequest) Descriptor() ([]byte, []int) {
	return file_pilab_director_v1_clouddirector_proto_rawDescGZIP(), []int{8}
}

func (x *ClusterJoinRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *ClusterJoinRequest) GetBridges() []*ClusterBridgeConfig {
	if x != nil {
		return x.Bridges
	}
	return nil
}

type ClusterBridgeConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	NetworkType   string                 `protobuf:"bytes,2,opt,name=network_type,json=networkType,proto3" json:"network_type,omitempty"`
	Vlan          uint32                 `protobuf:"varint,3,opt,name=vlan,proto3" json:"vlan,omitempty"`
	Mtu           uint32                 `protobuf:"varint,4,opt,name=mtu,proto3" json:"mtu,omitempty"`
	Uplinks       []string               `protobuf:"bytes,5,rep,name=uplinks,proto3" json:"uplinks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterBridgeConfig) Reset() {
	*x = ClusterBridgeConfig{}
	mi := &file_pilab_director_v1_clouddirector_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterBridgeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterBridgeConfig) ProtoMessage() {}

func (x *ClusterBridgeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pilab_director_v1_clouddirector_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterBridgeConfig.ProtoReflect.Descriptor instead.
func (*ClusterBridgeConfig) Descriptor() ([]byte, []int) {
	return file_pilab_director_v1_clouddirector_proto_rawDescGZIP(), []int{9}
}

func (x *ClusterBridgeConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClusterBridgeConfig) GetNetworkType() string {
	if x != nil {
		return x.NetworkType
	}
	return ""
}

func (x *ClusterBridgeConfig) GetVlan() uint32 {
	if x != nil {
		return x.Vlan
	}
	return 0
}

func (x *ClusterBridgeConfig) GetMtu() uint32 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

func (x *ClusterBridgeConfig) GetUplinks() []string {
	if x != nil {
		return x.Uplinks
	}
	return nil
}

type ClusterLeaveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterLeaveRequest) Reset() {
	*x = ClusterLeaveRequest{}
	mi := &file_pilab_director_v1_clouddirector_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterLeaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterLeaveRequest) ProtoMessage() {}

func (x *ClusterLeaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pilab_director_v1_clouddirector_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterLeaveRequest.ProtoReflect.Descriptor instead.
func (*ClusterLeaveRequest) Descriptor() ([]byte, []int) {
	return file_pilab_director_v1_clouddirector_proto_rawDescGZIP(), []int{10}
}

func (x *ClusterLeaveRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *ClusterLeaveRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type RegisterAgentRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Hostname             string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	AgentVersion         string                 `protobuf:"bytes,2,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	CoresCount           uint32                 `protobuf:"varint,3,opt,name=cores_count,json=coresCount,proto3" json:"cores_count,omitempty"`
	Platform             string                 `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"`
	PlatformFamily       string                 `protobuf:"bytes,5,opt,name=platform_family,json=platformFamily,proto3" json:"platform_family,omitempty"`
	Uptime               uint32                 `protobuf:"varint,6,opt,name=uptime,proto3" json:"uptime,omitempty"`
	VirtualizationSystem string                 `protobuf:"bytes,7,opt,name=virtualization_system,json=virtualizationSystem,proto3" json:"virtualization_system,omitempty"`
	VirtualizationRole   string                 `protobuf:"bytes,8,opt,name=virtualization_role,json=virtualizationRole,proto3" json:"virtualization_role,omitempty"`
	KernelVersion        string                 `protobuf:"bytes,10,opt,name=kernel_version,json=kernelVersion,proto3" json:"kernel_version,omitempty"`
	KernelArch           string                 `protobuf:"bytes,11,opt,name=kernel_arch,json=kernelArch,proto3" json:"kernel_arch,omitempty"`
	CpuVendorId          string                 `protobuf:"bytes,13,opt,name=cpu_vendor_id,json=cpuVendorId,proto3" json:"cpu_vendor_id,omitempty"`
	CpuFamily            string                 `protobuf:"bytes,14,opt,name=cpu_family,json=cpuFamily,proto3" json:"cpu_family,omitempty"`
	CpuModel             string                 `protobuf:"bytes,15,opt,name=cpu_model,json=cpuModel,proto3" json:"cpu_model,omitempty"`
	CpuModelName         string                 `protobuf:"bytes,16,opt,name=cpu_model_name,json=cpuModelName,proto3" json:"cpu_model_name,omitempty"`
	CpuMhz               uint32                 `protobuf:"varint,17,opt,name=cpu_mhz,json=cpuMhz,proto3" json:"cpu_mhz,omitempty"`
	CpuCacheSize         uint32                 `protobuf:"varint,18,opt,name=cpu_cache_size,json=cpuCacheSize,proto3" json:"cpu_cache_size,omitempty"`
	CpuFlags             []string               `protobuf:"bytes,19,rep,name=cpu_flags,json=cpuFlags,proto3" json:"cpu_flags,omitempty"`
	MemSize              uint64                 `protobuf:"varint,20,opt,name=mem_size,json=memSize,proto3" json:"mem_size,omitempty"`
	HostState            string                 `protobuf:"bytes,9999,opt,name=host_state,json=hostState,proto3" json:"host_state,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RegisterAgentRequest) Reset() {
	*x = RegisterAgentRequest{}
	mi := &file_pilab_director_v1_clouddirector_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgentRequest) ProtoMessage() {}

func (x *RegisterAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pilab_director_v1_clouddirector_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgentRequest.ProtoReflect.Descriptor instead.
func (*RegisterAgentRequest) Descriptor() ([]byte, []int) {
	return file_pilab_director_v1_clouddirector_proto_rawDescGZIP(), []int{11}
}

func (x *RegisterAgentRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterAgentRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *RegisterAgentRequest) GetCoresCount() uint32 {
	if x != nil {
		return x.CoresCount
	}
	return 0
}

func (x *RegisterAgentRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *RegisterAgentRequest) GetPlatformFamily() string {
	if x != nil {
		return x.PlatformFamily
	}
	return ""
}

func (x *RegisterAgentRequest) GetUptime() uint32 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

func (x *RegisterAgentRequest) GetVirtualizationSystem() string {
	if x != nil {
		return x.VirtualizationSystem
	}
	return ""
}

func (x *RegisterAgentRequest) GetVirtualizationRole() string {
	if x != nil {
		return x.VirtualizationRole
	}
	return ""
}

func (x *RegisterAgentRequest) GetKernelVersion() string {
	if x != nil {
		return x.KernelVersion
	}
	return ""
}

func (x *RegisterAgentRequest) GetKernelArch() string {
	if x != nil {
		return x.KernelArch
	}
	return ""
}

func (x *RegisterAgentRequest) GetCpuVendorId() string {
	if x != nil {
		return x.CpuVendorId
	}
	return ""
}

func (x *RegisterAgentRequest) GetCpuFamily() string {
	if x != nil {
		return x.CpuFamily
	}
	return ""
}

func (x *RegisterAgentRequest) GetCpuModel() string {
	if x != nil {
		return x.CpuModel
	}
	return ""
}

func (x *RegisterAgentRequest) GetCpuModelName() string {
	if x != nil {
		return x.CpuModelName
	}
	return ""
}

func (x *RegisterAgentRequest) GetCpuMhz() uint32 {
	if x != nil {
		return x.CpuMhz
	}
	return 0
}

func (x *RegisterAgentRequest) GetCpuCacheSize() uint32 {
	if x != nil {
		return x.CpuCacheSize
	}
	return 0
}

func (x *RegisterAgentRequest) GetCpuFlags() []string {
	if x != nil {
		return x.CpuFlags
	}
	return nil
}

func (x *RegisterAgentRequest) GetMemSize() uint64 {
	if x != nil {
		return x.MemSize
	}
	return 0
}

func (x *RegisterAgentRequest) GetHostState() string {
	if x != nil {
		return x.HostState
	}
	return ""
}

type RegisterAgentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*RegisterAgentResponse_DirectorWelcome
	//	*RegisterAgentResponse_ErrorReason
	Response      isRegisterAgentResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAgentResponse) Reset() {
	*x = RegisterAgentResponse{}
	mi := &file_pilab_director_v1_clouddirector_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgentResponse) ProtoMessage() {}

func (x *RegisterAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pilab_director_v1_clouddirector_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgentResponse.ProtoReflect.Descriptor instead.
func (*RegisterAgentResponse) Descriptor() ([]byte, []int) {
	return file_pilab_director_v1_clouddirector_proto_rawDescGZIP(), []int{12}
}

func (x *RegisterAgentResponse) GetResponse() isRegisterAgentResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *RegisterAgentResponse) GetDirectorWelcome() string {
	if x != nil {
		if x, ok := x.Response.(*RegisterAgentResponse_DirectorWelcome); ok {
			return x.DirectorWelcome
		}
	}
	return ""
}

func (x *RegisterAgentResponse) GetErrorReason() string {
	if x != nil {
		if x, ok := x.Response.(*RegisterAgentResponse_ErrorReason); ok {
			return x.ErrorReason
		}
	}
	return ""
}

type isRegisterAgentResponse_Response interface {
	isRegisterAgentResponse_Response()
}

type RegisterAgentResponse_DirectorWelcome struct {
	DirectorWelcome string `protobuf:"bytes,1,opt,name=director_welcome,json=directorWelcome,proto3,oneof"`
}

type RegisterAgentResponse_ErrorReason struct {
	ErrorReason string `protobuf:"bytes,2,opt,name=error_reason,json=errorReason,proto3,oneof"`
}

func (*RegisterAgentResponse_DirectorWelcome) isRegisterAgentResponse_Response() {}

func (*RegisterAgentResponse_ErrorReason) isRegisterAgentResponse_Response() {}

var File_pilab_director_v1_clouddirector_proto protoreflect.FileDescriptor

const file_pilab_director_v1_clouddirector_proto_rawDesc = "" +
	"\n" +
	"%pilab/director/v1/clouddirector.proto\x12\x11pilab.director.v1\x1a\x1apilab/common/v1/host.proto\x1a\x1apilab/common/v1/task.proto\"6\n" +
	"\vVmGuestInfo\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12\x12\n" +
	"\x04info\x18\x02 \x01(\tR\x04info\"\xee\x03\n" +
	"\x12AgentEventsRequest\x12G\n" +
	"\x0evm_state_event\x18\x01 \x01(\v2\x1f.pilab.director.v1.VmStateEventH\x00R\fvmStateEvent\x12A\n" +
	"\theartbeat\x18\x02 \x01(\v2!.pilab.director.v1.HeartbeatEventH\x00R\theartbeat\x12F\n" +
	"\rvm_definition\x18\x03 \x01(\v2\x1f.pilab.director.v1.VmDefinitionH\x00R\fvmDefinition\x12;\n" +
	"\n" +
	"host_stats\x18\x04 \x01(\v2\x1a.pilab.common.v1.HostStatsH\x00R\thostStats\x12;\n" +
	"\n" +
	"vm_metrics\x18\x05 \x01(\v2\x1a.pilab.common.v1.VmMetricsH\x00R\tvmMetrics\x12;\n" +
	"\n" +
	"job_status\x18\x06 \x01(\v2\x1a.pilab.common.v1.JobStatusH\x00R\tjobStatus\x12D\n" +
	"\rvm_guest_info\x18\a \x01(\v2\x1e.pilab.director.v1.VmGuestInfoH\x00R\vvmGuestInfoB\a\n" +
	"\x05event\"L\n" +
	"\x0eHeartbeatEvent\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12!\n" +
	"\felapsed_time\x18\x02 \x01(\rR\velapsedTime\"x\n" +
	"\fVmDefinition\x12\x1d\n" +
	"\n" +
	"domain_xml\x18\x01 \x01(\tR\tdomainXml\x12\x1f\n" +
	"\vdomain_uuid\x18\x02 \x01(\tR\n" +
	"domainUuid\x12\x14\n" +
	"\x05state\x18\x03 \x01(\rR\x05state\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\"j\n" +
	"\fVmStateEvent\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12\x17\n" +
	"\avm_name\x18\x02 \x01(\tR\x06vmName\x12\x14\n" +
	"\x05event\x18\x03 \x01(\tR\x05event\x12\x16\n" +
	"\x06detail\x18\x04 \x01(\tR\x06detail\":\n" +
	"\x0eDiskStateEvent\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x14\n" +
	"\x05event\x18\x02 \x01(\tR\x05event\"\x9d\x02\n" +
	"\x0eManagerMessage\x12e\n" +
	"\x18resource_refresh_request\x18\x02 \x01(\v2).pilab.director.v1.ResourceRefreshRequestH\x00R\x16resourceRefreshRequest\x12J\n" +
	"\fcluster_join\x18\x03 \x01(\v2%.pilab.director.v1.ClusterJoinRequestH\x00R\vclusterJoin\x12M\n" +
	"\rcluster_leave\x18\x04 \x01(\v2&.pilab.director.v1.ClusterLeaveRequestH\x00R\fclusterLeaveB\t\n" +
	"\amessage\"\x18\n" +
	"\x16ResourceRefreshRequest\"u\n" +
	"\x12ClusterJoinRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12@\n" +
	"\abridges\x18\x02 \x03(\v2&.pilab.director.v1.ClusterBridgeConfigR\abridges\"\x8c\x01\n" +
	"\x13ClusterBridgeConfig\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fnetwork_type\x18\x02 \x01(\tR\vnetworkType\x12\x12\n" +
	"\x04vlan\x18\x03 \x01(\rR\x04vlan\x12\x10\n" +
	"\x03mtu\x18\x04 \x01(\rR\x03mtu\x12\x18\n" +
	"\auplinks\x18\x05 \x03(\tR\auplinks\"J\n" +
	"\x13ClusterLeaveRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"\xa0\x05\n" +
	"\x14RegisterAgentRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12#\n" +
	"\ragent_version\x18\x02 \x01(\tR\fagentVersion\x12\x1f\n" +
	"\vcores_count\x18\x03 \x01(\rR\n" +
	"coresCount\x12\x1a\n" +
	"\bplatform\x18\x04 \x01(\tR\bplatform\x12'\n" +
	"\x0fplatform_family\x18\x05 \x01(\tR\x0eplatformFamily\x12\x16\n" +
	"\x06uptime\x18\x06 \x01(\rR\x06uptime\x123\n" +
	"\x15virtualization_system\x18\a \x01(\tR\x14virtualizationSystem\x12/\n" +
	"\x13virtualization_role\x18\b \x01(\tR\x12virtualizationRole\x12%\n" +
	"\x0ekernel_version\x18\n" +
	" \x01(\tR\rkernelVersion\x12\x1f\n" +
	"\vkernel_arch\x18\v \x01(\tR\n" +
	"kernelArch\x12\"\n" +
	"\rcpu_vendor_id\x18\r \x01(\tR\vcpuVendorId\x12\x1d\n" +
	"\n" +
	"cpu_family\x18\x0e \x01(\tR\tcpuFamily\x12\x1b\n" +
	"\tcpu_model\x18\x0f \x01(\tR\bcpuModel\x12$\n" +
	"\x0ecpu_model_name\x18\x10 \x01(\tR\fcpuModelName\x12\x17\n" +
	"\acpu_mhz\x18\x11 \x01(\rR\x06cpuMhz\x12$\n" +
	"\x0ecpu_cache_size\x18\x12 \x01(\rR\fcpuCacheSize\x12\x1b\n" +
	"\tcpu_flags\x18\x13 \x03(\tR\bcpuFlags\x12\x19\n" +
	"\bmem_size\x18\x14 \x01(\x04R\amemSize\x12\x1e\n" +
	"\n" +
	"host_state\x18\x8fN \x01(\tR\thostState\"u\n" +
	"\x15RegisterAgentResponse\x12+\n" +
	"\x10director_welcome\x18\x01 \x01(\tH\x00R\x0fdirectorWelcome\x12#\n" +
	"\ferror_reason\x18\x02 \x01(\tH\x00R\verrorReasonB\n" +
	"\n" +
	"\bresponse2\xd7\x01\n" +
	"\x14CloudDirectorService\x12b\n" +
	"\rRegisterAgent\x12'.pilab.director.v1.RegisterAgentRequest\x1a(.pilab.director.v1.RegisterAgentResponse\x12[\n" +
	"\vAgentEvents\x12%.pilab.director.v1.AgentEventsRequest\x1a!.pilab.director.v1.ManagerMessage(\x010\x01B7Z5go.pilab.hu/cloud/virtpb/pilab/director/v1;directorv1b\x06proto3"

var (
	file_pilab_director_v1_clouddirector_proto_rawDescOnce sync.Once
	file_pilab_director_v1_clouddirector_proto_rawDescData []byte
)

func file_pilab_director_v1_clouddirector_proto_rawDescGZIP() []byte {
	file_pilab_director_v1_clouddirector_proto_rawDescOnce.Do(func() {
		file_pilab_director_v1_clouddirector_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pilab_director_v1_clouddirector_proto_rawDesc), len(file_pilab_director_v1_clouddirector_proto_rawDesc)))
	})
	return file_pilab_director_v1_clouddirector_proto_rawDescData
}

var file_pilab_director_v1_clouddirector_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_pilab_director_v1_clouddirector_proto_goTypes = []any{
	(*VmGuestInfo)(nil),            // 0: pilab.director.v1.VmGuestInfo
	(*AgentEventsRequest)(nil),     // 1: pilab.director.v1.AgentEventsRequest
	(*HeartbeatEvent)(nil),         // 2: pilab.director.v1.HeartbeatEvent
	(*VmDefinition)(nil),           // 3: pilab.director.v1.VmDefinition
	(*VmStateEvent)(nil),           // 4: pilab.director.v1.VmStateEvent
	(*DiskStateEvent)(nil),         // 5: pilab.director.v1.DiskStateEvent
	(*ManagerMessage)(nil),         // 6: pilab.director.v1.ManagerMessage
	(*ResourceRefreshRequest)(nil), // 7: pilab.director.v1.ResourceRefreshRequest
	(*ClusterJoinRequest)(nil),     // 8: pilab.director.v1.ClusterJoinRequest
	(*ClusterBridgeConfig)(nil),    // 9: pilab.director.v1.ClusterBridgeConfig
	(*ClusterLeaveRequest)(nil),    // 10: pilab.director.v1.ClusterLeaveRequest
	(*RegisterAgentRequest)(nil),   // 11: pilab.director.v1.RegisterAgentRequest
	(*RegisterAgentResponse)(nil),  // 12: pilab.director.v1.RegisterAgentResponse
	(*v1.HostStats)(nil),           // 13: pilab.common.v1.HostStats
	(*v1.VmMetrics)(nil),           // 14: pilab.common.v1.VmMetrics
	(*v1.JobStatus)(nil),           // 15: pilab.common.v1.JobStatus
}
var file_pilab_director_v1_clouddirector_proto_depIdxs = []int32{
	4,  // 0: pilab.director.v1.AgentEventsRequest.vm_state_event:type_name -> pilab.director.v1.VmStateEvent
	2,  // 1: pilab.director.v1.AgentEventsRequest.heartbeat:type_name -> pilab.director.v1.HeartbeatEvent
	3,  // 2: pilab.director.v1.AgentEventsRequest.vm_definition:type_name -> pilab.director.v1.VmDefinition
	13, // 3: pilab.director.v1.AgentEventsRequest.host_stats:type_name -> pilab.common.v1.HostStats
	14, // 4: pilab.director.v1.AgentEventsRequest.vm_metrics:type_name -> pilab.common.v1.VmMetrics
	15, // 5: pilab.director.v1.AgentEventsRequest.job_status:type_name -> pilab.common.v1.JobStatus
	0,  // 6: pilab.director.v1.AgentEventsRequest.vm_guest_info:type_name -> pilab.director.v1.VmGuestInfo
	7,  // 7: pilab.director.v1.ManagerMessage.resource_refresh_request:type_name -> pilab.director.v1.ResourceRefreshRequest
	8,  // 8: pilab.director.v1.ManagerMessage.cluster_join:type_name -> pilab.director.v1.ClusterJoinRequest
	10, // 9: pilab.director.v1.ManagerMessage.cluster_leave:type_name -> pilab.director.v1.ClusterLeaveRequest
	9,  // 10: pilab.director.v1.ClusterJoinRequest.bridges:type_name -> pilab.director.v1.ClusterBridgeConfig
	11, // 11: pilab.director.v1.CloudDirectorService.RegisterAgent:input_type -> pilab.director.v1.RegisterAgentRequest
	1,  // 12: pilab.director.v1.CloudDirectorService.AgentEvents:input_type -> pilab.director.v1.AgentEventsRequest
	12, // 13: pilab.director.v1.CloudDirectorService.RegisterAgent:output_type -> pilab.director.v1.RegisterAgentResponse
	6,  // 14: pilab.director.v1.CloudDirectorService.AgentEvents:output_type -> pilab.director.v1.ManagerMessage
	13, // [13:15] is the sub-list for method output_type
	11, // [11:13] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_pilab_director_v1_clouddirector_proto_init() }
func file_pilab_director_v1_clouddirector_proto_init() {
	if File_pilab_director_v1_clouddirector_proto != nil {
		return
	}
	file_pilab_director_v1_clouddirector_proto_msgTypes[1].OneofWrappers = []any{
		(*AgentEventsRequest_VmStateEvent)(nil),
		(*AgentEventsRequest_Heartbeat)(nil),
		(*AgentEventsRequest_VmDefinition)(nil),
		(*AgentEventsRequest_HostStats)(nil),
		(*AgentEventsRequest_VmMetrics)(nil),
		(*AgentEventsRequest_JobStatus)(nil),
		(*AgentEventsRequest_VmGuestInfo)(nil),
	}
	file_pilab_director_v1_clouddirector_proto_msgTypes[6].OneofWrappers = []any{
		(*ManagerMessage_ResourceRefreshRequest)(nil),
		(*ManagerMessage_ClusterJoin)(nil),
		(*ManagerMessage_ClusterLeave)(nil),
	}
	file_pilab_director_v1_clouddirector_proto_msgTypes[12].OneofWrappers = []any{
		(*RegisterAgentResponse_DirectorWelcome)(nil),
		(*RegisterAgentResponse_ErrorReason)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pilab_director_v1_clouddirector_proto_rawDesc), len(file_pilab_director_v1_clouddirector_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pilab_director_v1_clouddirector_proto_goTypes,
		DependencyIndexes: file_pilab_director_v1_clouddirector_proto_depIdxs,
		MessageInfos:      file_pilab_director_v1_clouddirector_proto_msgTypes,
	}.Build()
	File_pilab_director_v1_clouddirector_proto = out.File
	file_pilab_director_v1_clouddirector_proto_goTypes = nil
	file_pilab_director_v1_clouddirector_proto_depIdxs = nil
}
