// Package director provides distributed task orchestration and agent coordination.
// NodeService is the PIVIRT-83 (control-plane consolidation, Phase 2) session
// stream: one bidirectional stream per node, replacing
// director/v1.CloudDirectorService.AgentEvents and (eventually, Phase 5)
// TaskService.Subscribe. A node's identity is a director-minted UUID bound
// to its mTLS client certificate, never a client-supplied claim.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: pilab/director/v2/node_service.proto

package directorv2connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v2 "go.pilab.hu/cloud/virtpb/v3/pilab/director/v2"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// NodeServiceName is the fully-qualified name of the NodeService service.
	NodeServiceName = "pilab.director.v2.NodeService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// NodeServiceRegisterProcedure is the fully-qualified name of the NodeService's Register RPC.
	NodeServiceRegisterProcedure = "/pilab.director.v2.NodeService/Register"
	// NodeServiceRequestCertificateProcedure is the fully-qualified name of the NodeService's
	// RequestCertificate RPC.
	NodeServiceRequestCertificateProcedure = "/pilab.director.v2.NodeService/RequestCertificate"
	// NodeServiceSessionProcedure is the fully-qualified name of the NodeService's Session RPC.
	NodeServiceSessionProcedure = "/pilab.director.v2.NodeService/Session"
)

// NodeServiceClient is a client for the pilab.director.v2.NodeService service.
type NodeServiceClient interface {
	// Register establishes (first join) or re-establishes (reconnect) a
	// node's identity with the director. On first join, called without an
	// mTLS client certificate yet -- authenticated instead by
	// bootstrap_token -- and the director mints a new node_uuid. On
	// reconnect, the caller's mTLS peer identity must already be bound to
	// the supplied node_uuid.
	Register(context.Context, *connect.Request[v2.RegisterNodeRequest]) (*connect.Response[v2.RegisterNodeResponse], error)
	// RequestCertificate submits a CSR for the node_uuid minted by Register
	// and returns a signed mTLS client certificate whose SAN the director
	// asserts itself (spiffe://pilab.hu/node/<node_uuid>), regardless of
	// what the CSR itself claims. Like Register, usable without an existing
	// client certificate via bootstrap_token; a node_uuid may only be
	// certified once (rejects if already bound to a peer identity).
	RequestCertificate(context.Context, *connect.Request[v2.RequestCertificateRequest]) (*connect.Response[v2.RequestCertificateResponse], error)
	// Session is the node's single long-lived stream to the director. It
	// requires a verified mTLS client certificate -- there is no
	// bootstrap-token path here. The first NodeEvent on the stream must
	// carry the node's current node_uuid and lease_epoch; events from a
	// stale epoch (an older Register than the one currently on record) are
	// dropped, which is what makes a duplicate or restarted agent process
	// safe.
	Session(context.Context) *connect.BidiStreamForClient[v2.NodeEvent, v2.NodeDirective]
}

// NewNodeServiceClient constructs a client for the pilab.director.v2.NodeService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewNodeServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) NodeServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	nodeServiceMethods := v2.File_pilab_director_v2_node_service_proto.Services().ByName("NodeService").Methods()
	return &nodeServiceClient{
		register: connect.NewClient[v2.RegisterNodeRequest, v2.RegisterNodeResponse](
			httpClient,
			baseURL+NodeServiceRegisterProcedure,
			connect.WithSchema(nodeServiceMethods.ByName("Register")),
			connect.WithClientOptions(opts...),
		),
		requestCertificate: connect.NewClient[v2.RequestCertificateRequest, v2.RequestCertificateResponse](
			httpClient,
			baseURL+NodeServiceRequestCertificateProcedure,
			connect.WithSchema(nodeServiceMethods.ByName("RequestCertificate")),
			connect.WithClientOptions(opts...),
		),
		session: connect.NewClient[v2.NodeEvent, v2.NodeDirective](
			httpClient,
			baseURL+NodeServiceSessionProcedure,
			connect.WithSchema(nodeServiceMethods.ByName("Session")),
			connect.WithClientOptions(opts...),
		),
	}
}

// nodeServiceClient implements NodeServiceClient.
type nodeServiceClient struct {
	register           *connect.Client[v2.RegisterNodeRequest, v2.RegisterNodeResponse]
	requestCertificate *connect.Client[v2.RequestCertificateRequest, v2.RequestCertificateResponse]
	session            *connect.Client[v2.NodeEvent, v2.NodeDirective]
}

// Register calls pilab.director.v2.NodeService.Register.
func (c *nodeServiceClient) Register(ctx context.Context, req *connect.Request[v2.RegisterNodeRequest]) (*connect.Response[v2.RegisterNodeResponse], error) {
	return c.register.CallUnary(ctx, req)
}

// RequestCertificate calls pilab.director.v2.NodeService.RequestCertificate.
func (c *nodeServiceClient) RequestCertificate(ctx context.Context, req *connect.Request[v2.RequestCertificateRequest]) (*connect.Response[v2.RequestCertificateResponse], error) {
	return c.requestCertificate.CallUnary(ctx, req)
}

// Session calls pilab.director.v2.NodeService.Session.
func (c *nodeServiceClient) Session(ctx context.Context) *connect.BidiStreamForClient[v2.NodeEvent, v2.NodeDirective] {
	return c.session.CallBidiStream(ctx)
}

// NodeServiceHandler is an implementation of the pilab.director.v2.NodeService service.
type NodeServiceHandler interface {
	// Register establishes (first join) or re-establishes (reconnect) a
	// node's identity with the director. On first join, called without an
	// mTLS client certificate yet -- authenticated instead by
	// bootstrap_token -- and the director mints a new node_uuid. On
	// reconnect, the caller's mTLS peer identity must already be bound to
	// the supplied node_uuid.
	Register(context.Context, *connect.Request[v2.RegisterNodeRequest]) (*connect.Response[v2.RegisterNodeResponse], error)
	// RequestCertificate submits a CSR for the node_uuid minted by Register
	// and returns a signed mTLS client certificate whose SAN the director
	// asserts itself (spiffe://pilab.hu/node/<node_uuid>), regardless of
	// what the CSR itself claims. Like Register, usable without an existing
	// client certificate via bootstrap_token; a node_uuid may only be
	// certified once (rejects if already bound to a peer identity).
	RequestCertificate(context.Context, *connect.Request[v2.RequestCertificateRequest]) (*connect.Response[v2.RequestCertificateResponse], error)
	// Session is the node's single long-lived stream to the director. It
	// requires a verified mTLS client certificate -- there is no
	// bootstrap-token path here. The first NodeEvent on the stream must
	// carry the node's current node_uuid and lease_epoch; events from a
	// stale epoch (an older Register than the one currently on record) are
	// dropped, which is what makes a duplicate or restarted agent process
	// safe.
	Session(context.Context, *connect.BidiStream[v2.NodeEvent, v2.NodeDirective]) error
}

// NewNodeServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewNodeServiceHandler(svc NodeServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	nodeServiceMethods := v2.File_pilab_director_v2_node_service_proto.Services().ByName("NodeService").Methods()
	nodeServiceRegisterHandler := connect.NewUnaryHandler(
		NodeServiceRegisterProcedure,
		svc.Register,
		connect.WithSchema(nodeServiceMethods.ByName("Register")),
		connect.WithHandlerOptions(opts...),
	)
	nodeServiceRequestCertificateHandler := connect.NewUnaryHandler(
		NodeServiceRequestCertificateProcedure,
		svc.RequestCertificate,
		connect.WithSchema(nodeServiceMethods.ByName("RequestCertificate")),
		connect.WithHandlerOptions(opts...),
	)
	nodeServiceSessionHandler := connect.NewBidiStreamHandler(
		NodeServiceSessionProcedure,
		svc.Session,
		connect.WithSchema(nodeServiceMethods.ByName("Session")),
		connect.WithHandlerOptions(opts...),
	)
	return "/pilab.director.v2.NodeService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case NodeServiceRegisterProcedure:
			nodeServiceRegisterHandler.ServeHTTP(w, r)
		case NodeServiceRequestCertificateProcedure:
			nodeServiceRequestCertificateHandler.ServeHTTP(w, r)
		case NodeServiceSessionProcedure:
			nodeServiceSessionHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedNodeServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedNodeServiceHandler struct{}

func (UnimplementedNodeServiceHandler) Register(context.Context, *connect.Request[v2.RegisterNodeRequest]) (*connect.Response[v2.RegisterNodeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pilab.director.v2.NodeService.Register is not implemented"))
}

func (UnimplementedNodeServiceHandler) RequestCertificate(context.Context, *connect.Request[v2.RequestCertificateRequest]) (*connect.Response[v2.RequestCertificateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pilab.director.v2.NodeService.RequestCertificate is not implemented"))
}

func (UnimplementedNodeServiceHandler) Session(context.Context, *connect.BidiStream[v2.NodeEvent, v2.NodeDirective]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("pilab.director.v2.NodeService.Session is not implemented"))
}
