// =============================================================================
// Task Service - Distributed Task Queue Management
// =============================================================================
// Purpose: Manages the ordered task queue for agent nodes. This is the central
// orchestration service that distributes work (VM operations) to agent nodes.
//
// Communication:
// - gRPC streaming for task subscription (agent receives tasks in real-time)
// - Unary RPC for task CRUD operations (frontend/director creates/manages tasks)
//
// Key Concepts:
// - Task types: VM lifecycle (create, start, stop, delete) and advanced operations
//   (migrate, snapshot, clone, export/import OVA)
// - Task status: PENDING -> IN_PROGRESS -> COMPLETED/FAILED/CANCELLED
// - Sequence numbers ensure ordered processing
// - Priority allows important tasks to be processed first
// - Superseded tasks: newer operations can invalidate older pending ones
// =============================================================================

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: pilab/director/v2/task_service.proto

package directorv2connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v2 "go.pilab.hu/cloud/virtpb/pilab/director/v2"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TaskServiceName is the fully-qualified name of the TaskService service.
	TaskServiceName = "pilab.cloud.director.v2.TaskService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TaskServiceSubscribeProcedure is the fully-qualified name of the TaskService's Subscribe RPC.
	TaskServiceSubscribeProcedure = "/pilab.cloud.director.v2.TaskService/Subscribe"
	// TaskServiceCreateTaskProcedure is the fully-qualified name of the TaskService's CreateTask RPC.
	TaskServiceCreateTaskProcedure = "/pilab.cloud.director.v2.TaskService/CreateTask"
	// TaskServiceGetTasksProcedure is the fully-qualified name of the TaskService's GetTasks RPC.
	TaskServiceGetTasksProcedure = "/pilab.cloud.director.v2.TaskService/GetTasks"
	// TaskServiceGetTaskProcedure is the fully-qualified name of the TaskService's GetTask RPC.
	TaskServiceGetTaskProcedure = "/pilab.cloud.director.v2.TaskService/GetTask"
	// TaskServiceUpdateTaskStatusProcedure is the fully-qualified name of the TaskService's
	// UpdateTaskStatus RPC.
	TaskServiceUpdateTaskStatusProcedure = "/pilab.cloud.director.v2.TaskService/UpdateTaskStatus"
	// TaskServiceCancelTaskProcedure is the fully-qualified name of the TaskService's CancelTask RPC.
	TaskServiceCancelTaskProcedure = "/pilab.cloud.director.v2.TaskService/CancelTask"
	// TaskServiceGetTaskHistoryProcedure is the fully-qualified name of the TaskService's
	// GetTaskHistory RPC.
	TaskServiceGetTaskHistoryProcedure = "/pilab.cloud.director.v2.TaskService/GetTaskHistory"
	// TaskServiceBatchUpdateTasksProcedure is the fully-qualified name of the TaskService's
	// BatchUpdateTasks RPC.
	TaskServiceBatchUpdateTasksProcedure = "/pilab.cloud.director.v2.TaskService/BatchUpdateTasks"
)

// TaskServiceClient is a client for the pilab.cloud.director.v2.TaskService service.
type TaskServiceClient interface {
	// Agent subscribes for tasks (gRPC streaming)
	Subscribe(context.Context, *connect.Request[v2.SubscribeRequest]) (*connect.ServerStreamForClient[v2.Task], error)
	// Create a new task
	CreateTask(context.Context, *connect.Request[v2.CreateTaskRequest]) (*connect.Response[v2.CreateTaskResponse], error)
	// Get pending tasks for a specific node
	GetTasks(context.Context, *connect.Request[v2.GetTasksRequest]) (*connect.Response[v2.GetTasksResponse], error)
	// Get a single task by ID
	GetTask(context.Context, *connect.Request[v2.GetTaskRequest]) (*connect.Response[v2.GetTaskResponse], error)
	// Update task status (called by agents)
	UpdateTaskStatus(context.Context, *connect.Request[v2.UpdateTaskStatusRequest]) (*connect.Response[v2.UpdateTaskStatusResponse], error)
	// Cancel a pending task
	CancelTask(context.Context, *connect.Request[v2.CancelTaskRequest]) (*connect.Response[v2.CancelTaskResponse], error)
	// Get task history for a specific VM
	GetTaskHistory(context.Context, *connect.Request[v2.GetTaskHistoryRequest]) (*connect.Response[v2.GetTaskHistoryResponse], error)
	// Batch update task statuses (more efficient for agents)
	BatchUpdateTasks(context.Context, *connect.Request[v2.BatchUpdateTasksRequest]) (*connect.Response[v2.BatchUpdateTasksResponse], error)
}

// NewTaskServiceClient constructs a client for the pilab.cloud.director.v2.TaskService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTaskServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TaskServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	taskServiceMethods := v2.File_pilab_director_v2_task_service_proto.Services().ByName("TaskService").Methods()
	return &taskServiceClient{
		subscribe: connect.NewClient[v2.SubscribeRequest, v2.Task](
			httpClient,
			baseURL+TaskServiceSubscribeProcedure,
			connect.WithSchema(taskServiceMethods.ByName("Subscribe")),
			connect.WithClientOptions(opts...),
		),
		createTask: connect.NewClient[v2.CreateTaskRequest, v2.CreateTaskResponse](
			httpClient,
			baseURL+TaskServiceCreateTaskProcedure,
			connect.WithSchema(taskServiceMethods.ByName("CreateTask")),
			connect.WithClientOptions(opts...),
		),
		getTasks: connect.NewClient[v2.GetTasksRequest, v2.GetTasksResponse](
			httpClient,
			baseURL+TaskServiceGetTasksProcedure,
			connect.WithSchema(taskServiceMethods.ByName("GetTasks")),
			connect.WithClientOptions(opts...),
		),
		getTask: connect.NewClient[v2.GetTaskRequest, v2.GetTaskResponse](
			httpClient,
			baseURL+TaskServiceGetTaskProcedure,
			connect.WithSchema(taskServiceMethods.ByName("GetTask")),
			connect.WithClientOptions(opts...),
		),
		updateTaskStatus: connect.NewClient[v2.UpdateTaskStatusRequest, v2.UpdateTaskStatusResponse](
			httpClient,
			baseURL+TaskServiceUpdateTaskStatusProcedure,
			connect.WithSchema(taskServiceMethods.ByName("UpdateTaskStatus")),
			connect.WithClientOptions(opts...),
		),
		cancelTask: connect.NewClient[v2.CancelTaskRequest, v2.CancelTaskResponse](
			httpClient,
			baseURL+TaskServiceCancelTaskProcedure,
			connect.WithSchema(taskServiceMethods.ByName("CancelTask")),
			connect.WithClientOptions(opts...),
		),
		getTaskHistory: connect.NewClient[v2.GetTaskHistoryRequest, v2.GetTaskHistoryResponse](
			httpClient,
			baseURL+TaskServiceGetTaskHistoryProcedure,
			connect.WithSchema(taskServiceMethods.ByName("GetTaskHistory")),
			connect.WithClientOptions(opts...),
		),
		batchUpdateTasks: connect.NewClient[v2.BatchUpdateTasksRequest, v2.BatchUpdateTasksResponse](
			httpClient,
			baseURL+TaskServiceBatchUpdateTasksProcedure,
			connect.WithSchema(taskServiceMethods.ByName("BatchUpdateTasks")),
			connect.WithClientOptions(opts...),
		),
	}
}

// taskServiceClient implements TaskServiceClient.
type taskServiceClient struct {
	subscribe        *connect.Client[v2.SubscribeRequest, v2.Task]
	createTask       *connect.Client[v2.CreateTaskRequest, v2.CreateTaskResponse]
	getTasks         *connect.Client[v2.GetTasksRequest, v2.GetTasksResponse]
	getTask          *connect.Client[v2.GetTaskRequest, v2.GetTaskResponse]
	updateTaskStatus *connect.Client[v2.UpdateTaskStatusRequest, v2.UpdateTaskStatusResponse]
	cancelTask       *connect.Client[v2.CancelTaskRequest, v2.CancelTaskResponse]
	getTaskHistory   *connect.Client[v2.GetTaskHistoryRequest, v2.GetTaskHistoryResponse]
	batchUpdateTasks *connect.Client[v2.BatchUpdateTasksRequest, v2.BatchUpdateTasksResponse]
}

// Subscribe calls pilab.cloud.director.v2.TaskService.Subscribe.
func (c *taskServiceClient) Subscribe(ctx context.Context, req *connect.Request[v2.SubscribeRequest]) (*connect.ServerStreamForClient[v2.Task], error) {
	return c.subscribe.CallServerStream(ctx, req)
}

// CreateTask calls pilab.cloud.director.v2.TaskService.CreateTask.
func (c *taskServiceClient) CreateTask(ctx context.Context, req *connect.Request[v2.CreateTaskRequest]) (*connect.Response[v2.CreateTaskResponse], error) {
	return c.createTask.CallUnary(ctx, req)
}

// GetTasks calls pilab.cloud.director.v2.TaskService.GetTasks.
func (c *taskServiceClient) GetTasks(ctx context.Context, req *connect.Request[v2.GetTasksRequest]) (*connect.Response[v2.GetTasksResponse], error) {
	return c.getTasks.CallUnary(ctx, req)
}

// GetTask calls pilab.cloud.director.v2.TaskService.GetTask.
func (c *taskServiceClient) GetTask(ctx context.Context, req *connect.Request[v2.GetTaskRequest]) (*connect.Response[v2.GetTaskResponse], error) {
	return c.getTask.CallUnary(ctx, req)
}

// UpdateTaskStatus calls pilab.cloud.director.v2.TaskService.UpdateTaskStatus.
func (c *taskServiceClient) UpdateTaskStatus(ctx context.Context, req *connect.Request[v2.UpdateTaskStatusRequest]) (*connect.Response[v2.UpdateTaskStatusResponse], error) {
	return c.updateTaskStatus.CallUnary(ctx, req)
}

// CancelTask calls pilab.cloud.director.v2.TaskService.CancelTask.
func (c *taskServiceClient) CancelTask(ctx context.Context, req *connect.Request[v2.CancelTaskRequest]) (*connect.Response[v2.CancelTaskResponse], error) {
	return c.cancelTask.CallUnary(ctx, req)
}

// GetTaskHistory calls pilab.cloud.director.v2.TaskService.GetTaskHistory.
func (c *taskServiceClient) GetTaskHistory(ctx context.Context, req *connect.Request[v2.GetTaskHistoryRequest]) (*connect.Response[v2.GetTaskHistoryResponse], error) {
	return c.getTaskHistory.CallUnary(ctx, req)
}

// BatchUpdateTasks calls pilab.cloud.director.v2.TaskService.BatchUpdateTasks.
func (c *taskServiceClient) BatchUpdateTasks(ctx context.Context, req *connect.Request[v2.BatchUpdateTasksRequest]) (*connect.Response[v2.BatchUpdateTasksResponse], error) {
	return c.batchUpdateTasks.CallUnary(ctx, req)
}

// TaskServiceHandler is an implementation of the pilab.cloud.director.v2.TaskService service.
type TaskServiceHandler interface {
	// Agent subscribes for tasks (gRPC streaming)
	Subscribe(context.Context, *connect.Request[v2.SubscribeRequest], *connect.ServerStream[v2.Task]) error
	// Create a new task
	CreateTask(context.Context, *connect.Request[v2.CreateTaskRequest]) (*connect.Response[v2.CreateTaskResponse], error)
	// Get pending tasks for a specific node
	GetTasks(context.Context, *connect.Request[v2.GetTasksRequest]) (*connect.Response[v2.GetTasksResponse], error)
	// Get a single task by ID
	GetTask(context.Context, *connect.Request[v2.GetTaskRequest]) (*connect.Response[v2.GetTaskResponse], error)
	// Update task status (called by agents)
	UpdateTaskStatus(context.Context, *connect.Request[v2.UpdateTaskStatusRequest]) (*connect.Response[v2.UpdateTaskStatusResponse], error)
	// Cancel a pending task
	CancelTask(context.Context, *connect.Request[v2.CancelTaskRequest]) (*connect.Response[v2.CancelTaskResponse], error)
	// Get task history for a specific VM
	GetTaskHistory(context.Context, *connect.Request[v2.GetTaskHistoryRequest]) (*connect.Response[v2.GetTaskHistoryResponse], error)
	// Batch update task statuses (more efficient for agents)
	BatchUpdateTasks(context.Context, *connect.Request[v2.BatchUpdateTasksRequest]) (*connect.Response[v2.BatchUpdateTasksResponse], error)
}

// NewTaskServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTaskServiceHandler(svc TaskServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	taskServiceMethods := v2.File_pilab_director_v2_task_service_proto.Services().ByName("TaskService").Methods()
	taskServiceSubscribeHandler := connect.NewServerStreamHandler(
		TaskServiceSubscribeProcedure,
		svc.Subscribe,
		connect.WithSchema(taskServiceMethods.ByName("Subscribe")),
		connect.WithHandlerOptions(opts...),
	)
	taskServiceCreateTaskHandler := connect.NewUnaryHandler(
		TaskServiceCreateTaskProcedure,
		svc.CreateTask,
		connect.WithSchema(taskServiceMethods.ByName("CreateTask")),
		connect.WithHandlerOptions(opts...),
	)
	taskServiceGetTasksHandler := connect.NewUnaryHandler(
		TaskServiceGetTasksProcedure,
		svc.GetTasks,
		connect.WithSchema(taskServiceMethods.ByName("GetTasks")),
		connect.WithHandlerOptions(opts...),
	)
	taskServiceGetTaskHandler := connect.NewUnaryHandler(
		TaskServiceGetTaskProcedure,
		svc.GetTask,
		connect.WithSchema(taskServiceMethods.ByName("GetTask")),
		connect.WithHandlerOptions(opts...),
	)
	taskServiceUpdateTaskStatusHandler := connect.NewUnaryHandler(
		TaskServiceUpdateTaskStatusProcedure,
		svc.UpdateTaskStatus,
		connect.WithSchema(taskServiceMethods.ByName("UpdateTaskStatus")),
		connect.WithHandlerOptions(opts...),
	)
	taskServiceCancelTaskHandler := connect.NewUnaryHandler(
		TaskServiceCancelTaskProcedure,
		svc.CancelTask,
		connect.WithSchema(taskServiceMethods.ByName("CancelTask")),
		connect.WithHandlerOptions(opts...),
	)
	taskServiceGetTaskHistoryHandler := connect.NewUnaryHandler(
		TaskServiceGetTaskHistoryProcedure,
		svc.GetTaskHistory,
		connect.WithSchema(taskServiceMethods.ByName("GetTaskHistory")),
		connect.WithHandlerOptions(opts...),
	)
	taskServiceBatchUpdateTasksHandler := connect.NewUnaryHandler(
		TaskServiceBatchUpdateTasksProcedure,
		svc.BatchUpdateTasks,
		connect.WithSchema(taskServiceMethods.ByName("BatchUpdateTasks")),
		connect.WithHandlerOptions(opts...),
	)
	return "/pilab.cloud.director.v2.TaskService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TaskServiceSubscribeProcedure:
			taskServiceSubscribeHandler.ServeHTTP(w, r)
		case TaskServiceCreateTaskProcedure:
			taskServiceCreateTaskHandler.ServeHTTP(w, r)
		case TaskServiceGetTasksProcedure:
			taskServiceGetTasksHandler.ServeHTTP(w, r)
		case TaskServiceGetTaskProcedure:
			taskServiceGetTaskHandler.ServeHTTP(w, r)
		case TaskServiceUpdateTaskStatusProcedure:
			taskServiceUpdateTaskStatusHandler.ServeHTTP(w, r)
		case TaskServiceCancelTaskProcedure:
			taskServiceCancelTaskHandler.ServeHTTP(w, r)
		case TaskServiceGetTaskHistoryProcedure:
			taskServiceGetTaskHistoryHandler.ServeHTTP(w, r)
		case TaskServiceBatchUpdateTasksProcedure:
			taskServiceBatchUpdateTasksHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTaskServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTaskServiceHandler struct{}

func (UnimplementedTaskServiceHandler) Subscribe(context.Context, *connect.Request[v2.SubscribeRequest], *connect.ServerStream[v2.Task]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("pilab.cloud.director.v2.TaskService.Subscribe is not implemented"))
}

func (UnimplementedTaskServiceHandler) CreateTask(context.Context, *connect.Request[v2.CreateTaskRequest]) (*connect.Response[v2.CreateTaskResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pilab.cloud.director.v2.TaskService.CreateTask is not implemented"))
}

func (UnimplementedTaskServiceHandler) GetTasks(context.Context, *connect.Request[v2.GetTasksRequest]) (*connect.Response[v2.GetTasksResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pilab.cloud.director.v2.TaskService.GetTasks is not implemented"))
}

func (UnimplementedTaskServiceHandler) GetTask(context.Context, *connect.Request[v2.GetTaskRequest]) (*connect.Response[v2.GetTaskResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pilab.cloud.director.v2.TaskService.GetTask is not implemented"))
}

func (UnimplementedTaskServiceHandler) UpdateTaskStatus(context.Context, *connect.Request[v2.UpdateTaskStatusRequest]) (*connect.Response[v2.UpdateTaskStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pilab.cloud.director.v2.TaskService.UpdateTaskStatus is not implemented"))
}

func (UnimplementedTaskServiceHandler) CancelTask(context.Context, *connect.Request[v2.CancelTaskRequest]) (*connect.Response[v2.CancelTaskResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pilab.cloud.director.v2.TaskService.CancelTask is not implemented"))
}

func (UnimplementedTaskServiceHandler) GetTaskHistory(context.Context, *connect.Request[v2.GetTaskHistoryRequest]) (*connect.Response[v2.GetTaskHistoryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pilab.cloud.director.v2.TaskService.GetTaskHistory is not implemented"))
}

func (UnimplementedTaskServiceHandler) BatchUpdateTasks(context.Context, *connect.Request[v2.BatchUpdateTasksRequest]) (*connect.Response[v2.BatchUpdateTasksResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pilab.cloud.director.v2.TaskService.BatchUpdateTasks is not implemented"))
}
