// =============================================================================
// Host Stats - Shared Message for Host Resource Utilization
// =============================================================================
// Purpose: Common message for reporting host-level resource statistics.
// Used in event streaming and agent-director communication.
//
// Fields:
// - cpu_usage: CPU utilization percentage (0.0-100.0)
// - disk_usage: Disk utilization percentage (0.0-100.0)
// - used_memory: Used memory in bytes
// - total_memory: Total memory in bytes
// =============================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pilab/host_stats.proto

package cloudpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HostStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuUsage      float32                `protobuf:"fixed32,2,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	DiskUsage     float32                `protobuf:"fixed32,3,opt,name=disk_usage,json=diskUsage,proto3" json:"disk_usage,omitempty"`
	UsedMemory    uint64                 `protobuf:"varint,4,opt,name=used_memory,json=usedMemory,proto3" json:"used_memory,omitempty"`
	TotalMemory   uint64                 `protobuf:"varint,5,opt,name=total_memory,json=totalMemory,proto3" json:"total_memory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostStats) Reset() {
	*x = HostStats{}
	mi := &file_pilab_host_stats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostStats) ProtoMessage() {}

func (x *HostStats) ProtoReflect() protoreflect.Message {
	mi := &file_pilab_host_stats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostStats.ProtoReflect.Descriptor instead.
func (*HostStats) Descriptor() ([]byte, []int) {
	return file_pilab_host_stats_proto_rawDescGZIP(), []int{0}
}

func (x *HostStats) GetCpuUsage() float32 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *HostStats) GetDiskUsage() float32 {
	if x != nil {
		return x.DiskUsage
	}
	return 0
}

func (x *HostStats) GetUsedMemory() uint64 {
	if x != nil {
		return x.UsedMemory
	}
	return 0
}

func (x *HostStats) GetTotalMemory() uint64 {
	if x != nil {
		return x.TotalMemory
	}
	return 0
}

var File_pilab_host_stats_proto protoreflect.FileDescriptor

const file_pilab_host_stats_proto_rawDesc = "" +
	"\n" +
	"\x16pilab/host_stats.proto\x12\vpilab.cloud\"\x8b\x01\n" +
	"\tHostStats\x12\x1b\n" +
	"\tcpu_usage\x18\x02 \x01(\x02R\bcpuUsage\x12\x1d\n" +
	"\n" +
	"disk_usage\x18\x03 \x01(\x02R\tdiskUsage\x12\x1f\n" +
	"\vused_memory\x18\x04 \x01(\x04R\n" +
	"usedMemory\x12!\n" +
	"\ftotal_memory\x18\x05 \x01(\x04R\vtotalMemoryB(Z&go.pilab.hu/cloud/virtpb/pilab;cloudpbb\x06proto3"

var (
	file_pilab_host_stats_proto_rawDescOnce sync.Once
	file_pilab_host_stats_proto_rawDescData []byte
)

func file_pilab_host_stats_proto_rawDescGZIP() []byte {
	file_pilab_host_stats_proto_rawDescOnce.Do(func() {
		file_pilab_host_stats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pilab_host_stats_proto_rawDesc), len(file_pilab_host_stats_proto_rawDesc)))
	})
	return file_pilab_host_stats_proto_rawDescData
}

var file_pilab_host_stats_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pilab_host_stats_proto_goTypes = []any{
	(*HostStats)(nil), // 0: pilab.cloud.HostStats
}
var file_pilab_host_stats_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pilab_host_stats_proto_init() }
func file_pilab_host_stats_proto_init() {
	if File_pilab_host_stats_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pilab_host_stats_proto_rawDesc), len(file_pilab_host_stats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pilab_host_stats_proto_goTypes,
		DependencyIndexes: file_pilab_host_stats_proto_depIdxs,
		MessageInfos:      file_pilab_host_stats_proto_msgTypes,
	}.Build()
	File_pilab_host_stats_proto = out.File
	file_pilab_host_stats_proto_goTypes = nil
	file_pilab_host_stats_proto_depIdxs = nil
}
