// =============================================================================
// Cluster Bridge Service - Per-Cluster OVS Bridge Configuration
// =============================================================================
// Purpose: Manage OVS bridges per cluster with uplink management.
//
// Services:
// - Cluster Bridge CRUD
// - Uplink management (add/remove)
// =============================================================================

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: pilab/network/v2/cluster_bridge_service.proto

package networkv2

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClusterBridgeService_CreateClusterBridge_FullMethodName = "/pilab.network.v2.ClusterBridgeService/CreateClusterBridge"
	ClusterBridgeService_GetClusterBridge_FullMethodName    = "/pilab.network.v2.ClusterBridgeService/GetClusterBridge"
	ClusterBridgeService_ListClusterBridges_FullMethodName  = "/pilab.network.v2.ClusterBridgeService/ListClusterBridges"
	ClusterBridgeService_UpdateClusterBridge_FullMethodName = "/pilab.network.v2.ClusterBridgeService/UpdateClusterBridge"
	ClusterBridgeService_DeleteClusterBridge_FullMethodName = "/pilab.network.v2.ClusterBridgeService/DeleteClusterBridge"
	ClusterBridgeService_AddUplink_FullMethodName           = "/pilab.network.v2.ClusterBridgeService/AddUplink"
	ClusterBridgeService_RemoveUplink_FullMethodName        = "/pilab.network.v2.ClusterBridgeService/RemoveUplink"
)

// ClusterBridgeServiceClient is the client API for ClusterBridgeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClusterBridgeServiceClient interface {
	CreateClusterBridge(ctx context.Context, in *CreateClusterBridgeRequest, opts ...grpc.CallOption) (*ClusterBridge, error)
	GetClusterBridge(ctx context.Context, in *GetClusterBridgeRequest, opts ...grpc.CallOption) (*ClusterBridge, error)
	ListClusterBridges(ctx context.Context, in *ListClusterBridgesRequest, opts ...grpc.CallOption) (*ListClusterBridgesResponse, error)
	UpdateClusterBridge(ctx context.Context, in *UpdateClusterBridgeRequest, opts ...grpc.CallOption) (*ClusterBridge, error)
	DeleteClusterBridge(ctx context.Context, in *DeleteClusterBridgeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	AddUplink(ctx context.Context, in *AddUplinkRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RemoveUplink(ctx context.Context, in *RemoveUplinkRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type clusterBridgeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClusterBridgeServiceClient(cc grpc.ClientConnInterface) ClusterBridgeServiceClient {
	return &clusterBridgeServiceClient{cc}
}

func (c *clusterBridgeServiceClient) CreateClusterBridge(ctx context.Context, in *CreateClusterBridgeRequest, opts ...grpc.CallOption) (*ClusterBridge, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClusterBridge)
	err := c.cc.Invoke(ctx, ClusterBridgeService_CreateClusterBridge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterBridgeServiceClient) GetClusterBridge(ctx context.Context, in *GetClusterBridgeRequest, opts ...grpc.CallOption) (*ClusterBridge, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClusterBridge)
	err := c.cc.Invoke(ctx, ClusterBridgeService_GetClusterBridge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterBridgeServiceClient) ListClusterBridges(ctx context.Context, in *ListClusterBridgesRequest, opts ...grpc.CallOption) (*ListClusterBridgesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListClusterBridgesResponse)
	err := c.cc.Invoke(ctx, ClusterBridgeService_ListClusterBridges_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterBridgeServiceClient) UpdateClusterBridge(ctx context.Context, in *UpdateClusterBridgeRequest, opts ...grpc.CallOption) (*ClusterBridge, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClusterBridge)
	err := c.cc.Invoke(ctx, ClusterBridgeService_UpdateClusterBridge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterBridgeServiceClient) DeleteClusterBridge(ctx context.Context, in *DeleteClusterBridgeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ClusterBridgeService_DeleteClusterBridge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterBridgeServiceClient) AddUplink(ctx context.Context, in *AddUplinkRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ClusterBridgeService_AddUplink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterBridgeServiceClient) RemoveUplink(ctx context.Context, in *RemoveUplinkRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ClusterBridgeService_RemoveUplink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClusterBridgeServiceServer is the server API for ClusterBridgeService service.
// All implementations must embed UnimplementedClusterBridgeServiceServer
// for forward compatibility.
type ClusterBridgeServiceServer interface {
	CreateClusterBridge(context.Context, *CreateClusterBridgeRequest) (*ClusterBridge, error)
	GetClusterBridge(context.Context, *GetClusterBridgeRequest) (*ClusterBridge, error)
	ListClusterBridges(context.Context, *ListClusterBridgesRequest) (*ListClusterBridgesResponse, error)
	UpdateClusterBridge(context.Context, *UpdateClusterBridgeRequest) (*ClusterBridge, error)
	DeleteClusterBridge(context.Context, *DeleteClusterBridgeRequest) (*emptypb.Empty, error)
	AddUplink(context.Context, *AddUplinkRequest) (*emptypb.Empty, error)
	RemoveUplink(context.Context, *RemoveUplinkRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedClusterBridgeServiceServer()
}

// UnimplementedClusterBridgeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClusterBridgeServiceServer struct{}

func (UnimplementedClusterBridgeServiceServer) CreateClusterBridge(context.Context, *CreateClusterBridgeRequest) (*ClusterBridge, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateClusterBridge not implemented")
}
func (UnimplementedClusterBridgeServiceServer) GetClusterBridge(context.Context, *GetClusterBridgeRequest) (*ClusterBridge, error) {
	return nil, status.Error(codes.Unimplemented, "method GetClusterBridge not implemented")
}
func (UnimplementedClusterBridgeServiceServer) ListClusterBridges(context.Context, *ListClusterBridgesRequest) (*ListClusterBridgesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListClusterBridges not implemented")
}
func (UnimplementedClusterBridgeServiceServer) UpdateClusterBridge(context.Context, *UpdateClusterBridgeRequest) (*ClusterBridge, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateClusterBridge not implemented")
}
func (UnimplementedClusterBridgeServiceServer) DeleteClusterBridge(context.Context, *DeleteClusterBridgeRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteClusterBridge not implemented")
}
func (UnimplementedClusterBridgeServiceServer) AddUplink(context.Context, *AddUplinkRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AddUplink not implemented")
}
func (UnimplementedClusterBridgeServiceServer) RemoveUplink(context.Context, *RemoveUplinkRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveUplink not implemented")
}
func (UnimplementedClusterBridgeServiceServer) mustEmbedUnimplementedClusterBridgeServiceServer() {}
func (UnimplementedClusterBridgeServiceServer) testEmbeddedByValue()                              {}

// UnsafeClusterBridgeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClusterBridgeServiceServer will
// result in compilation errors.
type UnsafeClusterBridgeServiceServer interface {
	mustEmbedUnimplementedClusterBridgeServiceServer()
}

func RegisterClusterBridgeServiceServer(s grpc.ServiceRegistrar, srv ClusterBridgeServiceServer) {
	// If the following call panics, it indicates UnimplementedClusterBridgeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClusterBridgeService_ServiceDesc, srv)
}

func _ClusterBridgeService_CreateClusterBridge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateClusterBridgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterBridgeServiceServer).CreateClusterBridge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClusterBridgeService_CreateClusterBridge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterBridgeServiceServer).CreateClusterBridge(ctx, req.(*CreateClusterBridgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterBridgeService_GetClusterBridge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClusterBridgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterBridgeServiceServer).GetClusterBridge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClusterBridgeService_GetClusterBridge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterBridgeServiceServer).GetClusterBridge(ctx, req.(*GetClusterBridgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterBridgeService_ListClusterBridges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListClusterBridgesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterBridgeServiceServer).ListClusterBridges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClusterBridgeService_ListClusterBridges_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterBridgeServiceServer).ListClusterBridges(ctx, req.(*ListClusterBridgesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterBridgeService_UpdateClusterBridge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateClusterBridgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterBridgeServiceServer).UpdateClusterBridge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClusterBridgeService_UpdateClusterBridge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterBridgeServiceServer).UpdateClusterBridge(ctx, req.(*UpdateClusterBridgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterBridgeService_DeleteClusterBridge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteClusterBridgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterBridgeServiceServer).DeleteClusterBridge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClusterBridgeService_DeleteClusterBridge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterBridgeServiceServer).DeleteClusterBridge(ctx, req.(*DeleteClusterBridgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterBridgeService_AddUplink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUplinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterBridgeServiceServer).AddUplink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClusterBridgeService_AddUplink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterBridgeServiceServer).AddUplink(ctx, req.(*AddUplinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterBridgeService_RemoveUplink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveUplinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterBridgeServiceServer).RemoveUplink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClusterBridgeService_RemoveUplink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterBridgeServiceServer).RemoveUplink(ctx, req.(*RemoveUplinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClusterBridgeService_ServiceDesc is the grpc.ServiceDesc for ClusterBridgeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClusterBridgeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pilab.network.v2.ClusterBridgeService",
	HandlerType: (*ClusterBridgeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateClusterBridge",
			Handler:    _ClusterBridgeService_CreateClusterBridge_Handler,
		},
		{
			MethodName: "GetClusterBridge",
			Handler:    _ClusterBridgeService_GetClusterBridge_Handler,
		},
		{
			MethodName: "ListClusterBridges",
			Handler:    _ClusterBridgeService_ListClusterBridges_Handler,
		},
		{
			MethodName: "UpdateClusterBridge",
			Handler:    _ClusterBridgeService_UpdateClusterBridge_Handler,
		},
		{
			MethodName: "DeleteClusterBridge",
			Handler:    _ClusterBridgeService_DeleteClusterBridge_Handler,
		},
		{
			MethodName: "AddUplink",
			Handler:    _ClusterBridgeService_AddUplink_Handler,
		},
		{
			MethodName: "RemoveUplink",
			Handler:    _ClusterBridgeService_RemoveUplink_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pilab/network/v2/cluster_bridge_service.proto",
}
