// Package network provides virtual networking services including networks,
// ports, VLAN/VXLAN management, IPAM, QoS, security, DVS, and statistics.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pilab/network/v2/cluster_bridge_service.proto

package networkv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	_ "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ClusterBridge represents an OVS bridge configuration for a cluster.
type ClusterBridge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ClusterId     string                 `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Role          NetworkRole            `protobuf:"varint,4,opt,name=role,proto3,enum=pilab.network.v2.NetworkRole" json:"role,omitempty"`
	Vlan          int32                  `protobuf:"varint,5,opt,name=vlan,proto3" json:"vlan,omitempty"`
	Mtu           int32                  `protobuf:"varint,6,opt,name=mtu,proto3" json:"mtu,omitempty"`
	Uplinks       []string               `protobuf:"bytes,7,rep,name=uplinks,proto3" json:"uplinks,omitempty"`
	OvsBridgeName string                 `protobuf:"bytes,8,opt,name=ovs_bridge_name,json=ovsBridgeName,proto3" json:"ovs_bridge_name,omitempty"`
	UplinkBond    bool                   `protobuf:"varint,9,opt,name=uplink_bond,json=uplinkBond,proto3" json:"uplink_bond,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,10,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterBridge) Reset() {
	*x = ClusterBridge{}
	mi := &file_pilab_network_v2_cluster_bridge_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterBridge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterBridge) ProtoMessage() {}

func (x *ClusterBridge) ProtoReflect() protoreflect.Message {
	mi := &file_pilab_network_v2_cluster_bridge_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterBridge.ProtoReflect.Descriptor instead.
func (*ClusterBridge) Descriptor() ([]byte, []int) {
	return file_pilab_network_v2_cluster_bridge_service_proto_rawDescGZIP(), []int{0}
}

func (x *ClusterBridge) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ClusterBridge) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *ClusterBridge) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClusterBridge) GetRole() NetworkRole {
	if x != nil {
		return x.Role
	}
	return NetworkRole_NETWORK_ROLE_UNSPECIFIED
}

func (x *ClusterBridge) GetVlan() int32 {
	if x != nil {
		return x.Vlan
	}
	return 0
}

func (x *ClusterBridge) GetMtu() int32 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

func (x *ClusterBridge) GetUplinks() []string {
	if x != nil {
		return x.Uplinks
	}
	return nil
}

func (x *ClusterBridge) GetOvsBridgeName() string {
	if x != nil {
		return x.OvsBridgeName
	}
	return ""
}

func (x *ClusterBridge) GetUplinkBond() bool {
	if x != nil {
		return x.UplinkBond
	}
	return false
}

func (x *ClusterBridge) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ClusterBridge) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ClusterBridge) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateClusterBridgeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Role          NetworkRole            `protobuf:"varint,3,opt,name=role,proto3,enum=pilab.network.v2.NetworkRole" json:"role,omitempty"`
	Vlan          int32                  `protobuf:"varint,4,opt,name=vlan,proto3" json:"vlan,omitempty"`
	Mtu           int32                  `protobuf:"varint,5,opt,name=mtu,proto3" json:"mtu,omitempty"`
	Uplinks       []string               `protobuf:"bytes,6,rep,name=uplinks,proto3" json:"uplinks,omitempty"`
	UplinkBond    bool                   `protobuf:"varint,7,opt,name=uplink_bond,json=uplinkBond,proto3" json:"uplink_bond,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateClusterBridgeRequest) Reset() {
	*x = CreateClusterBridgeRequest{}
	mi := &file_pilab_network_v2_cluster_bridge_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateClusterBridgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClusterBridgeRequest) ProtoMessage() {}

func (x *CreateClusterBridgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pilab_network_v2_cluster_bridge_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClusterBridgeRequest.ProtoReflect.Descriptor instead.
func (*CreateClusterBridgeRequest) Descriptor() ([]byte, []int) {
	return file_pilab_network_v2_cluster_bridge_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateClusterBridgeRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *CreateClusterBridgeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateClusterBridgeRequest) GetRole() NetworkRole {
	if x != nil {
		return x.Role
	}
	return NetworkRole_NETWORK_ROLE_UNSPECIFIED
}

func (x *CreateClusterBridgeRequest) GetVlan() int32 {
	if x != nil {
		return x.Vlan
	}
	return 0
}

func (x *CreateClusterBridgeRequest) GetMtu() int32 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

func (x *CreateClusterBridgeRequest) GetUplinks() []string {
	if x != nil {
		return x.Uplinks
	}
	return nil
}

func (x *CreateClusterBridgeRequest) GetUplinkBond() bool {
	if x != nil {
		return x.UplinkBond
	}
	return false
}

func (x *CreateClusterBridgeRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type GetClusterBridgeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ClusterId     string                 `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClusterBridgeRequest) Reset() {
	*x = GetClusterBridgeRequest{}
	mi := &file_pilab_network_v2_cluster_bridge_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClusterBridgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterBridgeRequest) ProtoMessage() {}

func (x *GetClusterBridgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pilab_network_v2_cluster_bridge_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClusterBridgeRequest.ProtoReflect.Descriptor instead.
func (*GetClusterBridgeRequest) Descriptor() ([]byte, []int) {
	return file_pilab_network_v2_cluster_bridge_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetClusterBridgeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetClusterBridgeRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

type ListClusterBridgesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClusterBridgesRequest) Reset() {
	*x = ListClusterBridgesRequest{}
	mi := &file_pilab_network_v2_cluster_bridge_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClusterBridgesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClusterBridgesRequest) ProtoMessage() {}

func (x *ListClusterBridgesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pilab_network_v2_cluster_bridge_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClusterBridgesRequest.ProtoReflect.Descriptor instead.
func (*ListClusterBridgesRequest) Descriptor() ([]byte, []int) {
	return file_pilab_network_v2_cluster_bridge_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListClusterBridgesRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

type ListClusterBridgesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bridges       []*ClusterBridge       `protobuf:"bytes,1,rep,name=bridges,proto3" json:"bridges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClusterBridgesResponse) Reset() {
	*x = ListClusterBridgesResponse{}
	mi := &file_pilab_network_v2_cluster_bridge_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClusterBridgesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClusterBridgesResponse) ProtoMessage() {}

func (x *ListClusterBridgesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pilab_network_v2_cluster_bridge_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClusterBridgesResponse.ProtoReflect.Descriptor instead.
func (*ListClusterBridgesResponse) Descriptor() ([]byte, []int) {
	return file_pilab_network_v2_cluster_bridge_service_proto_rawDescGZIP(), []int{4}
}

func (x *ListClusterBridgesResponse) GetBridges() []*ClusterBridge {
	if x != nil {
		return x.Bridges
	}
	return nil
}

type UpdateClusterBridgeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ClusterId     string                 `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Vlan          int32                  `protobuf:"varint,3,opt,name=vlan,proto3" json:"vlan,omitempty"`
	Mtu           int32                  `protobuf:"varint,4,opt,name=mtu,proto3" json:"mtu,omitempty"`
	Uplinks       []string               `protobuf:"bytes,5,rep,name=uplinks,proto3" json:"uplinks,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateClusterBridgeRequest) Reset() {
	*x = UpdateClusterBridgeRequest{}
	mi := &file_pilab_network_v2_cluster_bridge_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateClusterBridgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateClusterBridgeRequest) ProtoMessage() {}

func (x *UpdateClusterBridgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pilab_network_v2_cluster_bridge_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateClusterBridgeRequest.ProtoReflect.Descriptor instead.
func (*UpdateClusterBridgeRequest) Descriptor() ([]byte, []int) {
	return file_pilab_network_v2_cluster_bridge_service_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateClusterBridgeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateClusterBridgeRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *UpdateClusterBridgeRequest) GetVlan() int32 {
	if x != nil {
		return x.Vlan
	}
	return 0
}

func (x *UpdateClusterBridgeRequest) GetMtu() int32 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

func (x *UpdateClusterBridgeRequest) GetUplinks() []string {
	if x != nil {
		return x.Uplinks
	}
	return nil
}

func (x *UpdateClusterBridgeRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type DeleteClusterBridgeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ClusterId     string                 `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteClusterBridgeRequest) Reset() {
	*x = DeleteClusterBridgeRequest{}
	mi := &file_pilab_network_v2_cluster_bridge_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteClusterBridgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteClusterBridgeRequest) ProtoMessage() {}

func (x *DeleteClusterBridgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pilab_network_v2_cluster_bridge_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteClusterBridgeRequest.ProtoReflect.Descriptor instead.
func (*DeleteClusterBridgeRequest) Descriptor() ([]byte, []int) {
	return file_pilab_network_v2_cluster_bridge_service_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteClusterBridgeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteClusterBridgeRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

type AddUplinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BridgeId      string                 `protobuf:"bytes,1,opt,name=bridge_id,json=bridgeId,proto3" json:"bridge_id,omitempty"`
	ClusterId     string                 `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Interfaces    []string               `protobuf:"bytes,3,rep,name=interfaces,proto3" json:"interfaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUplinkRequest) Reset() {
	*x = AddUplinkRequest{}
	mi := &file_pilab_network_v2_cluster_bridge_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUplinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUplinkRequest) ProtoMessage() {}

func (x *AddUplinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pilab_network_v2_cluster_bridge_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUplinkRequest.ProtoReflect.Descriptor instead.
func (*AddUplinkRequest) Descriptor() ([]byte, []int) {
	return file_pilab_network_v2_cluster_bridge_service_proto_rawDescGZIP(), []int{7}
}

func (x *AddUplinkRequest) GetBridgeId() string {
	if x != nil {
		return x.BridgeId
	}
	return ""
}

func (x *AddUplinkRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *AddUplinkRequest) GetInterfaces() []string {
	if x != nil {
		return x.Interfaces
	}
	return nil
}

type RemoveUplinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BridgeId      string                 `protobuf:"bytes,1,opt,name=bridge_id,json=bridgeId,proto3" json:"bridge_id,omitempty"`
	ClusterId     string                 `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Interfaces    []string               `protobuf:"bytes,3,rep,name=interfaces,proto3" json:"interfaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveUplinkRequest) Reset() {
	*x = RemoveUplinkRequest{}
	mi := &file_pilab_network_v2_cluster_bridge_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveUplinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUplinkRequest) ProtoMessage() {}

func (x *RemoveUplinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pilab_network_v2_cluster_bridge_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUplinkRequest.ProtoReflect.Descriptor instead.
func (*RemoveUplinkRequest) Descriptor() ([]byte, []int) {
	return file_pilab_network_v2_cluster_bridge_service_proto_rawDescGZIP(), []int{8}
}

func (x *RemoveUplinkRequest) GetBridgeId() string {
	if x != nil {
		return x.BridgeId
	}
	return ""
}

func (x *RemoveUplinkRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *RemoveUplinkRequest) GetInterfaces() []string {
	if x != nil {
		return x.Interfaces
	}
	return nil
}

var File_pilab_network_v2_cluster_bridge_service_proto protoreflect.FileDescriptor

const file_pilab_network_v2_cluster_bridge_service_proto_rawDesc = "" +
	"\n" +
	"-pilab/network/v2/cluster_bridge_service.proto\x12\x10pilab.network.v2\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a%pilab/network/v2/network_common.proto\"\x8c\x04\n" +
	"\rClusterBridge\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x02 \x01(\tR\tclusterId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x121\n" +
	"\x04role\x18\x04 \x01(\x0e2\x1d.pilab.network.v2.NetworkRoleR\x04role\x12\x12\n" +
	"\x04vlan\x18\x05 \x01(\x05R\x04vlan\x12\x10\n" +
	"\x03mtu\x18\x06 \x01(\x05R\x03mtu\x12\x18\n" +
	"\auplinks\x18\a \x03(\tR\auplinks\x12&\n" +
	"\x0fovs_bridge_name\x18\b \x01(\tR\rovsBridgeName\x12\x1f\n" +
	"\vuplink_bond\x18\t \x01(\bR\n" +
	"uplinkBond\x12I\n" +
	"\bmetadata\x18\n" +
	" \x03(\v2-.pilab.network.v2.ClusterBridge.MetadataEntryR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf8\x02\n" +
	"\x1aCreateClusterBridgeRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x121\n" +
	"\x04role\x18\x03 \x01(\x0e2\x1d.pilab.network.v2.NetworkRoleR\x04role\x12\x12\n" +
	"\x04vlan\x18\x04 \x01(\x05R\x04vlan\x12\x10\n" +
	"\x03mtu\x18\x05 \x01(\x05R\x03mtu\x12\x18\n" +
	"\auplinks\x18\x06 \x03(\tR\auplinks\x12\x1f\n" +
	"\vuplink_bond\x18\a \x01(\bR\n" +
	"uplinkBond\x12V\n" +
	"\bmetadata\x18\b \x03(\v2:.pilab.network.v2.CreateClusterBridgeRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"H\n" +
	"\x17GetClusterBridgeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x02 \x01(\tR\tclusterId\":\n" +
	"\x19ListClusterBridgesRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\"W\n" +
	"\x1aListClusterBridgesResponse\x129\n" +
	"\abridges\x18\x01 \x03(\v2\x1f.pilab.network.v2.ClusterBridgeR\abridges\"\xa0\x02\n" +
	"\x1aUpdateClusterBridgeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x02 \x01(\tR\tclusterId\x12\x12\n" +
	"\x04vlan\x18\x03 \x01(\x05R\x04vlan\x12\x10\n" +
	"\x03mtu\x18\x04 \x01(\x05R\x03mtu\x12\x18\n" +
	"\auplinks\x18\x05 \x03(\tR\auplinks\x12V\n" +
	"\bmetadata\x18\x06 \x03(\v2:.pilab.network.v2.UpdateClusterBridgeRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"K\n" +
	"\x1aDeleteClusterBridgeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x02 \x01(\tR\tclusterId\"n\n" +
	"\x10AddUplinkRequest\x12\x1b\n" +
	"\tbridge_id\x18\x01 \x01(\tR\bbridgeId\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x02 \x01(\tR\tclusterId\x12\x1e\n" +
	"\n" +
	"interfaces\x18\x03 \x03(\tR\n" +
	"interfaces\"q\n" +
	"\x13RemoveUplinkRequest\x12\x1b\n" +
	"\tbridge_id\x18\x01 \x01(\tR\bbridgeId\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x02 \x01(\tR\tclusterId\x12\x1e\n" +
	"\n" +
	"interfaces\x18\x03 \x03(\tR\n" +
	"interfaces2\xa8\x05\n" +
	"\x14ClusterBridgeService\x12d\n" +
	"\x13CreateClusterBridge\x12,.pilab.network.v2.CreateClusterBridgeRequest\x1a\x1f.pilab.network.v2.ClusterBridge\x12^\n" +
	"\x10GetClusterBridge\x12).pilab.network.v2.GetClusterBridgeRequest\x1a\x1f.pilab.network.v2.ClusterBridge\x12o\n" +
	"\x12ListClusterBridges\x12+.pilab.network.v2.ListClusterBridgesRequest\x1a,.pilab.network.v2.ListClusterBridgesResponse\x12d\n" +
	"\x13UpdateClusterBridge\x12,.pilab.network.v2.UpdateClusterBridgeRequest\x1a\x1f.pilab.network.v2.ClusterBridge\x12[\n" +
	"\x13DeleteClusterBridge\x12,.pilab.network.v2.DeleteClusterBridgeRequest\x1a\x16.google.protobuf.Empty\x12G\n" +
	"\tAddUplink\x12\".pilab.network.v2.AddUplinkRequest\x1a\x16.google.protobuf.Empty\x12M\n" +
	"\fRemoveUplink\x12%.pilab.network.v2.RemoveUplinkRequest\x1a\x16.google.protobuf.EmptyB5Z3go.pilab.hu/cloud/virtpb/pilab/network/v2;networkv2b\x06proto3"

var (
	file_pilab_network_v2_cluster_bridge_service_proto_rawDescOnce sync.Once
	file_pilab_network_v2_cluster_bridge_service_proto_rawDescData []byte
)

func file_pilab_network_v2_cluster_bridge_service_proto_rawDescGZIP() []byte {
	file_pilab_network_v2_cluster_bridge_service_proto_rawDescOnce.Do(func() {
		file_pilab_network_v2_cluster_bridge_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pilab_network_v2_cluster_bridge_service_proto_rawDesc), len(file_pilab_network_v2_cluster_bridge_service_proto_rawDesc)))
	})
	return file_pilab_network_v2_cluster_bridge_service_proto_rawDescData
}

var file_pilab_network_v2_cluster_bridge_service_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_pilab_network_v2_cluster_bridge_service_proto_goTypes = []any{
	(*ClusterBridge)(nil),              // 0: pilab.network.v2.ClusterBridge
	(*CreateClusterBridgeRequest)(nil), // 1: pilab.network.v2.CreateClusterBridgeRequest
	(*GetClusterBridgeRequest)(nil),    // 2: pilab.network.v2.GetClusterBridgeRequest
	(*ListClusterBridgesRequest)(nil),  // 3: pilab.network.v2.ListClusterBridgesRequest
	(*ListClusterBridgesResponse)(nil), // 4: pilab.network.v2.ListClusterBridgesResponse
	(*UpdateClusterBridgeRequest)(nil), // 5: pilab.network.v2.UpdateClusterBridgeRequest
	(*DeleteClusterBridgeRequest)(nil), // 6: pilab.network.v2.DeleteClusterBridgeRequest
	(*AddUplinkRequest)(nil),           // 7: pilab.network.v2.AddUplinkRequest
	(*RemoveUplinkRequest)(nil),        // 8: pilab.network.v2.RemoveUplinkRequest
	nil,                                // 9: pilab.network.v2.ClusterBridge.MetadataEntry
	nil,                                // 10: pilab.network.v2.CreateClusterBridgeRequest.MetadataEntry
	nil,                                // 11: pilab.network.v2.UpdateClusterBridgeRequest.MetadataEntry
	(NetworkRole)(0),                   // 12: pilab.network.v2.NetworkRole
	(*timestamppb.Timestamp)(nil),      // 13: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),              // 14: google.protobuf.Empty
}
var file_pilab_network_v2_cluster_bridge_service_proto_depIdxs = []int32{
	12, // 0: pilab.network.v2.ClusterBridge.role:type_name -> pilab.network.v2.NetworkRole
	9,  // 1: pilab.network.v2.ClusterBridge.metadata:type_name -> pilab.network.v2.ClusterBridge.MetadataEntry
	13, // 2: pilab.network.v2.ClusterBridge.created_at:type_name -> google.protobuf.Timestamp
	13, // 3: pilab.network.v2.ClusterBridge.updated_at:type_name -> google.protobuf.Timestamp
	12, // 4: pilab.network.v2.CreateClusterBridgeRequest.role:type_name -> pilab.network.v2.NetworkRole
	10, // 5: pilab.network.v2.CreateClusterBridgeRequest.metadata:type_name -> pilab.network.v2.CreateClusterBridgeRequest.MetadataEntry
	0,  // 6: pilab.network.v2.ListClusterBridgesResponse.bridges:type_name -> pilab.network.v2.ClusterBridge
	11, // 7: pilab.network.v2.UpdateClusterBridgeRequest.metadata:type_name -> pilab.network.v2.UpdateClusterBridgeRequest.MetadataEntry
	1,  // 8: pilab.network.v2.ClusterBridgeService.CreateClusterBridge:input_type -> pilab.network.v2.CreateClusterBridgeRequest
	2,  // 9: pilab.network.v2.ClusterBridgeService.GetClusterBridge:input_type -> pilab.network.v2.GetClusterBridgeRequest
	3,  // 10: pilab.network.v2.ClusterBridgeService.ListClusterBridges:input_type -> pilab.network.v2.ListClusterBridgesRequest
	5,  // 11: pilab.network.v2.ClusterBridgeService.UpdateClusterBridge:input_type -> pilab.network.v2.UpdateClusterBridgeRequest
	6,  // 12: pilab.network.v2.ClusterBridgeService.DeleteClusterBridge:input_type -> pilab.network.v2.DeleteClusterBridgeRequest
	7,  // 13: pilab.network.v2.ClusterBridgeService.AddUplink:input_type -> pilab.network.v2.AddUplinkRequest
	8,  // 14: pilab.network.v2.ClusterBridgeService.RemoveUplink:input_type -> pilab.network.v2.RemoveUplinkRequest
	0,  // 15: pilab.network.v2.ClusterBridgeService.CreateClusterBridge:output_type -> pilab.network.v2.ClusterBridge
	0,  // 16: pilab.network.v2.ClusterBridgeService.GetClusterBridge:output_type -> pilab.network.v2.ClusterBridge
	4,  // 17: pilab.network.v2.ClusterBridgeService.ListClusterBridges:output_type -> pilab.network.v2.ListClusterBridgesResponse
	0,  // 18: pilab.network.v2.ClusterBridgeService.UpdateClusterBridge:output_type -> pilab.network.v2.ClusterBridge
	14, // 19: pilab.network.v2.ClusterBridgeService.DeleteClusterBridge:output_type -> google.protobuf.Empty
	14, // 20: pilab.network.v2.ClusterBridgeService.AddUplink:output_type -> google.protobuf.Empty
	14, // 21: pilab.network.v2.ClusterBridgeService.RemoveUplink:output_type -> google.protobuf.Empty
	15, // [15:22] is the sub-list for method output_type
	8,  // [8:15] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_pilab_network_v2_cluster_bridge_service_proto_init() }
func file_pilab_network_v2_cluster_bridge_service_proto_init() {
	if File_pilab_network_v2_cluster_bridge_service_proto != nil {
		return
	}
	file_pilab_network_v2_network_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pilab_network_v2_cluster_bridge_service_proto_rawDesc), len(file_pilab_network_v2_cluster_bridge_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pilab_network_v2_cluster_bridge_service_proto_goTypes,
		DependencyIndexes: file_pilab_network_v2_cluster_bridge_service_proto_depIdxs,
		MessageInfos:      file_pilab_network_v2_cluster_bridge_service_proto_msgTypes,
	}.Build()
	File_pilab_network_v2_cluster_bridge_service_proto = out.File
	file_pilab_network_v2_cluster_bridge_service_proto_goTypes = nil
	file_pilab_network_v2_cluster_bridge_service_proto_depIdxs = nil
}
