// =============================================================================
// DVS Service - Distributed Virtual Switch Management
// =============================================================================
// Purpose: Manage distributed virtual switches and port groups.
//
// Services:
// - Distributed Switch CRUD + Host management
// - Port Group CRUD
// =============================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pilab/network/v2/dvs_service.proto

package networkv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DistributedSwitch struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	TenantId           string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Description        string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	SwitchType         string                 `protobuf:"bytes,5,opt,name=switch_type,json=switchType,proto3" json:"switch_type,omitempty"`
	Mtu                int32                  `protobuf:"varint,6,opt,name=mtu,proto3" json:"mtu,omitempty"`
	EnableVlanTrunking bool                   `protobuf:"varint,7,opt,name=enable_vlan_trunking,json=enableVlanTrunking,proto3" json:"enable_vlan_trunking,omitempty"`
	AllowedVlanRanges  []uint32               `protobuf:"varint,8,rep,packed,name=allowed_vlan_ranges,json=allowedVlanRanges,proto3" json:"allowed_vlan_ranges,omitempty"`
	HostIds            []string               `protobuf:"bytes,9,rep,name=host_ids,json=hostIds,proto3" json:"host_ids,omitempty"`
	PortGroupIds       []string               `protobuf:"bytes,10,rep,name=port_group_ids,json=portGroupIds,proto3" json:"port_group_ids,omitempty"`
	Status             DVSStatus              `protobuf:"varint,11,opt,name=status,proto3,enum=pilab.network.v2.DVSStatus" json:"status,omitempty"`
	Metadata           map[string]string      `protobuf:"bytes,12,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt          *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DistributedSwitch) Reset() {
	*x = DistributedSwitch{}
	mi := &file_pilab_network_v2_dvs_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DistributedSwitch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistributedSwitch) ProtoMessage() {}

func (x *DistributedSwitch) ProtoReflect() protoreflect.Message {
	mi := &file_pilab_network_v2_dvs_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DistributedSwitch.ProtoReflect.Descriptor instead.
func (*DistributedSwitch) Descriptor() ([]byte, []int) {
	return file_pilab_network_v2_dvs_service_proto_rawDescGZIP(), []int{0}
}

func (x *DistributedSwitch) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DistributedSwitch) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DistributedSwitch) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *DistributedSwitch) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DistributedSwitch) GetSwitchType() string {
	if x != nil {
		return x.SwitchType
	}
	return ""
}

func (x *DistributedSwitch) GetMtu() int32 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

func (x *DistributedSwitch) GetEnableVlanTrunking() bool {
	if x != nil {
		return x.EnableVlanTrunking
	}
	return false
}

func (x *DistributedSwitch) GetAllowedVlanRanges() []uint32 {
	if x != nil {
		return x.AllowedVlanRanges
	}
	return nil
}

func (x *DistributedSwitch) GetHostIds() []string {
	if x != nil {
		return x.HostIds
	}
	return nil
}

func (x *DistributedSwitch) GetPortGroupIds() []string {
	if x != nil {
		return x.PortGroupIds
	}
	return nil
}

func (x *DistributedSwitch) GetStatus() DVSStatus {
	if x != nil {
		return x.Status
	}
	return DVSStatus_DVS_STATUS_UNSPECIFIED
}

func (x *DistributedSwitch) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *DistributedSwitch) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *DistributedSwitch) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type PortGroup struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	SwitchId            string                 `protobuf:"bytes,3,opt,name=switch_id,json=switchId,proto3" json:"switch_id,omitempty"`
	TenantId            string                 `protobuf:"bytes,4,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Description         string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	VlanId              uint32                 `protobuf:"varint,6,opt,name=vlan_id,json=vlanId,proto3" json:"vlan_id,omitempty"`
	VlanTrunkRangeStart uint32                 `protobuf:"varint,7,opt,name=vlan_trunk_range_start,json=vlanTrunkRangeStart,proto3" json:"vlan_trunk_range_start,omitempty"`
	VlanTrunkRangeEnd   uint32                 `protobuf:"varint,8,opt,name=vlan_trunk_range_end,json=vlanTrunkRangeEnd,proto3" json:"vlan_trunk_range_end,omitempty"`
	VlanTrunkEnabled    bool                   `protobuf:"varint,9,opt,name=vlan_trunk_enabled,json=vlanTrunkEnabled,proto3" json:"vlan_trunk_enabled,omitempty"`
	NetworkId           string                 `protobuf:"bytes,10,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	SecurityProfileId   string                 `protobuf:"bytes,11,opt,name=security_profile_id,json=securityProfileId,proto3" json:"security_profile_id,omitempty"`
	QosProfileId        string                 `protobuf:"bytes,12,opt,name=qos_profile_id,json=qosProfileId,proto3" json:"qos_profile_id,omitempty"`
	TeamingPolicy       *TeamingPolicy         `protobuf:"bytes,13,opt,name=teaming_policy,json=teamingPolicy,proto3" json:"teaming_policy,omitempty"`
	Metadata            map[string]string      `protobuf:"bytes,14,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt           *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt           *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PortGroup) Reset() {
	*x = PortGroup{}
	mi := &file_pilab_network_v2_dvs_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortGroup) ProtoMessage() {}

func (x *PortGroup) ProtoReflect() protoreflect.Message {
	mi := &file_pilab_network_v2_dvs_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortGroup.ProtoReflect.Descriptor instead.
func (*PortGroup) Descriptor() ([]byte, []int) {
	return file_pilab_network_v2_dvs_service_proto_rawDescGZIP(), []int{1}
}

func (x *PortGroup) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PortGroup) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PortGroup) GetSwitchId() string {
	if x != nil {
		return x.SwitchId
	}
	return ""
}

func (x *PortGroup) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *PortGroup) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PortGroup) GetVlanId() uint32 {
	if x != nil {
		return x.VlanId
	}
	return 0
}

func (x *PortGroup) GetVlanTrunkRangeStart() uint32 {
	if x != nil {
		return x.VlanTrunkRangeStart
	}
	return 0
}

func (x *PortGroup) GetVlanTrunkRangeEnd() uint32 {
	if x != nil {
		return x.VlanTrunkRangeEnd
	}
	return 0
}

func (x *PortGroup) GetVlanTrunkEnabled() bool {
	if x != nil {
		return x.VlanTrunkEnabled
	}
	return false
}

func (x *PortGroup) GetNetworkId() string {
	if x != nil {
		return x.NetworkId
	}
	return ""
}

func (x *PortGroup) GetSecurityProfileId() string {
	if x != nil {
		return x.SecurityProfileId
	}
	return ""
}

func (x *PortGroup) GetQosProfileId() string {
	if x != nil {
		return x.QosProfileId
	}
	return ""
}

func (x *PortGroup) GetTeamingPolicy() *TeamingPolicy {
	if x != nil {
		return x.TeamingPolicy
	}
	return nil
}

func (x *PortGroup) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *PortGroup) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PortGroup) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateDistributedSwitchRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Name               string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TenantId           string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Description        string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	SwitchType         string                 `protobuf:"bytes,4,opt,name=switch_type,json=switchType,proto3" json:"switch_type,omitempty"`
	Mtu                int32                  `protobuf:"varint,5,opt,name=mtu,proto3" json:"mtu,omitempty"`
	EnableVlanTrunking bool                   `protobuf:"varint,6,opt,name=enable_vlan_trunking,json=enableVlanTrunking,proto3" json:"enable_vlan_trunking,omitempty"`
	AllowedVlanRanges  []uint32               `protobuf:"varint,7,rep,packed,name=allowed_vlan_ranges,json=allowedVlanRanges,proto3" json:"allowed_vlan_ranges,omitempty"`
	HostIds            []string               `protobuf:"bytes,8,rep,name=host_ids,json=hostIds,proto3" json:"host_ids,omitempty"`
	Metadata           map[string]string      `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CreateDistributedSwitchRequest) Reset() {
	*x = CreateDistributedSwitchRequest{}
	mi := &file_pilab_network_v2_dvs_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDistributedSwitchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDistributedSwitchRequest) ProtoMessage() {}

func (x *CreateDistributedSwitchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pilab_network_v2_dvs_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDistributedSwitchRequest.ProtoReflect.Descriptor instead.
func (*CreateDistributedSwitchRequest) Descriptor() ([]byte, []int) {
	return file_pilab_network_v2_dvs_service_proto_rawDescGZIP(), []int{2}
}

func (x *CreateDistributedSwitchRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateDistributedSwitchRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateDistributedSwitchRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateDistributedSwitchRequest) GetSwitchType() string {
	if x != nil {
		return x.SwitchType
	}
	return ""
}

func (x *CreateDistributedSwitchRequest) GetMtu() int32 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

func (x *CreateDistributedSwitchRequest) GetEnableVlanTrunking() bool {
	if x != nil {
		return x.EnableVlanTrunking
	}
	return false
}

func (x *CreateDistributedSwitchRequest) GetAllowedVlanRanges() []uint32 {
	if x != nil {
		return x.AllowedVlanRanges
	}
	return nil
}

func (x *CreateDistributedSwitchRequest) GetHostIds() []string {
	if x != nil {
		return x.HostIds
	}
	return nil
}

func (x *CreateDistributedSwitchRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type GetDistributedSwitchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SwitchId      string                 `protobuf:"bytes,1,opt,name=switch_id,json=switchId,proto3" json:"switch_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDistributedSwitchRequest) Reset() {
	*x = GetDistributedSwitchRequest{}
	mi := &file_pilab_network_v2_dvs_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDistributedSwitchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDistributedSwitchRequest) ProtoMessage() {}

func (x *GetDistributedSwitchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pilab_network_v2_dvs_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDistributedSwitchRequest.ProtoReflect.Descriptor instead.
func (*GetDistributedSwitchRequest) Descriptor() ([]byte, []int) {
	return file_pilab_network_v2_dvs_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetDistributedSwitchRequest) GetSwitchId() string {
	if x != nil {
		return x.SwitchId
	}
	return ""
}

type ListDistributedSwitchesRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	TenantId      string                  `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Cursor        *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit         int32                   `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDistributedSwitchesRequest) Reset() {
	*x = ListDistributedSwitchesRequest{}
	mi := &file_pilab_network_v2_dvs_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDistributedSwitchesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDistributedSwitchesRequest) ProtoMessage() {}

func (x *ListDistributedSwitchesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pilab_network_v2_dvs_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDistributedSwitchesRequest.ProtoReflect.Descriptor instead.
func (*ListDistributedSwitchesRequest) Descriptor() ([]byte, []int) {
	return file_pilab_network_v2_dvs_service_proto_rawDescGZIP(), []int{4}
}

func (x *ListDistributedSwitchesRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListDistributedSwitchesRequest) GetCursor() *wrapperspb.StringValue {
	if x != nil {
		return x.Cursor
	}
	return nil
}

func (x *ListDistributedSwitchesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListDistributedSwitchesResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Switches      []*DistributedSwitch    `protobuf:"bytes,1,rep,name=switches,proto3" json:"switches,omitempty"`
	NextCursor    *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	Total         int32                   `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDistributedSwitchesResponse) Reset() {
	*x = ListDistributedSwitchesResponse{}
	mi := &file_pilab_network_v2_dvs_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDistributedSwitchesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDistributedSwitchesResponse) ProtoMessage() {}

func (x *ListDistributedSwitchesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pilab_network_v2_dvs_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDistributedSwitchesResponse.ProtoReflect.Descriptor instead.
func (*ListDistributedSwitchesResponse) Descriptor() ([]byte, []int) {
	return file_pilab_network_v2_dvs_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListDistributedSwitchesResponse) GetSwitches() []*DistributedSwitch {
	if x != nil {
		return x.Switches
	}
	return nil
}

func (x *ListDistributedSwitchesResponse) GetNextCursor() *wrapperspb.StringValue {
	if x != nil {
		return x.NextCursor
	}
	return nil
}

func (x *ListDistributedSwitchesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type UpdateDistributedSwitchRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SwitchId           string                 `protobuf:"bytes,1,opt,name=switch_id,json=switchId,proto3" json:"switch_id,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description        string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Mtu                int32                  `protobuf:"varint,4,opt,name=mtu,proto3" json:"mtu,omitempty"`
	EnableVlanTrunking bool                   `protobuf:"varint,5,opt,name=enable_vlan_trunking,json=enableVlanTrunking,proto3" json:"enable_vlan_trunking,omitempty"`
	AllowedVlanRanges  []uint32               `protobuf:"varint,6,rep,packed,name=allowed_vlan_ranges,json=allowedVlanRanges,proto3" json:"allowed_vlan_ranges,omitempty"`
	Metadata           map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UpdateDistributedSwitchRequest) Reset() {
	*x = UpdateDistributedSwitchRequest{}
	mi := &file_pilab_network_v2_dvs_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDistributedSwitchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDistributedSwitchRequest) ProtoMessage() {}

func (x *UpdateDistributedSwitchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pilab_network_v2_dvs_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDistributedSwitchRequest.ProtoReflect.Descriptor instead.
func (*UpdateDistributedSwitchRequest) Descriptor() ([]byte, []int) {
	return file_pilab_network_v2_dvs_service_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateDistributedSwitchRequest) GetSwitchId() string {
	if x != nil {
		return x.SwitchId
	}
	return ""
}

func (x *UpdateDistributedSwitchRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateDistributedSwitchRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateDistributedSwitchRequest) GetMtu() int32 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

func (x *UpdateDistributedSwitchRequest) GetEnableVlanTrunking() bool {
	if x != nil {
		return x.EnableVlanTrunking
	}
	return false
}

func (x *UpdateDistributedSwitchRequest) GetAllowedVlanRanges() []uint32 {
	if x != nil {
		return x.AllowedVlanRanges
	}
	return nil
}

func (x *UpdateDistributedSwitchRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type DeleteDistributedSwitchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SwitchId      string                 `protobuf:"bytes,1,opt,name=switch_id,json=switchId,proto3" json:"switch_id,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDistributedSwitchRequest) Reset() {
	*x = DeleteDistributedSwitchRequest{}
	mi := &file_pilab_network_v2_dvs_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDistributedSwitchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDistributedSwitchRequest) ProtoMessage() {}

func (x *DeleteDistributedSwitchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pilab_network_v2_dvs_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDistributedSwitchRequest.ProtoReflect.Descriptor instead.
func (*DeleteDistributedSwitchRequest) Descriptor() ([]byte, []int) {
	return file_pilab_network_v2_dvs_service_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteDistributedSwitchRequest) GetSwitchId() string {
	if x != nil {
		return x.SwitchId
	}
	return ""
}

func (x *DeleteDistributedSwitchRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type AddHostToDVSRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SwitchId      string                 `protobuf:"bytes,1,opt,name=switch_id,json=switchId,proto3" json:"switch_id,omitempty"`
	HostId        string                 `protobuf:"bytes,2,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddHostToDVSRequest) Reset() {
	*x = AddHostToDVSRequest{}
	mi := &file_pilab_network_v2_dvs_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddHostToDVSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddHostToDVSRequest) ProtoMessage() {}

func (x *AddHostToDVSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pilab_network_v2_dvs_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddHostToDVSRequest.ProtoReflect.Descriptor instead.
func (*AddHostToDVSRequest) Descriptor() ([]byte, []int) {
	return file_pilab_network_v2_dvs_service_proto_rawDescGZIP(), []int{8}
}

func (x *AddHostToDVSRequest) GetSwitchId() string {
	if x != nil {
		return x.SwitchId
	}
	return ""
}

func (x *AddHostToDVSRequest) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

type RemoveHostFromDVSRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SwitchId      string                 `protobuf:"bytes,1,opt,name=switch_id,json=switchId,proto3" json:"switch_id,omitempty"`
	HostId        string                 `protobuf:"bytes,2,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveHostFromDVSRequest) Reset() {
	*x = RemoveHostFromDVSRequest{}
	mi := &file_pilab_network_v2_dvs_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveHostFromDVSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveHostFromDVSRequest) ProtoMessage() {}

func (x *RemoveHostFromDVSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pilab_network_v2_dvs_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveHostFromDVSRequest.ProtoReflect.Descriptor instead.
func (*RemoveHostFromDVSRequest) Descriptor() ([]byte, []int) {
	return file_pilab_network_v2_dvs_service_proto_rawDescGZIP(), []int{9}
}

func (x *RemoveHostFromDVSRequest) GetSwitchId() string {
	if x != nil {
		return x.SwitchId
	}
	return ""
}

func (x *RemoveHostFromDVSRequest) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

type CreatePortGroupRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Name                string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	SwitchId            string                 `protobuf:"bytes,2,opt,name=switch_id,json=switchId,proto3" json:"switch_id,omitempty"`
	TenantId            string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Description         string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	VlanId              uint32                 `protobuf:"varint,5,opt,name=vlan_id,json=vlanId,proto3" json:"vlan_id,omitempty"`
	VlanTrunkRangeStart uint32                 `protobuf:"varint,6,opt,name=vlan_trunk_range_start,json=vlanTrunkRangeStart,proto3" json:"vlan_trunk_range_start,omitempty"`
	VlanTrunkRangeEnd   uint32                 `protobuf:"varint,7,opt,name=vlan_trunk_range_end,json=vlanTrunkRangeEnd,proto3" json:"vlan_trunk_range_end,omitempty"`
	VlanTrunkEnabled    bool                   `protobuf:"varint,8,opt,name=vlan_trunk_enabled,json=vlanTrunkEnabled,proto3" json:"vlan_trunk_enabled,omitempty"`
	SecurityProfileId   string                 `protobuf:"bytes,9,opt,name=security_profile_id,json=securityProfileId,proto3" json:"security_profile_id,omitempty"`
	QosProfileId        string                 `protobuf:"bytes,10,opt,name=qos_profile_id,json=qosProfileId,proto3" json:"qos_profile_id,omitempty"`
	TeamingPolicy       *TeamingPolicy         `protobuf:"bytes,11,opt,name=teaming_policy,json=teamingPolicy,proto3" json:"teaming_policy,omitempty"`
	Metadata            map[string]string      `protobuf:"bytes,12,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CreatePortGroupRequest) Reset() {
	*x = CreatePortGroupRequest{}
	mi := &file_pilab_network_v2_dvs_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePortGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePortGroupRequest) ProtoMessage() {}

func (x *CreatePortGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pilab_network_v2_dvs_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePortGroupRequest.ProtoReflect.Descriptor instead.
func (*CreatePortGroupRequest) Descriptor() ([]byte, []int) {
	return file_pilab_network_v2_dvs_service_proto_rawDescGZIP(), []int{10}
}

func (x *CreatePortGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePortGroupRequest) GetSwitchId() string {
	if x != nil {
		return x.SwitchId
	}
	return ""
}

func (x *CreatePortGroupRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreatePortGroupRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreatePortGroupRequest) GetVlanId() uint32 {
	if x != nil {
		return x.VlanId
	}
	return 0
}

func (x *CreatePortGroupRequest) GetVlanTrunkRangeStart() uint32 {
	if x != nil {
		return x.VlanTrunkRangeStart
	}
	return 0
}

func (x *CreatePortGroupRequest) GetVlanTrunkRangeEnd() uint32 {
	if x != nil {
		return x.VlanTrunkRangeEnd
	}
	return 0
}

func (x *CreatePortGroupRequest) GetVlanTrunkEnabled() bool {
	if x != nil {
		return x.VlanTrunkEnabled
	}
	return false
}

func (x *CreatePortGroupRequest) GetSecurityProfileId() string {
	if x != nil {
		return x.SecurityProfileId
	}
	return ""
}

func (x *CreatePortGroupRequest) GetQosProfileId() string {
	if x != nil {
		return x.QosProfileId
	}
	return ""
}

func (x *CreatePortGroupRequest) GetTeamingPolicy() *TeamingPolicy {
	if x != nil {
		return x.TeamingPolicy
	}
	return nil
}

func (x *CreatePortGroupRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type GetPortGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PortGroupId   string                 `protobuf:"bytes,1,opt,name=port_group_id,json=portGroupId,proto3" json:"port_group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPortGroupRequest) Reset() {
	*x = GetPortGroupRequest{}
	mi := &file_pilab_network_v2_dvs_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPortGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPortGroupRequest) ProtoMessage() {}

func (x *GetPortGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pilab_network_v2_dvs_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPortGroupRequest.ProtoReflect.Descriptor instead.
func (*GetPortGroupRequest) Descriptor() ([]byte, []int) {
	return file_pilab_network_v2_dvs_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetPortGroupRequest) GetPortGroupId() string {
	if x != nil {
		return x.PortGroupId
	}
	return ""
}

type ListPortGroupsRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	SwitchId      string                  `protobuf:"bytes,1,opt,name=switch_id,json=switchId,proto3" json:"switch_id,omitempty"`
	Cursor        *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit         int32                   `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPortGroupsRequest) Reset() {
	*x = ListPortGroupsRequest{}
	mi := &file_pilab_network_v2_dvs_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPortGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPortGroupsRequest) ProtoMessage() {}

func (x *ListPortGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pilab_network_v2_dvs_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPortGroupsRequest.ProtoReflect.Descriptor instead.
func (*ListPortGroupsRequest) Descriptor() ([]byte, []int) {
	return file_pilab_network_v2_dvs_service_proto_rawDescGZIP(), []int{12}
}

func (x *ListPortGroupsRequest) GetSwitchId() string {
	if x != nil {
		return x.SwitchId
	}
	return ""
}

func (x *ListPortGroupsRequest) GetCursor() *wrapperspb.StringValue {
	if x != nil {
		return x.Cursor
	}
	return nil
}

func (x *ListPortGroupsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListPortGroupsResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	PortGroups    []*PortGroup            `protobuf:"bytes,1,rep,name=port_groups,json=portGroups,proto3" json:"port_groups,omitempty"`
	NextCursor    *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	Total         int32                   `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPortGroupsResponse) Reset() {
	*x = ListPortGroupsResponse{}
	mi := &file_pilab_network_v2_dvs_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPortGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPortGroupsResponse) ProtoMessage() {}

func (x *ListPortGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pilab_network_v2_dvs_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPortGroupsResponse.ProtoReflect.Descriptor instead.
func (*ListPortGroupsResponse) Descriptor() ([]byte, []int) {
	return file_pilab_network_v2_dvs_service_proto_rawDescGZIP(), []int{13}
}

func (x *ListPortGroupsResponse) GetPortGroups() []*PortGroup {
	if x != nil {
		return x.PortGroups
	}
	return nil
}

func (x *ListPortGroupsResponse) GetNextCursor() *wrapperspb.StringValue {
	if x != nil {
		return x.NextCursor
	}
	return nil
}

func (x *ListPortGroupsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type UpdatePortGroupRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PortGroupId       string                 `protobuf:"bytes,1,opt,name=port_group_id,json=portGroupId,proto3" json:"port_group_id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	VlanId            uint32                 `protobuf:"varint,3,opt,name=vlan_id,json=vlanId,proto3" json:"vlan_id,omitempty"`
	SecurityProfileId string                 `protobuf:"bytes,4,opt,name=security_profile_id,json=securityProfileId,proto3" json:"security_profile_id,omitempty"`
	QosProfileId      string                 `protobuf:"bytes,5,opt,name=qos_profile_id,json=qosProfileId,proto3" json:"qos_profile_id,omitempty"`
	TeamingPolicy     *TeamingPolicy         `protobuf:"bytes,6,opt,name=teaming_policy,json=teamingPolicy,proto3" json:"teaming_policy,omitempty"`
	Metadata          map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdatePortGroupRequest) Reset() {
	*x = UpdatePortGroupRequest{}
	mi := &file_pilab_network_v2_dvs_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePortGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePortGroupRequest) ProtoMessage() {}

func (x *UpdatePortGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pilab_network_v2_dvs_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePortGroupRequest.ProtoReflect.Descriptor instead.
func (*UpdatePortGroupRequest) Descriptor() ([]byte, []int) {
	return file_pilab_network_v2_dvs_service_proto_rawDescGZIP(), []int{14}
}

func (x *UpdatePortGroupRequest) GetPortGroupId() string {
	if x != nil {
		return x.PortGroupId
	}
	return ""
}

func (x *UpdatePortGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdatePortGroupRequest) GetVlanId() uint32 {
	if x != nil {
		return x.VlanId
	}
	return 0
}

func (x *UpdatePortGroupRequest) GetSecurityProfileId() string {
	if x != nil {
		return x.SecurityProfileId
	}
	return ""
}

func (x *UpdatePortGroupRequest) GetQosProfileId() string {
	if x != nil {
		return x.QosProfileId
	}
	return ""
}

func (x *UpdatePortGroupRequest) GetTeamingPolicy() *TeamingPolicy {
	if x != nil {
		return x.TeamingPolicy
	}
	return nil
}

func (x *UpdatePortGroupRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type DeletePortGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PortGroupId   string                 `protobuf:"bytes,1,opt,name=port_group_id,json=portGroupId,proto3" json:"port_group_id,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePortGroupRequest) Reset() {
	*x = DeletePortGroupRequest{}
	mi := &file_pilab_network_v2_dvs_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePortGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePortGroupRequest) ProtoMessage() {}

func (x *DeletePortGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pilab_network_v2_dvs_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePortGroupRequest.ProtoReflect.Descriptor instead.
func (*DeletePortGroupRequest) Descriptor() ([]byte, []int) {
	return file_pilab_network_v2_dvs_service_proto_rawDescGZIP(), []int{15}
}

func (x *DeletePortGroupRequest) GetPortGroupId() string {
	if x != nil {
		return x.PortGroupId
	}
	return ""
}

func (x *DeletePortGroupRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

var File_pilab_network_v2_dvs_service_proto protoreflect.FileDescriptor

const file_pilab_network_v2_dvs_service_proto_rawDesc = "" +
	"\n" +
	"\"pilab/network/v2/dvs_service.proto\x12\x10pilab.network.v2\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a%pilab/network/v2/network_common.proto\"\x83\x05\n" +
	"\x11DistributedSwitch\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1f\n" +
	"\vswitch_type\x18\x05 \x01(\tR\n" +
	"switchType\x12\x10\n" +
	"\x03mtu\x18\x06 \x01(\x05R\x03mtu\x120\n" +
	"\x14enable_vlan_trunking\x18\a \x01(\bR\x12enableVlanTrunking\x12.\n" +
	"\x13allowed_vlan_ranges\x18\b \x03(\rR\x11allowedVlanRanges\x12\x19\n" +
	"\bhost_ids\x18\t \x03(\tR\ahostIds\x12$\n" +
	"\x0eport_group_ids\x18\n" +
	" \x03(\tR\fportGroupIds\x123\n" +
	"\x06status\x18\v \x01(\x0e2\x1b.pilab.network.v2.DVSStatusR\x06status\x12M\n" +
	"\bmetadata\x18\f \x03(\v21.pilab.network.v2.DistributedSwitch.MetadataEntryR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xef\x05\n" +
	"\tPortGroup\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tswitch_id\x18\x03 \x01(\tR\bswitchId\x12\x1b\n" +
	"\ttenant_id\x18\x04 \x01(\tR\btenantId\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x17\n" +
	"\avlan_id\x18\x06 \x01(\rR\x06vlanId\x123\n" +
	"\x16vlan_trunk_range_start\x18\a \x01(\rR\x13vlanTrunkRangeStart\x12/\n" +
	"\x14vlan_trunk_range_end\x18\b \x01(\rR\x11vlanTrunkRangeEnd\x12,\n" +
	"\x12vlan_trunk_enabled\x18\t \x01(\bR\x10vlanTrunkEnabled\x12\x1d\n" +
	"\n" +
	"network_id\x18\n" +
	" \x01(\tR\tnetworkId\x12.\n" +
	"\x13security_profile_id\x18\v \x01(\tR\x11securityProfileId\x12$\n" +
	"\x0eqos_profile_id\x18\f \x01(\tR\fqosProfileId\x12F\n" +
	"\x0eteaming_policy\x18\r \x01(\v2\x1f.pilab.network.v2.TeamingPolicyR\rteamingPolicy\x12E\n" +
	"\bmetadata\x18\x0e \x03(\v2).pilab.network.v2.PortGroup.MetadataEntryR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbc\x03\n" +
	"\x1eCreateDistributedSwitchRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1f\n" +
	"\vswitch_type\x18\x04 \x01(\tR\n" +
	"switchType\x12\x10\n" +
	"\x03mtu\x18\x05 \x01(\x05R\x03mtu\x120\n" +
	"\x14enable_vlan_trunking\x18\x06 \x01(\bR\x12enableVlanTrunking\x12.\n" +
	"\x13allowed_vlan_ranges\x18\a \x03(\rR\x11allowedVlanRanges\x12\x19\n" +
	"\bhost_ids\x18\b \x03(\tR\ahostIds\x12Z\n" +
	"\bmetadata\x18\t \x03(\v2>.pilab.network.v2.CreateDistributedSwitchRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\":\n" +
	"\x1bGetDistributedSwitchRequest\x12\x1b\n" +
	"\tswitch_id\x18\x01 \x01(\tR\bswitchId\"\x89\x01\n" +
	"\x1eListDistributedSwitchesRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x124\n" +
	"\x06cursor\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\x06cursor\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\xb7\x01\n" +
	"\x1fListDistributedSwitchesResponse\x12?\n" +
	"\bswitches\x18\x01 \x03(\v2#.pilab.network.v2.DistributedSwitchR\bswitches\x12=\n" +
	"\vnext_cursor\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\n" +
	"nextCursor\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total\"\x80\x03\n" +
	"\x1eUpdateDistributedSwitchRequest\x12\x1b\n" +
	"\tswitch_id\x18\x01 \x01(\tR\bswitchId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x10\n" +
	"\x03mtu\x18\x04 \x01(\x05R\x03mtu\x120\n" +
	"\x14enable_vlan_trunking\x18\x05 \x01(\bR\x12enableVlanTrunking\x12.\n" +
	"\x13allowed_vlan_ranges\x18\x06 \x03(\rR\x11allowedVlanRanges\x12Z\n" +
	"\bmetadata\x18\a \x03(\v2>.pilab.network.v2.UpdateDistributedSwitchRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"S\n" +
	"\x1eDeleteDistributedSwitchRequest\x12\x1b\n" +
	"\tswitch_id\x18\x01 \x01(\tR\bswitchId\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"K\n" +
	"\x13AddHostToDVSRequest\x12\x1b\n" +
	"\tswitch_id\x18\x01 \x01(\tR\bswitchId\x12\x17\n" +
	"\ahost_id\x18\x02 \x01(\tR\x06hostId\"P\n" +
	"\x18RemoveHostFromDVSRequest\x12\x1b\n" +
	"\tswitch_id\x18\x01 \x01(\tR\bswitchId\x12\x17\n" +
	"\ahost_id\x18\x02 \x01(\tR\x06hostId\"\xe4\x04\n" +
	"\x16CreatePortGroupRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tswitch_id\x18\x02 \x01(\tR\bswitchId\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x17\n" +
	"\avlan_id\x18\x05 \x01(\rR\x06vlanId\x123\n" +
	"\x16vlan_trunk_range_start\x18\x06 \x01(\rR\x13vlanTrunkRangeStart\x12/\n" +
	"\x14vlan_trunk_range_end\x18\a \x01(\rR\x11vlanTrunkRangeEnd\x12,\n" +
	"\x12vlan_trunk_enabled\x18\b \x01(\bR\x10vlanTrunkEnabled\x12.\n" +
	"\x13security_profile_id\x18\t \x01(\tR\x11securityProfileId\x12$\n" +
	"\x0eqos_profile_id\x18\n" +
	" \x01(\tR\fqosProfileId\x12F\n" +
	"\x0eteaming_policy\x18\v \x01(\v2\x1f.pilab.network.v2.TeamingPolicyR\rteamingPolicy\x12R\n" +
	"\bmetadata\x18\f \x03(\v26.pilab.network.v2.CreatePortGroupRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"9\n" +
	"\x13GetPortGroupRequest\x12\"\n" +
	"\rport_group_id\x18\x01 \x01(\tR\vportGroupId\"\x80\x01\n" +
	"\x15ListPortGroupsRequest\x12\x1b\n" +
	"\tswitch_id\x18\x01 \x01(\tR\bswitchId\x124\n" +
	"\x06cursor\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\x06cursor\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\xab\x01\n" +
	"\x16ListPortGroupsResponse\x12<\n" +
	"\vport_groups\x18\x01 \x03(\v2\x1b.pilab.network.v2.PortGroupR\n" +
	"portGroups\x12=\n" +
	"\vnext_cursor\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\n" +
	"nextCursor\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total\"\x98\x03\n" +
	"\x16UpdatePortGroupRequest\x12\"\n" +
	"\rport_group_id\x18\x01 \x01(\tR\vportGroupId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x17\n" +
	"\avlan_id\x18\x03 \x01(\rR\x06vlanId\x12.\n" +
	"\x13security_profile_id\x18\x04 \x01(\tR\x11securityProfileId\x12$\n" +
	"\x0eqos_profile_id\x18\x05 \x01(\tR\fqosProfileId\x12F\n" +
	"\x0eteaming_policy\x18\x06 \x01(\v2\x1f.pilab.network.v2.TeamingPolicyR\rteamingPolicy\x12R\n" +
	"\bmetadata\x18\a \x03(\v26.pilab.network.v2.UpdatePortGroupRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"R\n" +
	"\x16DeletePortGroupRequest\x12\"\n" +
	"\rport_group_id\x18\x01 \x01(\tR\vportGroupId\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force2\xab\t\n" +
	"\n" +
	"DVSService\x12p\n" +
	"\x17CreateDistributedSwitch\x120.pilab.network.v2.CreateDistributedSwitchRequest\x1a#.pilab.network.v2.DistributedSwitch\x12j\n" +
	"\x14GetDistributedSwitch\x12-.pilab.network.v2.GetDistributedSwitchRequest\x1a#.pilab.network.v2.DistributedSwitch\x12~\n" +
	"\x17ListDistributedSwitches\x120.pilab.network.v2.ListDistributedSwitchesRequest\x1a1.pilab.network.v2.ListDistributedSwitchesResponse\x12p\n" +
	"\x17UpdateDistributedSwitch\x120.pilab.network.v2.UpdateDistributedSwitchRequest\x1a#.pilab.network.v2.DistributedSwitch\x12c\n" +
	"\x17DeleteDistributedSwitch\x120.pilab.network.v2.DeleteDistributedSwitchRequest\x1a\x16.google.protobuf.Empty\x12M\n" +
	"\fAddHostToDVS\x12%.pilab.network.v2.AddHostToDVSRequest\x1a\x16.google.protobuf.Empty\x12W\n" +
	"\x11RemoveHostFromDVS\x12*.pilab.network.v2.RemoveHostFromDVSRequest\x1a\x16.google.protobuf.Empty\x12X\n" +
	"\x0fCreatePortGroup\x12(.pilab.network.v2.CreatePortGroupRequest\x1a\x1b.pilab.network.v2.PortGroup\x12R\n" +
	"\fGetPortGroup\x12%.pilab.network.v2.GetPortGroupRequest\x1a\x1b.pilab.network.v2.PortGroup\x12c\n" +
	"\x0eListPortGroups\x12'.pilab.network.v2.ListPortGroupsRequest\x1a(.pilab.network.v2.ListPortGroupsResponse\x12X\n" +
	"\x0fUpdatePortGroup\x12(.pilab.network.v2.UpdatePortGroupRequest\x1a\x1b.pilab.network.v2.PortGroup\x12S\n" +
	"\x0fDeletePortGroup\x12(.pilab.network.v2.DeletePortGroupRequest\x1a\x16.google.protobuf.EmptyB5Z3go.pilab.hu/cloud/virtpb/pilab/network/v2;networkv2b\x06proto3"

var (
	file_pilab_network_v2_dvs_service_proto_rawDescOnce sync.Once
	file_pilab_network_v2_dvs_service_proto_rawDescData []byte
)

func file_pilab_network_v2_dvs_service_proto_rawDescGZIP() []byte {
	file_pilab_network_v2_dvs_service_proto_rawDescOnce.Do(func() {
		file_pilab_network_v2_dvs_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pilab_network_v2_dvs_service_proto_rawDesc), len(file_pilab_network_v2_dvs_service_proto_rawDesc)))
	})
	return file_pilab_network_v2_dvs_service_proto_rawDescData
}

var file_pilab_network_v2_dvs_service_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_pilab_network_v2_dvs_service_proto_goTypes = []any{
	(*DistributedSwitch)(nil),               // 0: pilab.network.v2.DistributedSwitch
	(*PortGroup)(nil),                       // 1: pilab.network.v2.PortGroup
	(*CreateDistributedSwitchRequest)(nil),  // 2: pilab.network.v2.CreateDistributedSwitchRequest
	(*GetDistributedSwitchRequest)(nil),     // 3: pilab.network.v2.GetDistributedSwitchRequest
	(*ListDistributedSwitchesRequest)(nil),  // 4: pilab.network.v2.ListDistributedSwitchesRequest
	(*ListDistributedSwitchesResponse)(nil), // 5: pilab.network.v2.ListDistributedSwitchesResponse
	(*UpdateDistributedSwitchRequest)(nil),  // 6: pilab.network.v2.UpdateDistributedSwitchRequest
	(*DeleteDistributedSwitchRequest)(nil),  // 7: pilab.network.v2.DeleteDistributedSwitchRequest
	(*AddHostToDVSRequest)(nil),             // 8: pilab.network.v2.AddHostToDVSRequest
	(*RemoveHostFromDVSRequest)(nil),        // 9: pilab.network.v2.RemoveHostFromDVSRequest
	(*CreatePortGroupRequest)(nil),          // 10: pilab.network.v2.CreatePortGroupRequest
	(*GetPortGroupRequest)(nil),             // 11: pilab.network.v2.GetPortGroupRequest
	(*ListPortGroupsRequest)(nil),           // 12: pilab.network.v2.ListPortGroupsRequest
	(*ListPortGroupsResponse)(nil),          // 13: pilab.network.v2.ListPortGroupsResponse
	(*UpdatePortGroupRequest)(nil),          // 14: pilab.network.v2.UpdatePortGroupRequest
	(*DeletePortGroupRequest)(nil),          // 15: pilab.network.v2.DeletePortGroupRequest
	nil,                                     // 16: pilab.network.v2.DistributedSwitch.MetadataEntry
	nil,                                     // 17: pilab.network.v2.PortGroup.MetadataEntry
	nil,                                     // 18: pilab.network.v2.CreateDistributedSwitchRequest.MetadataEntry
	nil,                                     // 19: pilab.network.v2.UpdateDistributedSwitchRequest.MetadataEntry
	nil,                                     // 20: pilab.network.v2.CreatePortGroupRequest.MetadataEntry
	nil,                                     // 21: pilab.network.v2.UpdatePortGroupRequest.MetadataEntry
	(DVSStatus)(0),                          // 22: pilab.network.v2.DVSStatus
	(*timestamppb.Timestamp)(nil),           // 23: google.protobuf.Timestamp
	(*TeamingPolicy)(nil),                   // 24: pilab.network.v2.TeamingPolicy
	(*wrapperspb.StringValue)(nil),          // 25: google.protobuf.StringValue
	(*emptypb.Empty)(nil),                   // 26: google.protobuf.Empty
}
var file_pilab_network_v2_dvs_service_proto_depIdxs = []int32{
	22, // 0: pilab.network.v2.DistributedSwitch.status:type_name -> pilab.network.v2.DVSStatus
	16, // 1: pilab.network.v2.DistributedSwitch.metadata:type_name -> pilab.network.v2.DistributedSwitch.MetadataEntry
	23, // 2: pilab.network.v2.DistributedSwitch.created_at:type_name -> google.protobuf.Timestamp
	23, // 3: pilab.network.v2.DistributedSwitch.updated_at:type_name -> google.protobuf.Timestamp
	24, // 4: pilab.network.v2.PortGroup.teaming_policy:type_name -> pilab.network.v2.TeamingPolicy
	17, // 5: pilab.network.v2.PortGroup.metadata:type_name -> pilab.network.v2.PortGroup.MetadataEntry
	23, // 6: pilab.network.v2.PortGroup.created_at:type_name -> google.protobuf.Timestamp
	23, // 7: pilab.network.v2.PortGroup.updated_at:type_name -> google.protobuf.Timestamp
	18, // 8: pilab.network.v2.CreateDistributedSwitchRequest.metadata:type_name -> pilab.network.v2.CreateDistributedSwitchRequest.MetadataEntry
	25, // 9: pilab.network.v2.ListDistributedSwitchesRequest.cursor:type_name -> google.protobuf.StringValue
	0,  // 10: pilab.network.v2.ListDistributedSwitchesResponse.switches:type_name -> pilab.network.v2.DistributedSwitch
	25, // 11: pilab.network.v2.ListDistributedSwitchesResponse.next_cursor:type_name -> google.protobuf.StringValue
	19, // 12: pilab.network.v2.UpdateDistributedSwitchRequest.metadata:type_name -> pilab.network.v2.UpdateDistributedSwitchRequest.MetadataEntry
	24, // 13: pilab.network.v2.CreatePortGroupRequest.teaming_policy:type_name -> pilab.network.v2.TeamingPolicy
	20, // 14: pilab.network.v2.CreatePortGroupRequest.metadata:type_name -> pilab.network.v2.CreatePortGroupRequest.MetadataEntry
	25, // 15: pilab.network.v2.ListPortGroupsRequest.cursor:type_name -> google.protobuf.StringValue
	1,  // 16: pilab.network.v2.ListPortGroupsResponse.port_groups:type_name -> pilab.network.v2.PortGroup
	25, // 17: pilab.network.v2.ListPortGroupsResponse.next_cursor:type_name -> google.protobuf.StringValue
	24, // 18: pilab.network.v2.UpdatePortGroupRequest.teaming_policy:type_name -> pilab.network.v2.TeamingPolicy
	21, // 19: pilab.network.v2.UpdatePortGroupRequest.metadata:type_name -> pilab.network.v2.UpdatePortGroupRequest.MetadataEntry
	2,  // 20: pilab.network.v2.DVSService.CreateDistributedSwitch:input_type -> pilab.network.v2.CreateDistributedSwitchRequest
	3,  // 21: pilab.network.v2.DVSService.GetDistributedSwitch:input_type -> pilab.network.v2.GetDistributedSwitchRequest
	4,  // 22: pilab.network.v2.DVSService.ListDistributedSwitches:input_type -> pilab.network.v2.ListDistributedSwitchesRequest
	6,  // 23: pilab.network.v2.DVSService.UpdateDistributedSwitch:input_type -> pilab.network.v2.UpdateDistributedSwitchRequest
	7,  // 24: pilab.network.v2.DVSService.DeleteDistributedSwitch:input_type -> pilab.network.v2.DeleteDistributedSwitchRequest
	8,  // 25: pilab.network.v2.DVSService.AddHostToDVS:input_type -> pilab.network.v2.AddHostToDVSRequest
	9,  // 26: pilab.network.v2.DVSService.RemoveHostFromDVS:input_type -> pilab.network.v2.RemoveHostFromDVSRequest
	10, // 27: pilab.network.v2.DVSService.CreatePortGroup:input_type -> pilab.network.v2.CreatePortGroupRequest
	11, // 28: pilab.network.v2.DVSService.GetPortGroup:input_type -> pilab.network.v2.GetPortGroupRequest
	12, // 29: pilab.network.v2.DVSService.ListPortGroups:input_type -> pilab.network.v2.ListPortGroupsRequest
	14, // 30: pilab.network.v2.DVSService.UpdatePortGroup:input_type -> pilab.network.v2.UpdatePortGroupRequest
	15, // 31: pilab.network.v2.DVSService.DeletePortGroup:input_type -> pilab.network.v2.DeletePortGroupRequest
	0,  // 32: pilab.network.v2.DVSService.CreateDistributedSwitch:output_type -> pilab.network.v2.DistributedSwitch
	0,  // 33: pilab.network.v2.DVSService.GetDistributedSwitch:output_type -> pilab.network.v2.DistributedSwitch
	5,  // 34: pilab.network.v2.DVSService.ListDistributedSwitches:output_type -> pilab.network.v2.ListDistributedSwitchesResponse
	0,  // 35: pilab.network.v2.DVSService.UpdateDistributedSwitch:output_type -> pilab.network.v2.DistributedSwitch
	26, // 36: pilab.network.v2.DVSService.DeleteDistributedSwitch:output_type -> google.protobuf.Empty
	26, // 37: pilab.network.v2.DVSService.AddHostToDVS:output_type -> google.protobuf.Empty
	26, // 38: pilab.network.v2.DVSService.RemoveHostFromDVS:output_type -> google.protobuf.Empty
	1,  // 39: pilab.network.v2.DVSService.CreatePortGroup:output_type -> pilab.network.v2.PortGroup
	1,  // 40: pilab.network.v2.DVSService.GetPortGroup:output_type -> pilab.network.v2.PortGroup
	13, // 41: pilab.network.v2.DVSService.ListPortGroups:output_type -> pilab.network.v2.ListPortGroupsResponse
	1,  // 42: pilab.network.v2.DVSService.UpdatePortGroup:output_type -> pilab.network.v2.PortGroup
	26, // 43: pilab.network.v2.DVSService.DeletePortGroup:output_type -> google.protobuf.Empty
	32, // [32:44] is the sub-list for method output_type
	20, // [20:32] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_pilab_network_v2_dvs_service_proto_init() }
func file_pilab_network_v2_dvs_service_proto_init() {
	if File_pilab_network_v2_dvs_service_proto != nil {
		return
	}
	file_pilab_network_v2_network_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pilab_network_v2_dvs_service_proto_rawDesc), len(file_pilab_network_v2_dvs_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pilab_network_v2_dvs_service_proto_goTypes,
		DependencyIndexes: file_pilab_network_v2_dvs_service_proto_depIdxs,
		MessageInfos:      file_pilab_network_v2_dvs_service_proto_msgTypes,
	}.Build()
	File_pilab_network_v2_dvs_service_proto = out.File
	file_pilab_network_v2_dvs_service_proto_goTypes = nil
	file_pilab_network_v2_dvs_service_proto_depIdxs = nil
}
