// Package network provides virtual networking services including networks,
// ports, VLAN/VXLAN management, IPAM, QoS, security, DVS, and statistics.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pilab/network/v2/network_common.proto

package networkv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Protocol int32

const (
	Protocol_PROTOCOL_UNSPECIFIED Protocol = 0
	Protocol_PROTOCOL_ALL         Protocol = 1
	Protocol_PROTOCOL_TCP         Protocol = 2
	Protocol_PROTOCOL_UDP         Protocol = 3
	Protocol_PROTOCOL_ICMP        Protocol = 4
	Protocol_PROTOCOL_ICMPV6      Protocol = 5
	Protocol_PROTOCOL_SCTP        Protocol = 6
	Protocol_PROTOCOL_GRE         Protocol = 7
	Protocol_PROTOCOL_VXLAN       Protocol = 8
	Protocol_PROTOCOL_ESP         Protocol = 9
	Protocol_PROTOCOL_AH          Protocol = 10
)

// Enum value maps for Protocol.
var (
	Protocol_name = map[int32]string{
		0:  "PROTOCOL_UNSPECIFIED",
		1:  "PROTOCOL_ALL",
		2:  "PROTOCOL_TCP",
		3:  "PROTOCOL_UDP",
		4:  "PROTOCOL_ICMP",
		5:  "PROTOCOL_ICMPV6",
		6:  "PROTOCOL_SCTP",
		7:  "PROTOCOL_GRE",
		8:  "PROTOCOL_VXLAN",
		9:  "PROTOCOL_ESP",
		10: "PROTOCOL_AH",
	}
	Protocol_value = map[string]int32{
		"PROTOCOL_UNSPECIFIED": 0,
		"PROTOCOL_ALL":         1,
		"PROTOCOL_TCP":         2,
		"PROTOCOL_UDP":         3,
		"PROTOCOL_ICMP":        4,
		"PROTOCOL_ICMPV6":      5,
		"PROTOCOL_SCTP":        6,
		"PROTOCOL_GRE":         7,
		"PROTOCOL_VXLAN":       8,
		"PROTOCOL_ESP":         9,
		"PROTOCOL_AH":          10,
	}
)

func (x Protocol) Enum() *Protocol {
	p := new(Protocol)
	*p = x
	return p
}

func (x Protocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Protocol) Descriptor() protoreflect.EnumDescriptor {
	return file_pilab_network_v2_network_common_proto_enumTypes[0].Descriptor()
}

func (Protocol) Type() protoreflect.EnumType {
	return &file_pilab_network_v2_network_common_proto_enumTypes[0]
}

func (x Protocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Protocol.Descriptor instead.
func (Protocol) EnumDescriptor() ([]byte, []int) {
	return file_pilab_network_v2_network_common_proto_rawDescGZIP(), []int{0}
}

type ACNAction int32

const (
	ACNAction_ACN_ACTION_UNSPECIFIED ACNAction = 0
	ACNAction_ACN_ACTION_ALLOW       ACNAction = 1
	ACNAction_ACN_ACTION_DROP        ACNAction = 2
	ACNAction_ACN_ACTION_REJECT      ACNAction = 3
	ACNAction_ACN_ACTION_LOG         ACNAction = 4
)

// Enum value maps for ACNAction.
var (
	ACNAction_name = map[int32]string{
		0: "ACN_ACTION_UNSPECIFIED",
		1: "ACN_ACTION_ALLOW",
		2: "ACN_ACTION_DROP",
		3: "ACN_ACTION_REJECT",
		4: "ACN_ACTION_LOG",
	}
	ACNAction_value = map[string]int32{
		"ACN_ACTION_UNSPECIFIED": 0,
		"ACN_ACTION_ALLOW":       1,
		"ACN_ACTION_DROP":        2,
		"ACN_ACTION_REJECT":      3,
		"ACN_ACTION_LOG":         4,
	}
)

func (x ACNAction) Enum() *ACNAction {
	p := new(ACNAction)
	*p = x
	return p
}

func (x ACNAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ACNAction) Descriptor() protoreflect.EnumDescriptor {
	return file_pilab_network_v2_network_common_proto_enumTypes[1].Descriptor()
}

func (ACNAction) Type() protoreflect.EnumType {
	return &file_pilab_network_v2_network_common_proto_enumTypes[1]
}

func (x ACNAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ACNAction.Descriptor instead.
func (ACNAction) EnumDescriptor() ([]byte, []int) {
	return file_pilab_network_v2_network_common_proto_rawDescGZIP(), []int{1}
}

type Direction int32

const (
	Direction_DIRECTION_UNSPECIFIED Direction = 0
	Direction_DIRECTION_INGRESS     Direction = 1
	Direction_DIRECTION_EGRESS      Direction = 2
	Direction_DIRECTION_BOTH        Direction = 3
)

// Enum value maps for Direction.
var (
	Direction_name = map[int32]string{
		0: "DIRECTION_UNSPECIFIED",
		1: "DIRECTION_INGRESS",
		2: "DIRECTION_EGRESS",
		3: "DIRECTION_BOTH",
	}
	Direction_value = map[string]int32{
		"DIRECTION_UNSPECIFIED": 0,
		"DIRECTION_INGRESS":     1,
		"DIRECTION_EGRESS":      2,
		"DIRECTION_BOTH":        3,
	}
)

func (x Direction) Enum() *Direction {
	p := new(Direction)
	*p = x
	return p
}

func (x Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_pilab_network_v2_network_common_proto_enumTypes[2].Descriptor()
}

func (Direction) Type() protoreflect.EnumType {
	return &file_pilab_network_v2_network_common_proto_enumTypes[2]
}

func (x Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Direction.Descriptor instead.
func (Direction) EnumDescriptor() ([]byte, []int) {
	return file_pilab_network_v2_network_common_proto_rawDescGZIP(), []int{2}
}

type NetworkType int32

const (
	NetworkType_NETWORK_TYPE_UNSPECIFIED NetworkType = 0
	NetworkType_NETWORK_TYPE_VLAN        NetworkType = 1
	NetworkType_NETWORK_TYPE_VXLAN       NetworkType = 2
	NetworkType_NETWORK_TYPE_BRIDGE      NetworkType = 3
	NetworkType_NETWORK_TYPE_FLAT        NetworkType = 4
	NetworkType_NETWORK_TYPE_GENEVE      NetworkType = 5
)

// Enum value maps for NetworkType.
var (
	NetworkType_name = map[int32]string{
		0: "NETWORK_TYPE_UNSPECIFIED",
		1: "NETWORK_TYPE_VLAN",
		2: "NETWORK_TYPE_VXLAN",
		3: "NETWORK_TYPE_BRIDGE",
		4: "NETWORK_TYPE_FLAT",
		5: "NETWORK_TYPE_GENEVE",
	}
	NetworkType_value = map[string]int32{
		"NETWORK_TYPE_UNSPECIFIED": 0,
		"NETWORK_TYPE_VLAN":        1,
		"NETWORK_TYPE_VXLAN":       2,
		"NETWORK_TYPE_BRIDGE":      3,
		"NETWORK_TYPE_FLAT":        4,
		"NETWORK_TYPE_GENEVE":      5,
	}
)

func (x NetworkType) Enum() *NetworkType {
	p := new(NetworkType)
	*p = x
	return p
}

func (x NetworkType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NetworkType) Descriptor() protoreflect.EnumDescriptor {
	return file_pilab_network_v2_network_common_proto_enumTypes[3].Descriptor()
}

func (NetworkType) Type() protoreflect.EnumType {
	return &file_pilab_network_v2_network_common_proto_enumTypes[3]
}

func (x NetworkType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NetworkType.Descriptor instead.
func (NetworkType) EnumDescriptor() ([]byte, []int) {
	return file_pilab_network_v2_network_common_proto_rawDescGZIP(), []int{3}
}

type NetworkStatus int32

const (
	NetworkStatus_NETWORK_STATUS_UNSPECIFIED NetworkStatus = 0
	NetworkStatus_NETWORK_STATUS_PENDING     NetworkStatus = 1
	NetworkStatus_NETWORK_STATUS_ACTIVE      NetworkStatus = 2
	NetworkStatus_NETWORK_STATUS_DEGRADED    NetworkStatus = 3
	NetworkStatus_NETWORK_STATUS_ERROR       NetworkStatus = 4
)

// Enum value maps for NetworkStatus.
var (
	NetworkStatus_name = map[int32]string{
		0: "NETWORK_STATUS_UNSPECIFIED",
		1: "NETWORK_STATUS_PENDING",
		2: "NETWORK_STATUS_ACTIVE",
		3: "NETWORK_STATUS_DEGRADED",
		4: "NETWORK_STATUS_ERROR",
	}
	NetworkStatus_value = map[string]int32{
		"NETWORK_STATUS_UNSPECIFIED": 0,
		"NETWORK_STATUS_PENDING":     1,
		"NETWORK_STATUS_ACTIVE":      2,
		"NETWORK_STATUS_DEGRADED":    3,
		"NETWORK_STATUS_ERROR":       4,
	}
)

func (x NetworkStatus) Enum() *NetworkStatus {
	p := new(NetworkStatus)
	*p = x
	return p
}

func (x NetworkStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NetworkStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pilab_network_v2_network_common_proto_enumTypes[4].Descriptor()
}

func (NetworkStatus) Type() protoreflect.EnumType {
	return &file_pilab_network_v2_network_common_proto_enumTypes[4]
}

func (x NetworkStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NetworkStatus.Descriptor instead.
func (NetworkStatus) EnumDescriptor() ([]byte, []int) {
	return file_pilab_network_v2_network_common_proto_rawDescGZIP(), []int{4}
}

type NetworkRole int32

const (
	NetworkRole_NETWORK_ROLE_UNSPECIFIED NetworkRole = 0
	NetworkRole_NETWORK_ROLE_VMS         NetworkRole = 1
	NetworkRole_NETWORK_ROLE_VMOTION     NetworkRole = 2
	NetworkRole_NETWORK_ROLE_UPLINK      NetworkRole = 3
	NetworkRole_NETWORK_ROLE_STORAGE     NetworkRole = 4
	NetworkRole_NETWORK_ROLE_MGMT        NetworkRole = 5
)

// Enum value maps for NetworkRole.
var (
	NetworkRole_name = map[int32]string{
		0: "NETWORK_ROLE_UNSPECIFIED",
		1: "NETWORK_ROLE_VMS",
		2: "NETWORK_ROLE_VMOTION",
		3: "NETWORK_ROLE_UPLINK",
		4: "NETWORK_ROLE_STORAGE",
		5: "NETWORK_ROLE_MGMT",
	}
	NetworkRole_value = map[string]int32{
		"NETWORK_ROLE_UNSPECIFIED": 0,
		"NETWORK_ROLE_VMS":         1,
		"NETWORK_ROLE_VMOTION":     2,
		"NETWORK_ROLE_UPLINK":      3,
		"NETWORK_ROLE_STORAGE":     4,
		"NETWORK_ROLE_MGMT":        5,
	}
)

func (x NetworkRole) Enum() *NetworkRole {
	p := new(NetworkRole)
	*p = x
	return p
}

func (x NetworkRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NetworkRole) Descriptor() protoreflect.EnumDescriptor {
	return file_pilab_network_v2_network_common_proto_enumTypes[5].Descriptor()
}

func (NetworkRole) Type() protoreflect.EnumType {
	return &file_pilab_network_v2_network_common_proto_enumTypes[5]
}

func (x NetworkRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NetworkRole.Descriptor instead.
func (NetworkRole) EnumDescriptor() ([]byte, []int) {
	return file_pilab_network_v2_network_common_proto_rawDescGZIP(), []int{5}
}

type PortType int32

const (
	PortType_PORT_TYPE_UNSPECIFIED       PortType = 0
	PortType_PORT_TYPE_NORMAL            PortType = 1
	PortType_PORT_TYPE_DIRECT            PortType = 2
	PortType_PORT_TYPE_ALLOW_PROMISCUOUS PortType = 3
)

// Enum value maps for PortType.
var (
	PortType_name = map[int32]string{
		0: "PORT_TYPE_UNSPECIFIED",
		1: "PORT_TYPE_NORMAL",
		2: "PORT_TYPE_DIRECT",
		3: "PORT_TYPE_ALLOW_PROMISCUOUS",
	}
	PortType_value = map[string]int32{
		"PORT_TYPE_UNSPECIFIED":       0,
		"PORT_TYPE_NORMAL":            1,
		"PORT_TYPE_DIRECT":            2,
		"PORT_TYPE_ALLOW_PROMISCUOUS": 3,
	}
)

func (x PortType) Enum() *PortType {
	p := new(PortType)
	*p = x
	return p
}

func (x PortType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PortType) Descriptor() protoreflect.EnumDescriptor {
	return file_pilab_network_v2_network_common_proto_enumTypes[6].Descriptor()
}

func (PortType) Type() protoreflect.EnumType {
	return &file_pilab_network_v2_network_common_proto_enumTypes[6]
}

func (x PortType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PortType.Descriptor instead.
func (PortType) EnumDescriptor() ([]byte, []int) {
	return file_pilab_network_v2_network_common_proto_rawDescGZIP(), []int{6}
}

type PortStatus int32

const (
	PortStatus_PORT_STATUS_UNSPECIFIED PortStatus = 0
	PortStatus_PORT_STATUS_DOWN        PortStatus = 1
	PortStatus_PORT_STATUS_UP          PortStatus = 2
	PortStatus_PORT_STATUS_ERROR       PortStatus = 3
)

// Enum value maps for PortStatus.
var (
	PortStatus_name = map[int32]string{
		0: "PORT_STATUS_UNSPECIFIED",
		1: "PORT_STATUS_DOWN",
		2: "PORT_STATUS_UP",
		3: "PORT_STATUS_ERROR",
	}
	PortStatus_value = map[string]int32{
		"PORT_STATUS_UNSPECIFIED": 0,
		"PORT_STATUS_DOWN":        1,
		"PORT_STATUS_UP":          2,
		"PORT_STATUS_ERROR":       3,
	}
)

func (x PortStatus) Enum() *PortStatus {
	p := new(PortStatus)
	*p = x
	return p
}

func (x PortStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PortStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pilab_network_v2_network_common_proto_enumTypes[7].Descriptor()
}

func (PortStatus) Type() protoreflect.EnumType {
	return &file_pilab_network_v2_network_common_proto_enumTypes[7]
}

func (x PortStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PortStatus.Descriptor instead.
func (PortStatus) EnumDescriptor() ([]byte, []int) {
	return file_pilab_network_v2_network_common_proto_rawDescGZIP(), []int{7}
}

type VirtualCloudType int32

const (
	VirtualCloudType_VIRTUAL_CLOUD_TYPE_UNSPECIFIED VirtualCloudType = 0
	VirtualCloudType_VIRTUAL_CLOUD_TYPE_ISOLATED    VirtualCloudType = 1
	VirtualCloudType_VIRTUAL_CLOUD_TYPE_INTERNAL    VirtualCloudType = 2
	VirtualCloudType_VIRTUAL_CLOUD_TYPE_EXTERNAL    VirtualCloudType = 3
	VirtualCloudType_VIRTUAL_CLOUD_TYPE_ROUTED      VirtualCloudType = 4
)

// Enum value maps for VirtualCloudType.
var (
	VirtualCloudType_name = map[int32]string{
		0: "VIRTUAL_CLOUD_TYPE_UNSPECIFIED",
		1: "VIRTUAL_CLOUD_TYPE_ISOLATED",
		2: "VIRTUAL_CLOUD_TYPE_INTERNAL",
		3: "VIRTUAL_CLOUD_TYPE_EXTERNAL",
		4: "VIRTUAL_CLOUD_TYPE_ROUTED",
	}
	VirtualCloudType_value = map[string]int32{
		"VIRTUAL_CLOUD_TYPE_UNSPECIFIED": 0,
		"VIRTUAL_CLOUD_TYPE_ISOLATED":    1,
		"VIRTUAL_CLOUD_TYPE_INTERNAL":    2,
		"VIRTUAL_CLOUD_TYPE_EXTERNAL":    3,
		"VIRTUAL_CLOUD_TYPE_ROUTED":      4,
	}
)

func (x VirtualCloudType) Enum() *VirtualCloudType {
	p := new(VirtualCloudType)
	*p = x
	return p
}

func (x VirtualCloudType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VirtualCloudType) Descriptor() protoreflect.EnumDescriptor {
	return file_pilab_network_v2_network_common_proto_enumTypes[8].Descriptor()
}

func (VirtualCloudType) Type() protoreflect.EnumType {
	return &file_pilab_network_v2_network_common_proto_enumTypes[8]
}

func (x VirtualCloudType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VirtualCloudType.Descriptor instead.
func (VirtualCloudType) EnumDescriptor() ([]byte, []int) {
	return file_pilab_network_v2_network_common_proto_rawDescGZIP(), []int{8}
}

type VirtualCloudStatus int32

const (
	VirtualCloudStatus_VIRTUAL_CLOUD_STATUS_UNSPECIFIED VirtualCloudStatus = 0
	VirtualCloudStatus_VIRTUAL_CLOUD_STATUS_PENDING     VirtualCloudStatus = 1
	VirtualCloudStatus_VIRTUAL_CLOUD_STATUS_ACTIVE      VirtualCloudStatus = 2
	VirtualCloudStatus_VIRTUAL_CLOUD_STATUS_ERROR       VirtualCloudStatus = 3
)

// Enum value maps for VirtualCloudStatus.
var (
	VirtualCloudStatus_name = map[int32]string{
		0: "VIRTUAL_CLOUD_STATUS_UNSPECIFIED",
		1: "VIRTUAL_CLOUD_STATUS_PENDING",
		2: "VIRTUAL_CLOUD_STATUS_ACTIVE",
		3: "VIRTUAL_CLOUD_STATUS_ERROR",
	}
	VirtualCloudStatus_value = map[string]int32{
		"VIRTUAL_CLOUD_STATUS_UNSPECIFIED": 0,
		"VIRTUAL_CLOUD_STATUS_PENDING":     1,
		"VIRTUAL_CLOUD_STATUS_ACTIVE":      2,
		"VIRTUAL_CLOUD_STATUS_ERROR":       3,
	}
)

func (x VirtualCloudStatus) Enum() *VirtualCloudStatus {
	p := new(VirtualCloudStatus)
	*p = x
	return p
}

func (x VirtualCloudStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VirtualCloudStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pilab_network_v2_network_common_proto_enumTypes[9].Descriptor()
}

func (VirtualCloudStatus) Type() protoreflect.EnumType {
	return &file_pilab_network_v2_network_common_proto_enumTypes[9]
}

func (x VirtualCloudStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VirtualCloudStatus.Descriptor instead.
func (VirtualCloudStatus) EnumDescriptor() ([]byte, []int) {
	return file_pilab_network_v2_network_common_proto_rawDescGZIP(), []int{9}
}

type PriorityClass int32

const (
	PriorityClass_PRIORITY_CLASS_UNSPECIFIED PriorityClass = 0
	PriorityClass_PRIORITY_CLASS_BEST_EFFORT PriorityClass = 1
	PriorityClass_PRIORITY_CLASS_LOW         PriorityClass = 2
	PriorityClass_PRIORITY_CLASS_NORMAL      PriorityClass = 3
	PriorityClass_PRIORITY_CLASS_HIGH        PriorityClass = 4
	PriorityClass_PRIORITY_CLASS_CRITICAL    PriorityClass = 5
)

// Enum value maps for PriorityClass.
var (
	PriorityClass_name = map[int32]string{
		0: "PRIORITY_CLASS_UNSPECIFIED",
		1: "PRIORITY_CLASS_BEST_EFFORT",
		2: "PRIORITY_CLASS_LOW",
		3: "PRIORITY_CLASS_NORMAL",
		4: "PRIORITY_CLASS_HIGH",
		5: "PRIORITY_CLASS_CRITICAL",
	}
	PriorityClass_value = map[string]int32{
		"PRIORITY_CLASS_UNSPECIFIED": 0,
		"PRIORITY_CLASS_BEST_EFFORT": 1,
		"PRIORITY_CLASS_LOW":         2,
		"PRIORITY_CLASS_NORMAL":      3,
		"PRIORITY_CLASS_HIGH":        4,
		"PRIORITY_CLASS_CRITICAL":    5,
	}
)

func (x PriorityClass) Enum() *PriorityClass {
	p := new(PriorityClass)
	*p = x
	return p
}

func (x PriorityClass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PriorityClass) Descriptor() protoreflect.EnumDescriptor {
	return file_pilab_network_v2_network_common_proto_enumTypes[10].Descriptor()
}

func (PriorityClass) Type() protoreflect.EnumType {
	return &file_pilab_network_v2_network_common_proto_enumTypes[10]
}

func (x PriorityClass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PriorityClass.Descriptor instead.
func (PriorityClass) EnumDescriptor() ([]byte, []int) {
	return file_pilab_network_v2_network_common_proto_rawDescGZIP(), []int{10}
}

type QoSAlgorithm int32

const (
	QoSAlgorithm_QOS_ALGORITHM_UNSPECIFIED QoSAlgorithm = 0
	QoSAlgorithm_QOS_ALGORITHM_SFQ         QoSAlgorithm = 1
	QoSAlgorithm_QOS_ALGORITHM_FQ_CODEL    QoSAlgorithm = 2
	QoSAlgorithm_QOS_ALGORITHM_TBF         QoSAlgorithm = 3
	QoSAlgorithm_QOS_ALGORITHM_HTB         QoSAlgorithm = 4
	QoSAlgorithm_QOS_ALGORITHM_PRIO        QoSAlgorithm = 5
)

// Enum value maps for QoSAlgorithm.
var (
	QoSAlgorithm_name = map[int32]string{
		0: "QOS_ALGORITHM_UNSPECIFIED",
		1: "QOS_ALGORITHM_SFQ",
		2: "QOS_ALGORITHM_FQ_CODEL",
		3: "QOS_ALGORITHM_TBF",
		4: "QOS_ALGORITHM_HTB",
		5: "QOS_ALGORITHM_PRIO",
	}
	QoSAlgorithm_value = map[string]int32{
		"QOS_ALGORITHM_UNSPECIFIED": 0,
		"QOS_ALGORITHM_SFQ":         1,
		"QOS_ALGORITHM_FQ_CODEL":    2,
		"QOS_ALGORITHM_TBF":         3,
		"QOS_ALGORITHM_HTB":         4,
		"QOS_ALGORITHM_PRIO":        5,
	}
)

func (x QoSAlgorithm) Enum() *QoSAlgorithm {
	p := new(QoSAlgorithm)
	*p = x
	return p
}

func (x QoSAlgorithm) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QoSAlgorithm) Descriptor() protoreflect.EnumDescriptor {
	return file_pilab_network_v2_network_common_proto_enumTypes[11].Descriptor()
}

func (QoSAlgorithm) Type() protoreflect.EnumType {
	return &file_pilab_network_v2_network_common_proto_enumTypes[11]
}

func (x QoSAlgorithm) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QoSAlgorithm.Descriptor instead.
func (QoSAlgorithm) EnumDescriptor() ([]byte, []int) {
	return file_pilab_network_v2_network_common_proto_rawDescGZIP(), []int{11}
}

type RateLimitUnit int32

const (
	RateLimitUnit_RATE_LIMIT_UNIT_UNSPECIFIED RateLimitUnit = 0
	RateLimitUnit_RATE_LIMIT_UNIT_BPS         RateLimitUnit = 1
	RateLimitUnit_RATE_LIMIT_UNIT_KBPS        RateLimitUnit = 2
	RateLimitUnit_RATE_LIMIT_UNIT_MBPS        RateLimitUnit = 3
	RateLimitUnit_RATE_LIMIT_UNIT_GBPS        RateLimitUnit = 4
	RateLimitUnit_RATE_LIMIT_UNIT_PPS         RateLimitUnit = 5
)

// Enum value maps for RateLimitUnit.
var (
	RateLimitUnit_name = map[int32]string{
		0: "RATE_LIMIT_UNIT_UNSPECIFIED",
		1: "RATE_LIMIT_UNIT_BPS",
		2: "RATE_LIMIT_UNIT_KBPS",
		3: "RATE_LIMIT_UNIT_MBPS",
		4: "RATE_LIMIT_UNIT_GBPS",
		5: "RATE_LIMIT_UNIT_PPS",
	}
	RateLimitUnit_value = map[string]int32{
		"RATE_LIMIT_UNIT_UNSPECIFIED": 0,
		"RATE_LIMIT_UNIT_BPS":         1,
		"RATE_LIMIT_UNIT_KBPS":        2,
		"RATE_LIMIT_UNIT_MBPS":        3,
		"RATE_LIMIT_UNIT_GBPS":        4,
		"RATE_LIMIT_UNIT_PPS":         5,
	}
)

func (x RateLimitUnit) Enum() *RateLimitUnit {
	p := new(RateLimitUnit)
	*p = x
	return p
}

func (x RateLimitUnit) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RateLimitUnit) Descriptor() protoreflect.EnumDescriptor {
	return file_pilab_network_v2_network_common_proto_enumTypes[12].Descriptor()
}

func (RateLimitUnit) Type() protoreflect.EnumType {
	return &file_pilab_network_v2_network_common_proto_enumTypes[12]
}

func (x RateLimitUnit) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RateLimitUnit.Descriptor instead.
func (RateLimitUnit) EnumDescriptor() ([]byte, []int) {
	return file_pilab_network_v2_network_common_proto_rawDescGZIP(), []int{12}
}

type ApplyTarget int32

const (
	ApplyTarget_APPLY_TARGET_UNSPECIFIED ApplyTarget = 0
	ApplyTarget_APPLY_TARGET_PORT        ApplyTarget = 1
	ApplyTarget_APPLY_TARGET_NETWORK     ApplyTarget = 2
)

// Enum value maps for ApplyTarget.
var (
	ApplyTarget_name = map[int32]string{
		0: "APPLY_TARGET_UNSPECIFIED",
		1: "APPLY_TARGET_PORT",
		2: "APPLY_TARGET_NETWORK",
	}
	ApplyTarget_value = map[string]int32{
		"APPLY_TARGET_UNSPECIFIED": 0,
		"APPLY_TARGET_PORT":        1,
		"APPLY_TARGET_NETWORK":     2,
	}
)

func (x ApplyTarget) Enum() *ApplyTarget {
	p := new(ApplyTarget)
	*p = x
	return p
}

func (x ApplyTarget) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ApplyTarget) Descriptor() protoreflect.EnumDescriptor {
	return file_pilab_network_v2_network_common_proto_enumTypes[13].Descriptor()
}

func (ApplyTarget) Type() protoreflect.EnumType {
	return &file_pilab_network_v2_network_common_proto_enumTypes[13]
}

func (x ApplyTarget) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ApplyTarget.Descriptor instead.
func (ApplyTarget) EnumDescriptor() ([]byte, []int) {
	return file_pilab_network_v2_network_common_proto_rawDescGZIP(), []int{13}
}

type AllocationMode int32

const (
	AllocationMode_ALLOCATION_MODE_UNSPECIFIED AllocationMode = 0
	AllocationMode_ALLOCATION_MODE_DHCP        AllocationMode = 1
	AllocationMode_ALLOCATION_MODE_STATIC      AllocationMode = 2
	AllocationMode_ALLOCATION_MODE_DYNAMIC     AllocationMode = 3
	AllocationMode_ALLOCATION_MODE_HYBRID      AllocationMode = 4
)

// Enum value maps for AllocationMode.
var (
	AllocationMode_name = map[int32]string{
		0: "ALLOCATION_MODE_UNSPECIFIED",
		1: "ALLOCATION_MODE_DHCP",
		2: "ALLOCATION_MODE_STATIC",
		3: "ALLOCATION_MODE_DYNAMIC",
		4: "ALLOCATION_MODE_HYBRID",
	}
	AllocationMode_value = map[string]int32{
		"ALLOCATION_MODE_UNSPECIFIED": 0,
		"ALLOCATION_MODE_DHCP":        1,
		"ALLOCATION_MODE_STATIC":      2,
		"ALLOCATION_MODE_DYNAMIC":     3,
		"ALLOCATION_MODE_HYBRID":      4,
	}
)

func (x AllocationMode) Enum() *AllocationMode {
	p := new(AllocationMode)
	*p = x
	return p
}

func (x AllocationMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AllocationMode) Descriptor() protoreflect.EnumDescriptor {
	return file_pilab_network_v2_network_common_proto_enumTypes[14].Descriptor()
}

func (AllocationMode) Type() protoreflect.EnumType {
	return &file_pilab_network_v2_network_common_proto_enumTypes[14]
}

func (x AllocationMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AllocationMode.Descriptor instead.
func (AllocationMode) EnumDescriptor() ([]byte, []int) {
	return file_pilab_network_v2_network_common_proto_rawDescGZIP(), []int{14}
}

type AllocationType int32

const (
	AllocationType_ALLOCATION_TYPE_UNSPECIFIED AllocationType = 0
	AllocationType_ALLOCATION_TYPE_DHCP        AllocationType = 1
	AllocationType_ALLOCATION_TYPE_STATIC      AllocationType = 2
	AllocationType_ALLOCATION_TYPE_FIP         AllocationType = 3
)

// Enum value maps for AllocationType.
var (
	AllocationType_name = map[int32]string{
		0: "ALLOCATION_TYPE_UNSPECIFIED",
		1: "ALLOCATION_TYPE_DHCP",
		2: "ALLOCATION_TYPE_STATIC",
		3: "ALLOCATION_TYPE_FIP",
	}
	AllocationType_value = map[string]int32{
		"ALLOCATION_TYPE_UNSPECIFIED": 0,
		"ALLOCATION_TYPE_DHCP":        1,
		"ALLOCATION_TYPE_STATIC":      2,
		"ALLOCATION_TYPE_FIP":         3,
	}
)

func (x AllocationType) Enum() *AllocationType {
	p := new(AllocationType)
	*p = x
	return p
}

func (x AllocationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AllocationType) Descriptor() protoreflect.EnumDescriptor {
	return file_pilab_network_v2_network_common_proto_enumTypes[15].Descriptor()
}

func (AllocationType) Type() protoreflect.EnumType {
	return &file_pilab_network_v2_network_common_proto_enumTypes[15]
}

func (x AllocationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AllocationType.Descriptor instead.
func (AllocationType) EnumDescriptor() ([]byte, []int) {
	return file_pilab_network_v2_network_common_proto_rawDescGZIP(), []int{15}
}

type PublicIPType int32

const (
	PublicIPType_PUBLIC_IP_TYPE_UNSPECIFIED PublicIPType = 0
	PublicIPType_PUBLIC_IP_TYPE_ELASTIC     PublicIPType = 1
	PublicIPType_PUBLIC_IP_TYPE_RESERVED    PublicIPType = 2
	PublicIPType_PUBLIC_IP_TYPE_BYOIP       PublicIPType = 3
)

// Enum value maps for PublicIPType.
var (
	PublicIPType_name = map[int32]string{
		0: "PUBLIC_IP_TYPE_UNSPECIFIED",
		1: "PUBLIC_IP_TYPE_ELASTIC",
		2: "PUBLIC_IP_TYPE_RESERVED",
		3: "PUBLIC_IP_TYPE_BYOIP",
	}
	PublicIPType_value = map[string]int32{
		"PUBLIC_IP_TYPE_UNSPECIFIED": 0,
		"PUBLIC_IP_TYPE_ELASTIC":     1,
		"PUBLIC_IP_TYPE_RESERVED":    2,
		"PUBLIC_IP_TYPE_BYOIP":       3,
	}
)

func (x PublicIPType) Enum() *PublicIPType {
	p := new(PublicIPType)
	*p = x
	return p
}

func (x PublicIPType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PublicIPType) Descriptor() protoreflect.EnumDescriptor {
	return file_pilab_network_v2_network_common_proto_enumTypes[16].Descriptor()
}

func (PublicIPType) Type() protoreflect.EnumType {
	return &file_pilab_network_v2_network_common_proto_enumTypes[16]
}

func (x PublicIPType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PublicIPType.Descriptor instead.
func (PublicIPType) EnumDescriptor() ([]byte, []int) {
	return file_pilab_network_v2_network_common_proto_rawDescGZIP(), []int{16}
}

type PublicIPStatus int32

const (
	PublicIPStatus_PUBLIC_IP_STATUS_UNSPECIFIED PublicIPStatus = 0
	PublicIPStatus_PUBLIC_IP_STATUS_AVAILABLE   PublicIPStatus = 1
	PublicIPStatus_PUBLIC_IP_STATUS_ASSOCIATED  PublicIPStatus = 2
	PublicIPStatus_PUBLIC_IP_STATUS_RESERVED    PublicIPStatus = 3
	PublicIPStatus_PUBLIC_IP_STATUS_RELEASING   PublicIPStatus = 4
)

// Enum value maps for PublicIPStatus.
var (
	PublicIPStatus_name = map[int32]string{
		0: "PUBLIC_IP_STATUS_UNSPECIFIED",
		1: "PUBLIC_IP_STATUS_AVAILABLE",
		2: "PUBLIC_IP_STATUS_ASSOCIATED",
		3: "PUBLIC_IP_STATUS_RESERVED",
		4: "PUBLIC_IP_STATUS_RELEASING",
	}
	PublicIPStatus_value = map[string]int32{
		"PUBLIC_IP_STATUS_UNSPECIFIED": 0,
		"PUBLIC_IP_STATUS_AVAILABLE":   1,
		"PUBLIC_IP_STATUS_ASSOCIATED":  2,
		"PUBLIC_IP_STATUS_RESERVED":    3,
		"PUBLIC_IP_STATUS_RELEASING":   4,
	}
)

func (x PublicIPStatus) Enum() *PublicIPStatus {
	p := new(PublicIPStatus)
	*p = x
	return p
}

func (x PublicIPStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PublicIPStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pilab_network_v2_network_common_proto_enumTypes[17].Descriptor()
}

func (PublicIPStatus) Type() protoreflect.EnumType {
	return &file_pilab_network_v2_network_common_proto_enumTypes[17]
}

func (x PublicIPStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PublicIPStatus.Descriptor instead.
func (PublicIPStatus) EnumDescriptor() ([]byte, []int) {
	return file_pilab_network_v2_network_common_proto_rawDescGZIP(), []int{17}
}

type FirewallState int32

const (
	FirewallState_FIREWALL_STATE_UNSPECIFIED FirewallState = 0
	FirewallState_FIREWALL_STATE_DISABLED    FirewallState = 1
	FirewallState_FIREWALL_STATE_ENABLED     FirewallState = 2
	FirewallState_FIREWALL_STATE_BYPASS      FirewallState = 3
)

// Enum value maps for FirewallState.
var (
	FirewallState_name = map[int32]string{
		0: "FIREWALL_STATE_UNSPECIFIED",
		1: "FIREWALL_STATE_DISABLED",
		2: "FIREWALL_STATE_ENABLED",
		3: "FIREWALL_STATE_BYPASS",
	}
	FirewallState_value = map[string]int32{
		"FIREWALL_STATE_UNSPECIFIED": 0,
		"FIREWALL_STATE_DISABLED":    1,
		"FIREWALL_STATE_ENABLED":     2,
		"FIREWALL_STATE_BYPASS":      3,
	}
)

func (x FirewallState) Enum() *FirewallState {
	p := new(FirewallState)
	*p = x
	return p
}

func (x FirewallState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FirewallState) Descriptor() protoreflect.EnumDescriptor {
	return file_pilab_network_v2_network_common_proto_enumTypes[18].Descriptor()
}

func (FirewallState) Type() protoreflect.EnumType {
	return &file_pilab_network_v2_network_common_proto_enumTypes[18]
}

func (x FirewallState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FirewallState.Descriptor instead.
func (FirewallState) EnumDescriptor() ([]byte, []int) {
	return file_pilab_network_v2_network_common_proto_rawDescGZIP(), []int{18}
}

type FirewallDirection int32

const (
	FirewallDirection_FIREWALL_DIRECTION_UNSPECIFIED FirewallDirection = 0
	FirewallDirection_FIREWALL_DIRECTION_INGRESS     FirewallDirection = 1
	FirewallDirection_FIREWALL_DIRECTION_EGRESS      FirewallDirection = 2
)

// Enum value maps for FirewallDirection.
var (
	FirewallDirection_name = map[int32]string{
		0: "FIREWALL_DIRECTION_UNSPECIFIED",
		1: "FIREWALL_DIRECTION_INGRESS",
		2: "FIREWALL_DIRECTION_EGRESS",
	}
	FirewallDirection_value = map[string]int32{
		"FIREWALL_DIRECTION_UNSPECIFIED": 0,
		"FIREWALL_DIRECTION_INGRESS":     1,
		"FIREWALL_DIRECTION_EGRESS":      2,
	}
)

func (x FirewallDirection) Enum() *FirewallDirection {
	p := new(FirewallDirection)
	*p = x
	return p
}

func (x FirewallDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FirewallDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_pilab_network_v2_network_common_proto_enumTypes[19].Descriptor()
}

func (FirewallDirection) Type() protoreflect.EnumType {
	return &file_pilab_network_v2_network_common_proto_enumTypes[19]
}

func (x FirewallDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FirewallDirection.Descriptor instead.
func (FirewallDirection) EnumDescriptor() ([]byte, []int) {
	return file_pilab_network_v2_network_common_proto_rawDescGZIP(), []int{19}
}

type DVSStatus int32

const (
	DVSStatus_DVS_STATUS_UNSPECIFIED DVSStatus = 0
	DVSStatus_DVS_STATUS_PENDING     DVSStatus = 1
	DVSStatus_DVS_STATUS_ACTIVE      DVSStatus = 2
	DVSStatus_DVS_STATUS_DEGRADED    DVSStatus = 3
	DVSStatus_DVS_STATUS_ERROR       DVSStatus = 4
)

// Enum value maps for DVSStatus.
var (
	DVSStatus_name = map[int32]string{
		0: "DVS_STATUS_UNSPECIFIED",
		1: "DVS_STATUS_PENDING",
		2: "DVS_STATUS_ACTIVE",
		3: "DVS_STATUS_DEGRADED",
		4: "DVS_STATUS_ERROR",
	}
	DVSStatus_value = map[string]int32{
		"DVS_STATUS_UNSPECIFIED": 0,
		"DVS_STATUS_PENDING":     1,
		"DVS_STATUS_ACTIVE":      2,
		"DVS_STATUS_DEGRADED":    3,
		"DVS_STATUS_ERROR":       4,
	}
)

func (x DVSStatus) Enum() *DVSStatus {
	p := new(DVSStatus)
	*p = x
	return p
}

func (x DVSStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DVSStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pilab_network_v2_network_common_proto_enumTypes[20].Descriptor()
}

func (DVSStatus) Type() protoreflect.EnumType {
	return &file_pilab_network_v2_network_common_proto_enumTypes[20]
}

func (x DVSStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DVSStatus.Descriptor instead.
func (DVSStatus) EnumDescriptor() ([]byte, []int) {
	return file_pilab_network_v2_network_common_proto_rawDescGZIP(), []int{20}
}

type TeamingMode int32

const (
	TeamingMode_TEAMING_MODE_UNSPECIFIED   TeamingMode = 0
	TeamingMode_TEAMING_MODE_ACTIVE_BACKUP TeamingMode = 1
	TeamingMode_TEAMING_MODE_LACP          TeamingMode = 2
	TeamingMode_TEAMING_MODE_SRC_DST_IP    TeamingMode = 3
	TeamingMode_TEAMING_MODE_SRC_DST_MAC   TeamingMode = 4
	TeamingMode_TEAMING_MODE_SRC_PORT      TeamingMode = 5
)

// Enum value maps for TeamingMode.
var (
	TeamingMode_name = map[int32]string{
		0: "TEAMING_MODE_UNSPECIFIED",
		1: "TEAMING_MODE_ACTIVE_BACKUP",
		2: "TEAMING_MODE_LACP",
		3: "TEAMING_MODE_SRC_DST_IP",
		4: "TEAMING_MODE_SRC_DST_MAC",
		5: "TEAMING_MODE_SRC_PORT",
	}
	TeamingMode_value = map[string]int32{
		"TEAMING_MODE_UNSPECIFIED":   0,
		"TEAMING_MODE_ACTIVE_BACKUP": 1,
		"TEAMING_MODE_LACP":          2,
		"TEAMING_MODE_SRC_DST_IP":    3,
		"TEAMING_MODE_SRC_DST_MAC":   4,
		"TEAMING_MODE_SRC_PORT":      5,
	}
)

func (x TeamingMode) Enum() *TeamingMode {
	p := new(TeamingMode)
	*p = x
	return p
}

func (x TeamingMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TeamingMode) Descriptor() protoreflect.EnumDescriptor {
	return file_pilab_network_v2_network_common_proto_enumTypes[21].Descriptor()
}

func (TeamingMode) Type() protoreflect.EnumType {
	return &file_pilab_network_v2_network_common_proto_enumTypes[21]
}

func (x TeamingMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TeamingMode.Descriptor instead.
func (TeamingMode) EnumDescriptor() ([]byte, []int) {
	return file_pilab_network_v2_network_common_proto_rawDescGZIP(), []int{21}
}

type FlowDirection int32

const (
	FlowDirection_FLOW_DIRECTION_UNSPECIFIED   FlowDirection = 0
	FlowDirection_FLOW_DIRECTION_INGRESS       FlowDirection = 1
	FlowDirection_FLOW_DIRECTION_EGRESS        FlowDirection = 2
	FlowDirection_FLOW_DIRECTION_BIDIRECTIONAL FlowDirection = 3
)

// Enum value maps for FlowDirection.
var (
	FlowDirection_name = map[int32]string{
		0: "FLOW_DIRECTION_UNSPECIFIED",
		1: "FLOW_DIRECTION_INGRESS",
		2: "FLOW_DIRECTION_EGRESS",
		3: "FLOW_DIRECTION_BIDIRECTIONAL",
	}
	FlowDirection_value = map[string]int32{
		"FLOW_DIRECTION_UNSPECIFIED":   0,
		"FLOW_DIRECTION_INGRESS":       1,
		"FLOW_DIRECTION_EGRESS":        2,
		"FLOW_DIRECTION_BIDIRECTIONAL": 3,
	}
)

func (x FlowDirection) Enum() *FlowDirection {
	p := new(FlowDirection)
	*p = x
	return p
}

func (x FlowDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FlowDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_pilab_network_v2_network_common_proto_enumTypes[22].Descriptor()
}

func (FlowDirection) Type() protoreflect.EnumType {
	return &file_pilab_network_v2_network_common_proto_enumTypes[22]
}

func (x FlowDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FlowDirection.Descriptor instead.
func (FlowDirection) EnumDescriptor() ([]byte, []int) {
	return file_pilab_network_v2_network_common_proto_rawDescGZIP(), []int{22}
}

type RateLimit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rate          int64                  `protobuf:"varint,1,opt,name=rate,proto3" json:"rate,omitempty"`
	Unit          RateLimitUnit          `protobuf:"varint,2,opt,name=unit,proto3,enum=pilab.network.v2.RateLimitUnit" json:"unit,omitempty"`
	Peak          int64                  `protobuf:"varint,3,opt,name=peak,proto3" json:"peak,omitempty"`
	Burst         int64                  `protobuf:"varint,4,opt,name=burst,proto3" json:"burst,omitempty"`
	MinBurst      int64                  `protobuf:"varint,5,opt,name=min_burst,json=minBurst,proto3" json:"min_burst,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateLimit) Reset() {
	*x = RateLimit{}
	mi := &file_pilab_network_v2_network_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateLimit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimit) ProtoMessage() {}

func (x *RateLimit) ProtoReflect() protoreflect.Message {
	mi := &file_pilab_network_v2_network_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLimit.ProtoReflect.Descriptor instead.
func (*RateLimit) Descriptor() ([]byte, []int) {
	return file_pilab_network_v2_network_common_proto_rawDescGZIP(), []int{0}
}

func (x *RateLimit) GetRate() int64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *RateLimit) GetUnit() RateLimitUnit {
	if x != nil {
		return x.Unit
	}
	return RateLimitUnit_RATE_LIMIT_UNIT_UNSPECIFIED
}

func (x *RateLimit) GetPeak() int64 {
	if x != nil {
		return x.Peak
	}
	return 0
}

func (x *RateLimit) GetBurst() int64 {
	if x != nil {
		return x.Burst
	}
	return 0
}

func (x *RateLimit) GetMinBurst() int64 {
	if x != nil {
		return x.MinBurst
	}
	return 0
}

type TeamingPolicy struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Mode           TeamingMode            `protobuf:"varint,1,opt,name=mode,proto3,enum=pilab.network.v2.TeamingMode" json:"mode,omitempty"`
	ActiveUplinks  []string               `protobuf:"bytes,2,rep,name=active_uplinks,json=activeUplinks,proto3" json:"active_uplinks,omitempty"`
	StandbyUplinks []string               `protobuf:"bytes,3,rep,name=standby_uplinks,json=standbyUplinks,proto3" json:"standby_uplinks,omitempty"`
	NotifySwitches bool                   `protobuf:"varint,4,opt,name=notify_switches,json=notifySwitches,proto3" json:"notify_switches,omitempty"`
	Failback       bool                   `protobuf:"varint,5,opt,name=failback,proto3" json:"failback,omitempty"`
	LoadBalance    int32                  `protobuf:"varint,6,opt,name=load_balance,json=loadBalance,proto3" json:"load_balance,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TeamingPolicy) Reset() {
	*x = TeamingPolicy{}
	mi := &file_pilab_network_v2_network_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeamingPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamingPolicy) ProtoMessage() {}

func (x *TeamingPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_pilab_network_v2_network_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamingPolicy.ProtoReflect.Descriptor instead.
func (*TeamingPolicy) Descriptor() ([]byte, []int) {
	return file_pilab_network_v2_network_common_proto_rawDescGZIP(), []int{1}
}

func (x *TeamingPolicy) GetMode() TeamingMode {
	if x != nil {
		return x.Mode
	}
	return TeamingMode_TEAMING_MODE_UNSPECIFIED
}

func (x *TeamingPolicy) GetActiveUplinks() []string {
	if x != nil {
		return x.ActiveUplinks
	}
	return nil
}

func (x *TeamingPolicy) GetStandbyUplinks() []string {
	if x != nil {
		return x.StandbyUplinks
	}
	return nil
}

func (x *TeamingPolicy) GetNotifySwitches() bool {
	if x != nil {
		return x.NotifySwitches
	}
	return false
}

func (x *TeamingPolicy) GetFailback() bool {
	if x != nil {
		return x.Failback
	}
	return false
}

func (x *TeamingPolicy) GetLoadBalance() int32 {
	if x != nil {
		return x.LoadBalance
	}
	return 0
}

var File_pilab_network_v2_network_common_proto protoreflect.FileDescriptor

const file_pilab_network_v2_network_common_proto_rawDesc = "" +
	"\n" +
	"%pilab/network/v2/network_common.proto\x12\x10pilab.network.v2\"\x9b\x01\n" +
	"\tRateLimit\x12\x12\n" +
	"\x04rate\x18\x01 \x01(\x03R\x04rate\x123\n" +
	"\x04unit\x18\x02 \x01(\x0e2\x1f.pilab.network.v2.RateLimitUnitR\x04unit\x12\x12\n" +
	"\x04peak\x18\x03 \x01(\x03R\x04peak\x12\x14\n" +
	"\x05burst\x18\x04 \x01(\x03R\x05burst\x12\x1b\n" +
	"\tmin_burst\x18\x05 \x01(\x03R\bminBurst\"\xfa\x01\n" +
	"\rTeamingPolicy\x121\n" +
	"\x04mode\x18\x01 \x01(\x0e2\x1d.pilab.network.v2.TeamingModeR\x04mode\x12%\n" +
	"\x0eactive_uplinks\x18\x02 \x03(\tR\ractiveUplinks\x12'\n" +
	"\x0fstandby_uplinks\x18\x03 \x03(\tR\x0estandbyUplinks\x12'\n" +
	"\x0fnotify_switches\x18\x04 \x01(\bR\x0enotifySwitches\x12\x1a\n" +
	"\bfailback\x18\x05 \x01(\bR\bfailback\x12!\n" +
	"\fload_balance\x18\x06 \x01(\x05R\vloadBalance*\xde\x01\n" +
	"\bProtocol\x12\x18\n" +
	"\x14PROTOCOL_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fPROTOCOL_ALL\x10\x01\x12\x10\n" +
	"\fPROTOCOL_TCP\x10\x02\x12\x10\n" +
	"\fPROTOCOL_UDP\x10\x03\x12\x11\n" +
	"\rPROTOCOL_ICMP\x10\x04\x12\x13\n" +
	"\x0fPROTOCOL_ICMPV6\x10\x05\x12\x11\n" +
	"\rPROTOCOL_SCTP\x10\x06\x12\x10\n" +
	"\fPROTOCOL_GRE\x10\a\x12\x12\n" +
	"\x0ePROTOCOL_VXLAN\x10\b\x12\x10\n" +
	"\fPROTOCOL_ESP\x10\t\x12\x0f\n" +
	"\vPROTOCOL_AH\x10\n" +
	"*}\n" +
	"\tACNAction\x12\x1a\n" +
	"\x16ACN_ACTION_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10ACN_ACTION_ALLOW\x10\x01\x12\x13\n" +
	"\x0fACN_ACTION_DROP\x10\x02\x12\x15\n" +
	"\x11ACN_ACTION_REJECT\x10\x03\x12\x12\n" +
	"\x0eACN_ACTION_LOG\x10\x04*g\n" +
	"\tDirection\x12\x19\n" +
	"\x15DIRECTION_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11DIRECTION_INGRESS\x10\x01\x12\x14\n" +
	"\x10DIRECTION_EGRESS\x10\x02\x12\x12\n" +
	"\x0eDIRECTION_BOTH\x10\x03*\xa3\x01\n" +
	"\vNetworkType\x12\x1c\n" +
	"\x18NETWORK_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11NETWORK_TYPE_VLAN\x10\x01\x12\x16\n" +
	"\x12NETWORK_TYPE_VXLAN\x10\x02\x12\x17\n" +
	"\x13NETWORK_TYPE_BRIDGE\x10\x03\x12\x15\n" +
	"\x11NETWORK_TYPE_FLAT\x10\x04\x12\x17\n" +
	"\x13NETWORK_TYPE_GENEVE\x10\x05*\x9d\x01\n" +
	"\rNetworkStatus\x12\x1e\n" +
	"\x1aNETWORK_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16NETWORK_STATUS_PENDING\x10\x01\x12\x19\n" +
	"\x15NETWORK_STATUS_ACTIVE\x10\x02\x12\x1b\n" +
	"\x17NETWORK_STATUS_DEGRADED\x10\x03\x12\x18\n" +
	"\x14NETWORK_STATUS_ERROR\x10\x04*\xa5\x01\n" +
	"\vNetworkRole\x12\x1c\n" +
	"\x18NETWORK_ROLE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10NETWORK_ROLE_VMS\x10\x01\x12\x18\n" +
	"\x14NETWORK_ROLE_VMOTION\x10\x02\x12\x17\n" +
	"\x13NETWORK_ROLE_UPLINK\x10\x03\x12\x18\n" +
	"\x14NETWORK_ROLE_STORAGE\x10\x04\x12\x15\n" +
	"\x11NETWORK_ROLE_MGMT\x10\x05*r\n" +
	"\bPortType\x12\x19\n" +
	"\x15PORT_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10PORT_TYPE_NORMAL\x10\x01\x12\x14\n" +
	"\x10PORT_TYPE_DIRECT\x10\x02\x12\x1f\n" +
	"\x1bPORT_TYPE_ALLOW_PROMISCUOUS\x10\x03*j\n" +
	"\n" +
	"PortStatus\x12\x1b\n" +
	"\x17PORT_STATUS_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10PORT_STATUS_DOWN\x10\x01\x12\x12\n" +
	"\x0ePORT_STATUS_UP\x10\x02\x12\x15\n" +
	"\x11PORT_STATUS_ERROR\x10\x03*\xb8\x01\n" +
	"\x10VirtualCloudType\x12\"\n" +
	"\x1eVIRTUAL_CLOUD_TYPE_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bVIRTUAL_CLOUD_TYPE_ISOLATED\x10\x01\x12\x1f\n" +
	"\x1bVIRTUAL_CLOUD_TYPE_INTERNAL\x10\x02\x12\x1f\n" +
	"\x1bVIRTUAL_CLOUD_TYPE_EXTERNAL\x10\x03\x12\x1d\n" +
	"\x19VIRTUAL_CLOUD_TYPE_ROUTED\x10\x04*\x9d\x01\n" +
	"\x12VirtualCloudStatus\x12$\n" +
	" VIRTUAL_CLOUD_STATUS_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cVIRTUAL_CLOUD_STATUS_PENDING\x10\x01\x12\x1f\n" +
	"\x1bVIRTUAL_CLOUD_STATUS_ACTIVE\x10\x02\x12\x1e\n" +
	"\x1aVIRTUAL_CLOUD_STATUS_ERROR\x10\x03*\xb8\x01\n" +
	"\rPriorityClass\x12\x1e\n" +
	"\x1aPRIORITY_CLASS_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aPRIORITY_CLASS_BEST_EFFORT\x10\x01\x12\x16\n" +
	"\x12PRIORITY_CLASS_LOW\x10\x02\x12\x19\n" +
	"\x15PRIORITY_CLASS_NORMAL\x10\x03\x12\x17\n" +
	"\x13PRIORITY_CLASS_HIGH\x10\x04\x12\x1b\n" +
	"\x17PRIORITY_CLASS_CRITICAL\x10\x05*\xa6\x01\n" +
	"\fQoSAlgorithm\x12\x1d\n" +
	"\x19QOS_ALGORITHM_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11QOS_ALGORITHM_SFQ\x10\x01\x12\x1a\n" +
	"\x16QOS_ALGORITHM_FQ_CODEL\x10\x02\x12\x15\n" +
	"\x11QOS_ALGORITHM_TBF\x10\x03\x12\x15\n" +
	"\x11QOS_ALGORITHM_HTB\x10\x04\x12\x16\n" +
	"\x12QOS_ALGORITHM_PRIO\x10\x05*\xb0\x01\n" +
	"\rRateLimitUnit\x12\x1f\n" +
	"\x1bRATE_LIMIT_UNIT_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13RATE_LIMIT_UNIT_BPS\x10\x01\x12\x18\n" +
	"\x14RATE_LIMIT_UNIT_KBPS\x10\x02\x12\x18\n" +
	"\x14RATE_LIMIT_UNIT_MBPS\x10\x03\x12\x18\n" +
	"\x14RATE_LIMIT_UNIT_GBPS\x10\x04\x12\x17\n" +
	"\x13RATE_LIMIT_UNIT_PPS\x10\x05*\\\n" +
	"\vApplyTarget\x12\x1c\n" +
	"\x18APPLY_TARGET_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11APPLY_TARGET_PORT\x10\x01\x12\x18\n" +
	"\x14APPLY_TARGET_NETWORK\x10\x02*\xa0\x01\n" +
	"\x0eAllocationMode\x12\x1f\n" +
	"\x1bALLOCATION_MODE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ALLOCATION_MODE_DHCP\x10\x01\x12\x1a\n" +
	"\x16ALLOCATION_MODE_STATIC\x10\x02\x12\x1b\n" +
	"\x17ALLOCATION_MODE_DYNAMIC\x10\x03\x12\x1a\n" +
	"\x16ALLOCATION_MODE_HYBRID\x10\x04*\x80\x01\n" +
	"\x0eAllocationType\x12\x1f\n" +
	"\x1bALLOCATION_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ALLOCATION_TYPE_DHCP\x10\x01\x12\x1a\n" +
	"\x16ALLOCATION_TYPE_STATIC\x10\x02\x12\x17\n" +
	"\x13ALLOCATION_TYPE_FIP\x10\x03*\x81\x01\n" +
	"\fPublicIPType\x12\x1e\n" +
	"\x1aPUBLIC_IP_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16PUBLIC_IP_TYPE_ELASTIC\x10\x01\x12\x1b\n" +
	"\x17PUBLIC_IP_TYPE_RESERVED\x10\x02\x12\x18\n" +
	"\x14PUBLIC_IP_TYPE_BYOIP\x10\x03*\xb2\x01\n" +
	"\x0ePublicIPStatus\x12 \n" +
	"\x1cPUBLIC_IP_STATUS_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aPUBLIC_IP_STATUS_AVAILABLE\x10\x01\x12\x1f\n" +
	"\x1bPUBLIC_IP_STATUS_ASSOCIATED\x10\x02\x12\x1d\n" +
	"\x19PUBLIC_IP_STATUS_RESERVED\x10\x03\x12\x1e\n" +
	"\x1aPUBLIC_IP_STATUS_RELEASING\x10\x04*\x83\x01\n" +
	"\rFirewallState\x12\x1e\n" +
	"\x1aFIREWALL_STATE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17FIREWALL_STATE_DISABLED\x10\x01\x12\x1a\n" +
	"\x16FIREWALL_STATE_ENABLED\x10\x02\x12\x19\n" +
	"\x15FIREWALL_STATE_BYPASS\x10\x03*v\n" +
	"\x11FirewallDirection\x12\"\n" +
	"\x1eFIREWALL_DIRECTION_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aFIREWALL_DIRECTION_INGRESS\x10\x01\x12\x1d\n" +
	"\x19FIREWALL_DIRECTION_EGRESS\x10\x02*\x85\x01\n" +
	"\tDVSStatus\x12\x1a\n" +
	"\x16DVS_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12DVS_STATUS_PENDING\x10\x01\x12\x15\n" +
	"\x11DVS_STATUS_ACTIVE\x10\x02\x12\x17\n" +
	"\x13DVS_STATUS_DEGRADED\x10\x03\x12\x14\n" +
	"\x10DVS_STATUS_ERROR\x10\x04*\xb8\x01\n" +
	"\vTeamingMode\x12\x1c\n" +
	"\x18TEAMING_MODE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aTEAMING_MODE_ACTIVE_BACKUP\x10\x01\x12\x15\n" +
	"\x11TEAMING_MODE_LACP\x10\x02\x12\x1b\n" +
	"\x17TEAMING_MODE_SRC_DST_IP\x10\x03\x12\x1c\n" +
	"\x18TEAMING_MODE_SRC_DST_MAC\x10\x04\x12\x19\n" +
	"\x15TEAMING_MODE_SRC_PORT\x10\x05*\x88\x01\n" +
	"\rFlowDirection\x12\x1e\n" +
	"\x1aFLOW_DIRECTION_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16FLOW_DIRECTION_INGRESS\x10\x01\x12\x19\n" +
	"\x15FLOW_DIRECTION_EGRESS\x10\x02\x12 \n" +
	"\x1cFLOW_DIRECTION_BIDIRECTIONAL\x10\x03B5Z3go.pilab.hu/cloud/virtpb/pilab/network/v2;networkv2b\x06proto3"

var (
	file_pilab_network_v2_network_common_proto_rawDescOnce sync.Once
	file_pilab_network_v2_network_common_proto_rawDescData []byte
)

func file_pilab_network_v2_network_common_proto_rawDescGZIP() []byte {
	file_pilab_network_v2_network_common_proto_rawDescOnce.Do(func() {
		file_pilab_network_v2_network_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pilab_network_v2_network_common_proto_rawDesc), len(file_pilab_network_v2_network_common_proto_rawDesc)))
	})
	return file_pilab_network_v2_network_common_proto_rawDescData
}

var file_pilab_network_v2_network_common_proto_enumTypes = make([]protoimpl.EnumInfo, 23)
var file_pilab_network_v2_network_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pilab_network_v2_network_common_proto_goTypes = []any{
	(Protocol)(0),           // 0: pilab.network.v2.Protocol
	(ACNAction)(0),          // 1: pilab.network.v2.ACNAction
	(Direction)(0),          // 2: pilab.network.v2.Direction
	(NetworkType)(0),        // 3: pilab.network.v2.NetworkType
	(NetworkStatus)(0),      // 4: pilab.network.v2.NetworkStatus
	(NetworkRole)(0),        // 5: pilab.network.v2.NetworkRole
	(PortType)(0),           // 6: pilab.network.v2.PortType
	(PortStatus)(0),         // 7: pilab.network.v2.PortStatus
	(VirtualCloudType)(0),   // 8: pilab.network.v2.VirtualCloudType
	(VirtualCloudStatus)(0), // 9: pilab.network.v2.VirtualCloudStatus
	(PriorityClass)(0),      // 10: pilab.network.v2.PriorityClass
	(QoSAlgorithm)(0),       // 11: pilab.network.v2.QoSAlgorithm
	(RateLimitUnit)(0),      // 12: pilab.network.v2.RateLimitUnit
	(ApplyTarget)(0),        // 13: pilab.network.v2.ApplyTarget
	(AllocationMode)(0),     // 14: pilab.network.v2.AllocationMode
	(AllocationType)(0),     // 15: pilab.network.v2.AllocationType
	(PublicIPType)(0),       // 16: pilab.network.v2.PublicIPType
	(PublicIPStatus)(0),     // 17: pilab.network.v2.PublicIPStatus
	(FirewallState)(0),      // 18: pilab.network.v2.FirewallState
	(FirewallDirection)(0),  // 19: pilab.network.v2.FirewallDirection
	(DVSStatus)(0),          // 20: pilab.network.v2.DVSStatus
	(TeamingMode)(0),        // 21: pilab.network.v2.TeamingMode
	(FlowDirection)(0),      // 22: pilab.network.v2.FlowDirection
	(*RateLimit)(nil),       // 23: pilab.network.v2.RateLimit
	(*TeamingPolicy)(nil),   // 24: pilab.network.v2.TeamingPolicy
}
var file_pilab_network_v2_network_common_proto_depIdxs = []int32{
	12, // 0: pilab.network.v2.RateLimit.unit:type_name -> pilab.network.v2.RateLimitUnit
	21, // 1: pilab.network.v2.TeamingPolicy.mode:type_name -> pilab.network.v2.TeamingMode
	2,  // [2:2] is the sub-list for method output_type
	2,  // [2:2] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_pilab_network_v2_network_common_proto_init() }
func file_pilab_network_v2_network_common_proto_init() {
	if File_pilab_network_v2_network_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pilab_network_v2_network_common_proto_rawDesc), len(file_pilab_network_v2_network_common_proto_rawDesc)),
			NumEnums:      23,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pilab_network_v2_network_common_proto_goTypes,
		DependencyIndexes: file_pilab_network_v2_network_common_proto_depIdxs,
		EnumInfos:         file_pilab_network_v2_network_common_proto_enumTypes,
		MessageInfos:      file_pilab_network_v2_network_common_proto_msgTypes,
	}.Build()
	File_pilab_network_v2_network_common_proto = out.File
	file_pilab_network_v2_network_common_proto_goTypes = nil
	file_pilab_network_v2_network_common_proto_depIdxs = nil
}
