// Package network provides virtual networking services including networks,
// ports, VLAN/VXLAN management, IPAM, QoS, security, DVS, and statistics.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pilab/network/v2/qos_security_service.proto

package networkv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// QoSProfile defines quality of service settings for ports and networks.
type QoSProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	PriorityClass PriorityClass          `protobuf:"varint,4,opt,name=priority_class,json=priorityClass,proto3,enum=pilab.network.v2.PriorityClass" json:"priority_class,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	IngressLimit  *RateLimit             `protobuf:"bytes,6,opt,name=ingress_limit,json=ingressLimit,proto3" json:"ingress_limit,omitempty"`
	EgressLimit   *RateLimit             `protobuf:"bytes,7,opt,name=egress_limit,json=egressLimit,proto3" json:"egress_limit,omitempty"`
	Burst         int64                  `protobuf:"varint,8,opt,name=burst,proto3" json:"burst,omitempty"`
	BurstBuffer   int64                  `protobuf:"varint,9,opt,name=burst_buffer,json=burstBuffer,proto3" json:"burst_buffer,omitempty"`
	Enabled       bool                   `protobuf:"varint,10,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Algorithm     QoSAlgorithm           `protobuf:"varint,11,opt,name=algorithm,proto3,enum=pilab.network.v2.QoSAlgorithm" json:"algorithm,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,12,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QoSProfile) Reset() {
	*x = QoSProfile{}
	mi := &file_pilab_network_v2_qos_security_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QoSProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QoSProfile) ProtoMessage() {}

func (x *QoSProfile) ProtoReflect() protoreflect.Message {
	mi := &file_pilab_network_v2_qos_security_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QoSProfile.ProtoReflect.Descriptor instead.
func (*QoSProfile) Descriptor() ([]byte, []int) {
	return file_pilab_network_v2_qos_security_service_proto_rawDescGZIP(), []int{0}
}

func (x *QoSProfile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *QoSProfile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *QoSProfile) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *QoSProfile) GetPriorityClass() PriorityClass {
	if x != nil {
		return x.PriorityClass
	}
	return PriorityClass_PRIORITY_CLASS_UNSPECIFIED
}

func (x *QoSProfile) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *QoSProfile) GetIngressLimit() *RateLimit {
	if x != nil {
		return x.IngressLimit
	}
	return nil
}

func (x *QoSProfile) GetEgressLimit() *RateLimit {
	if x != nil {
		return x.EgressLimit
	}
	return nil
}

func (x *QoSProfile) GetBurst() int64 {
	if x != nil {
		return x.Burst
	}
	return 0
}

func (x *QoSProfile) GetBurstBuffer() int64 {
	if x != nil {
		return x.BurstBuffer
	}
	return 0
}

func (x *QoSProfile) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *QoSProfile) GetAlgorithm() QoSAlgorithm {
	if x != nil {
		return x.Algorithm
	}
	return QoSAlgorithm_QOS_ALGORITHM_UNSPECIFIED
}

func (x *QoSProfile) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *QoSProfile) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *QoSProfile) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// CreateQoSProfileRequest contains parameters for creating a QoS profile.
type CreateQoSProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	PriorityClass PriorityClass          `protobuf:"varint,3,opt,name=priority_class,json=priorityClass,proto3,enum=pilab.network.v2.PriorityClass" json:"priority_class,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	IngressLimit  *RateLimit             `protobuf:"bytes,5,opt,name=ingress_limit,json=ingressLimit,proto3" json:"ingress_limit,omitempty"`
	EgressLimit   *RateLimit             `protobuf:"bytes,6,opt,name=egress_limit,json=egressLimit,proto3" json:"egress_limit,omitempty"`
	Burst         int64                  `protobuf:"varint,7,opt,name=burst,proto3" json:"burst,omitempty"`
	BurstBuffer   int64                  `protobuf:"varint,8,opt,name=burst_buffer,json=burstBuffer,proto3" json:"burst_buffer,omitempty"`
	Algorithm     QoSAlgorithm           `protobuf:"varint,9,opt,name=algorithm,proto3,enum=pilab.network.v2.QoSAlgorithm" json:"algorithm,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,10,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateQoSProfileRequest) Reset() {
	*x = CreateQoSProfileRequest{}
	mi := &file_pilab_network_v2_qos_security_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateQoSProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQoSProfileRequest) ProtoMessage() {}

func (x *CreateQoSProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pilab_network_v2_qos_security_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQoSProfileRequest.ProtoReflect.Descriptor instead.
func (*CreateQoSProfileRequest) Descriptor() ([]byte, []int) {
	return file_pilab_network_v2_qos_security_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateQoSProfileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateQoSProfileRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateQoSProfileRequest) GetPriorityClass() PriorityClass {
	if x != nil {
		return x.PriorityClass
	}
	return PriorityClass_PRIORITY_CLASS_UNSPECIFIED
}

func (x *CreateQoSProfileRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateQoSProfileRequest) GetIngressLimit() *RateLimit {
	if x != nil {
		return x.IngressLimit
	}
	return nil
}

func (x *CreateQoSProfileRequest) GetEgressLimit() *RateLimit {
	if x != nil {
		return x.EgressLimit
	}
	return nil
}

func (x *CreateQoSProfileRequest) GetBurst() int64 {
	if x != nil {
		return x.Burst
	}
	return 0
}

func (x *CreateQoSProfileRequest) GetBurstBuffer() int64 {
	if x != nil {
		return x.BurstBuffer
	}
	return 0
}

func (x *CreateQoSProfileRequest) GetAlgorithm() QoSAlgorithm {
	if x != nil {
		return x.Algorithm
	}
	return QoSAlgorithm_QOS_ALGORITHM_UNSPECIFIED
}

func (x *CreateQoSProfileRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type GetQoSProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QosProfileId  string                 `protobuf:"bytes,1,opt,name=qos_profile_id,json=qosProfileId,proto3" json:"qos_profile_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQoSProfileRequest) Reset() {
	*x = GetQoSProfileRequest{}
	mi := &file_pilab_network_v2_qos_security_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQoSProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQoSProfileRequest) ProtoMessage() {}

func (x *GetQoSProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pilab_network_v2_qos_security_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQoSProfileRequest.ProtoReflect.Descriptor instead.
func (*GetQoSProfileRequest) Descriptor() ([]byte, []int) {
	return file_pilab_network_v2_qos_security_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetQoSProfileRequest) GetQosProfileId() string {
	if x != nil {
		return x.QosProfileId
	}
	return ""
}

type ListQoSProfilesRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	TenantId      string                  `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Cursor        *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit         int32                   `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListQoSProfilesRequest) Reset() {
	*x = ListQoSProfilesRequest{}
	mi := &file_pilab_network_v2_qos_security_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListQoSProfilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQoSProfilesRequest) ProtoMessage() {}

func (x *ListQoSProfilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pilab_network_v2_qos_security_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQoSProfilesRequest.ProtoReflect.Descriptor instead.
func (*ListQoSProfilesRequest) Descriptor() ([]byte, []int) {
	return file_pilab_network_v2_qos_security_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListQoSProfilesRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListQoSProfilesRequest) GetCursor() *wrapperspb.StringValue {
	if x != nil {
		return x.Cursor
	}
	return nil
}

func (x *ListQoSProfilesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListQoSProfilesResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Profiles      []*QoSProfile           `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty"`
	NextCursor    *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	Total         int32                   `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListQoSProfilesResponse) Reset() {
	*x = ListQoSProfilesResponse{}
	mi := &file_pilab_network_v2_qos_security_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListQoSProfilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQoSProfilesResponse) ProtoMessage() {}

func (x *ListQoSProfilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pilab_network_v2_qos_security_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQoSProfilesResponse.ProtoReflect.Descriptor instead.
func (*ListQoSProfilesResponse) Descriptor() ([]byte, []int) {
	return file_pilab_network_v2_qos_security_service_proto_rawDescGZIP(), []int{4}
}

func (x *ListQoSProfilesResponse) GetProfiles() []*QoSProfile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

func (x *ListQoSProfilesResponse) GetNextCursor() *wrapperspb.StringValue {
	if x != nil {
		return x.NextCursor
	}
	return nil
}

func (x *ListQoSProfilesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type UpdateQoSProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QosProfileId  string                 `protobuf:"bytes,1,opt,name=qos_profile_id,json=qosProfileId,proto3" json:"qos_profile_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IngressLimit  *RateLimit             `protobuf:"bytes,3,opt,name=ingress_limit,json=ingressLimit,proto3" json:"ingress_limit,omitempty"`
	EgressLimit   *RateLimit             `protobuf:"bytes,4,opt,name=egress_limit,json=egressLimit,proto3" json:"egress_limit,omitempty"`
	Burst         int64                  `protobuf:"varint,5,opt,name=burst,proto3" json:"burst,omitempty"`
	Enabled       bool                   `protobuf:"varint,6,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateQoSProfileRequest) Reset() {
	*x = UpdateQoSProfileRequest{}
	mi := &file_pilab_network_v2_qos_security_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateQoSProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateQoSProfileRequest) ProtoMessage() {}

func (x *UpdateQoSProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pilab_network_v2_qos_security_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateQoSProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateQoSProfileRequest) Descriptor() ([]byte, []int) {
	return file_pilab_network_v2_qos_security_service_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateQoSProfileRequest) GetQosProfileId() string {
	if x != nil {
		return x.QosProfileId
	}
	return ""
}

func (x *UpdateQoSProfileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateQoSProfileRequest) GetIngressLimit() *RateLimit {
	if x != nil {
		return x.IngressLimit
	}
	return nil
}

func (x *UpdateQoSProfileRequest) GetEgressLimit() *RateLimit {
	if x != nil {
		return x.EgressLimit
	}
	return nil
}

func (x *UpdateQoSProfileRequest) GetBurst() int64 {
	if x != nil {
		return x.Burst
	}
	return 0
}

func (x *UpdateQoSProfileRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *UpdateQoSProfileRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type DeleteQoSProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QosProfileId  string                 `protobuf:"bytes,1,opt,name=qos_profile_id,json=qosProfileId,proto3" json:"qos_profile_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteQoSProfileRequest) Reset() {
	*x = DeleteQoSProfileRequest{}
	mi := &file_pilab_network_v2_qos_security_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteQoSProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteQoSProfileRequest) ProtoMessage() {}

func (x *DeleteQoSProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pilab_network_v2_qos_security_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteQoSProfileRequest.ProtoReflect.Descriptor instead.
func (*DeleteQoSProfileRequest) Descriptor() ([]byte, []int) {
	return file_pilab_network_v2_qos_security_service_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteQoSProfileRequest) GetQosProfileId() string {
	if x != nil {
		return x.QosProfileId
	}
	return ""
}

type ApplyQoSProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QosProfileId  string                 `protobuf:"bytes,1,opt,name=qos_profile_id,json=qosProfileId,proto3" json:"qos_profile_id,omitempty"`
	PortId        string                 `protobuf:"bytes,2,opt,name=port_id,json=portId,proto3" json:"port_id,omitempty"`
	NetworkId     string                 `protobuf:"bytes,3,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	Target        ApplyTarget            `protobuf:"varint,4,opt,name=target,proto3,enum=pilab.network.v2.ApplyTarget" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyQoSProfileRequest) Reset() {
	*x = ApplyQoSProfileRequest{}
	mi := &file_pilab_network_v2_qos_security_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyQoSProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyQoSProfileRequest) ProtoMessage() {}

func (x *ApplyQoSProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pilab_network_v2_qos_security_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyQoSProfileRequest.ProtoReflect.Descriptor instead.
func (*ApplyQoSProfileRequest) Descriptor() ([]byte, []int) {
	return file_pilab_network_v2_qos_security_service_proto_rawDescGZIP(), []int{7}
}

func (x *ApplyQoSProfileRequest) GetQosProfileId() string {
	if x != nil {
		return x.QosProfileId
	}
	return ""
}

func (x *ApplyQoSProfileRequest) GetPortId() string {
	if x != nil {
		return x.PortId
	}
	return ""
}

func (x *ApplyQoSProfileRequest) GetNetworkId() string {
	if x != nil {
		return x.NetworkId
	}
	return ""
}

func (x *ApplyQoSProfileRequest) GetTarget() ApplyTarget {
	if x != nil {
		return x.Target
	}
	return ApplyTarget_APPLY_TARGET_UNSPECIFIED
}

type RemoveQoSProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QosProfileId  string                 `protobuf:"bytes,1,opt,name=qos_profile_id,json=qosProfileId,proto3" json:"qos_profile_id,omitempty"`
	PortId        string                 `protobuf:"bytes,2,opt,name=port_id,json=portId,proto3" json:"port_id,omitempty"`
	NetworkId     string                 `protobuf:"bytes,3,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	Target        ApplyTarget            `protobuf:"varint,4,opt,name=target,proto3,enum=pilab.network.v2.ApplyTarget" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveQoSProfileRequest) Reset() {
	*x = RemoveQoSProfileRequest{}
	mi := &file_pilab_network_v2_qos_security_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveQoSProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveQoSProfileRequest) ProtoMessage() {}

func (x *RemoveQoSProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pilab_network_v2_qos_security_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveQoSProfileRequest.ProtoReflect.Descriptor instead.
func (*RemoveQoSProfileRequest) Descriptor() ([]byte, []int) {
	return file_pilab_network_v2_qos_security_service_proto_rawDescGZIP(), []int{8}
}

func (x *RemoveQoSProfileRequest) GetQosProfileId() string {
	if x != nil {
		return x.QosProfileId
	}
	return ""
}

func (x *RemoveQoSProfileRequest) GetPortId() string {
	if x != nil {
		return x.PortId
	}
	return ""
}

func (x *RemoveQoSProfileRequest) GetNetworkId() string {
	if x != nil {
		return x.NetworkId
	}
	return ""
}

func (x *RemoveQoSProfileRequest) GetTarget() ApplyTarget {
	if x != nil {
		return x.Target
	}
	return ApplyTarget_APPLY_TARGET_UNSPECIFIED
}

// SecurityProfile defines port security and ACL settings.
type SecurityProfile struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	Id                        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                      string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	TenantId                  string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Description               string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	MacSpoofProtectionEnabled bool                   `protobuf:"varint,5,opt,name=mac_spoof_protection_enabled,json=macSpoofProtectionEnabled,proto3" json:"mac_spoof_protection_enabled,omitempty"`
	IpSpoofProtectionEnabled  bool                   `protobuf:"varint,6,opt,name=ip_spoof_protection_enabled,json=ipSpoofProtectionEnabled,proto3" json:"ip_spoof_protection_enabled,omitempty"`
	ArpSpoofProtectionEnabled bool                   `protobuf:"varint,7,opt,name=arp_spoof_protection_enabled,json=arpSpoofProtectionEnabled,proto3" json:"arp_spoof_protection_enabled,omitempty"`
	AllowPromiscuous          bool                   `protobuf:"varint,8,opt,name=allow_promiscuous,json=allowPromiscuous,proto3" json:"allow_promiscuous,omitempty"`
	PortSecurityEnabled       bool                   `protobuf:"varint,9,opt,name=port_security_enabled,json=portSecurityEnabled,proto3" json:"port_security_enabled,omitempty"`
	AllowedMacAddresses       []string               `protobuf:"bytes,10,rep,name=allowed_mac_addresses,json=allowedMacAddresses,proto3" json:"allowed_mac_addresses,omitempty"`
	AllowedIpAddresses        []string               `protobuf:"bytes,11,rep,name=allowed_ip_addresses,json=allowedIpAddresses,proto3" json:"allowed_ip_addresses,omitempty"`
	IngressRules              []*ACLRule             `protobuf:"bytes,12,rep,name=ingress_rules,json=ingressRules,proto3" json:"ingress_rules,omitempty"`
	EgressRules               []*ACLRule             `protobuf:"bytes,13,rep,name=egress_rules,json=egressRules,proto3" json:"egress_rules,omitempty"`
	Metadata                  map[string]string      `protobuf:"bytes,14,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt                 *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt                 *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *SecurityProfile) Reset() {
	*x = SecurityProfile{}
	mi := &file_pilab_network_v2_qos_security_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityProfile) ProtoMessage() {}

func (x *SecurityProfile) ProtoReflect() protoreflect.Message {
	mi := &file_pilab_network_v2_qos_security_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityProfile.ProtoReflect.Descriptor instead.
func (*SecurityProfile) Descriptor() ([]byte, []int) {
	return file_pilab_network_v2_qos_security_service_proto_rawDescGZIP(), []int{9}
}

func (x *SecurityProfile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SecurityProfile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SecurityProfile) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *SecurityProfile) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SecurityProfile) GetMacSpoofProtectionEnabled() bool {
	if x != nil {
		return x.MacSpoofProtectionEnabled
	}
	return false
}

func (x *SecurityProfile) GetIpSpoofProtectionEnabled() bool {
	if x != nil {
		return x.IpSpoofProtectionEnabled
	}
	return false
}

func (x *SecurityProfile) GetArpSpoofProtectionEnabled() bool {
	if x != nil {
		return x.ArpSpoofProtectionEnabled
	}
	return false
}

func (x *SecurityProfile) GetAllowPromiscuous() bool {
	if x != nil {
		return x.AllowPromiscuous
	}
	return false
}

func (x *SecurityProfile) GetPortSecurityEnabled() bool {
	if x != nil {
		return x.PortSecurityEnabled
	}
	return false
}

func (x *SecurityProfile) GetAllowedMacAddresses() []string {
	if x != nil {
		return x.AllowedMacAddresses
	}
	return nil
}

func (x *SecurityProfile) GetAllowedIpAddresses() []string {
	if x != nil {
		return x.AllowedIpAddresses
	}
	return nil
}

func (x *SecurityProfile) GetIngressRules() []*ACLRule {
	if x != nil {
		return x.IngressRules
	}
	return nil
}

func (x *SecurityProfile) GetEgressRules() []*ACLRule {
	if x != nil {
		return x.EgressRules
	}
	return nil
}

func (x *SecurityProfile) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SecurityProfile) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SecurityProfile) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// ACLRule defines an access control list rule.
type ACLRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Priority      int32                  `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	Direction     Direction              `protobuf:"varint,4,opt,name=direction,proto3,enum=pilab.network.v2.Direction" json:"direction,omitempty"`
	Action        ACNAction              `protobuf:"varint,5,opt,name=action,proto3,enum=pilab.network.v2.ACNAction" json:"action,omitempty"`
	Protocol      Protocol               `protobuf:"varint,6,opt,name=protocol,proto3,enum=pilab.network.v2.Protocol" json:"protocol,omitempty"`
	SrcCidr       string                 `protobuf:"bytes,7,opt,name=src_cidr,json=srcCidr,proto3" json:"src_cidr,omitempty"`
	DstCidr       string                 `protobuf:"bytes,8,opt,name=dst_cidr,json=dstCidr,proto3" json:"dst_cidr,omitempty"`
	SrcPortStart  uint32                 `protobuf:"varint,9,opt,name=src_port_start,json=srcPortStart,proto3" json:"src_port_start,omitempty"`
	SrcPortEnd    uint32                 `protobuf:"varint,10,opt,name=src_port_end,json=srcPortEnd,proto3" json:"src_port_end,omitempty"`
	DstPortStart  uint32                 `protobuf:"varint,11,opt,name=dst_port_start,json=dstPortStart,proto3" json:"dst_port_start,omitempty"`
	DstPortEnd    uint32                 `protobuf:"varint,12,opt,name=dst_port_end,json=dstPortEnd,proto3" json:"dst_port_end,omitempty"`
	Description   string                 `protobuf:"bytes,13,opt,name=description,proto3" json:"description,omitempty"`
	LogEnabled    bool                   `protobuf:"varint,14,opt,name=log_enabled,json=logEnabled,proto3" json:"log_enabled,omitempty"`
	Stateful      bool                   `protobuf:"varint,15,opt,name=stateful,proto3" json:"stateful,omitempty"`
	PacketCount   int64                  `protobuf:"varint,16,opt,name=packet_count,json=packetCount,proto3" json:"packet_count,omitempty"`
	ByteCount     int64                  `protobuf:"varint,17,opt,name=byte_count,json=byteCount,proto3" json:"byte_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ACLRule) Reset() {
	*x = ACLRule{}
	mi := &file_pilab_network_v2_qos_security_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ACLRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ACLRule) ProtoMessage() {}

func (x *ACLRule) ProtoReflect() protoreflect.Message {
	mi := &file_pilab_network_v2_qos_security_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ACLRule.ProtoReflect.Descriptor instead.
func (*ACLRule) Descriptor() ([]byte, []int) {
	return file_pilab_network_v2_qos_security_service_proto_rawDescGZIP(), []int{10}
}

func (x *ACLRule) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ACLRule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ACLRule) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *ACLRule) GetDirection() Direction {
	if x != nil {
		return x.Direction
	}
	return Direction_DIRECTION_UNSPECIFIED
}

func (x *ACLRule) GetAction() ACNAction {
	if x != nil {
		return x.Action
	}
	return ACNAction_ACN_ACTION_UNSPECIFIED
}

func (x *ACLRule) GetProtocol() Protocol {
	if x != nil {
		return x.Protocol
	}
	return Protocol_PROTOCOL_UNSPECIFIED
}

func (x *ACLRule) GetSrcCidr() string {
	if x != nil {
		return x.SrcCidr
	}
	return ""
}

func (x *ACLRule) GetDstCidr() string {
	if x != nil {
		return x.DstCidr
	}
	return ""
}

func (x *ACLRule) GetSrcPortStart() uint32 {
	if x != nil {
		return x.SrcPortStart
	}
	return 0
}

func (x *ACLRule) GetSrcPortEnd() uint32 {
	if x != nil {
		return x.SrcPortEnd
	}
	return 0
}

func (x *ACLRule) GetDstPortStart() uint32 {
	if x != nil {
		return x.DstPortStart
	}
	return 0
}

func (x *ACLRule) GetDstPortEnd() uint32 {
	if x != nil {
		return x.DstPortEnd
	}
	return 0
}

func (x *ACLRule) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ACLRule) GetLogEnabled() bool {
	if x != nil {
		return x.LogEnabled
	}
	return false
}

func (x *ACLRule) GetStateful() bool {
	if x != nil {
		return x.Stateful
	}
	return false
}

func (x *ACLRule) GetPacketCount() int64 {
	if x != nil {
		return x.PacketCount
	}
	return 0
}

func (x *ACLRule) GetByteCount() int64 {
	if x != nil {
		return x.ByteCount
	}
	return 0
}

// CreateSecurityProfileRequest contains parameters for creating a security profile.
type CreateSecurityProfileRequest struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	Name                      string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TenantId                  string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Description               string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	MacSpoofProtectionEnabled bool                   `protobuf:"varint,4,opt,name=mac_spoof_protection_enabled,json=macSpoofProtectionEnabled,proto3" json:"mac_spoof_protection_enabled,omitempty"`
	IpSpoofProtectionEnabled  bool                   `protobuf:"varint,5,opt,name=ip_spoof_protection_enabled,json=ipSpoofProtectionEnabled,proto3" json:"ip_spoof_protection_enabled,omitempty"`
	ArpSpoofProtectionEnabled bool                   `protobuf:"varint,6,opt,name=arp_spoof_protection_enabled,json=arpSpoofProtectionEnabled,proto3" json:"arp_spoof_protection_enabled,omitempty"`
	AllowPromiscuous          bool                   `protobuf:"varint,7,opt,name=allow_promiscuous,json=allowPromiscuous,proto3" json:"allow_promiscuous,omitempty"`
	PortSecurityEnabled       bool                   `protobuf:"varint,8,opt,name=port_security_enabled,json=portSecurityEnabled,proto3" json:"port_security_enabled,omitempty"`
	AllowedMacAddresses       []string               `protobuf:"bytes,9,rep,name=allowed_mac_addresses,json=allowedMacAddresses,proto3" json:"allowed_mac_addresses,omitempty"`
	AllowedIpAddresses        []string               `protobuf:"bytes,10,rep,name=allowed_ip_addresses,json=allowedIpAddresses,proto3" json:"allowed_ip_addresses,omitempty"`
	IngressRules              []*ACLRule             `protobuf:"bytes,11,rep,name=ingress_rules,json=ingressRules,proto3" json:"ingress_rules,omitempty"`
	EgressRules               []*ACLRule             `protobuf:"bytes,12,rep,name=egress_rules,json=egressRules,proto3" json:"egress_rules,omitempty"`
	Metadata                  map[string]string      `protobuf:"bytes,13,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *CreateSecurityProfileRequest) Reset() {
	*x = CreateSecurityProfileRequest{}
	mi := &file_pilab_network_v2_qos_security_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSecurityProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSecurityProfileRequest) ProtoMessage() {}

func (x *CreateSecurityProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pilab_network_v2_qos_security_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSecurityProfileRequest.ProtoReflect.Descriptor instead.
func (*CreateSecurityProfileRequest) Descriptor() ([]byte, []int) {
	return file_pilab_network_v2_qos_security_service_proto_rawDescGZIP(), []int{11}
}

func (x *CreateSecurityProfileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSecurityProfileRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateSecurityProfileRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateSecurityProfileRequest) GetMacSpoofProtectionEnabled() bool {
	if x != nil {
		return x.MacSpoofProtectionEnabled
	}
	return false
}

func (x *CreateSecurityProfileRequest) GetIpSpoofProtectionEnabled() bool {
	if x != nil {
		return x.IpSpoofProtectionEnabled
	}
	return false
}

func (x *CreateSecurityProfileRequest) GetArpSpoofProtectionEnabled() bool {
	if x != nil {
		return x.ArpSpoofProtectionEnabled
	}
	return false
}

func (x *CreateSecurityProfileRequest) GetAllowPromiscuous() bool {
	if x != nil {
		return x.AllowPromiscuous
	}
	return false
}

func (x *CreateSecurityProfileRequest) GetPortSecurityEnabled() bool {
	if x != nil {
		return x.PortSecurityEnabled
	}
	return false
}

func (x *CreateSecurityProfileRequest) GetAllowedMacAddresses() []string {
	if x != nil {
		return x.AllowedMacAddresses
	}
	return nil
}

func (x *CreateSecurityProfileRequest) GetAllowedIpAddresses() []string {
	if x != nil {
		return x.AllowedIpAddresses
	}
	return nil
}

func (x *CreateSecurityProfileRequest) GetIngressRules() []*ACLRule {
	if x != nil {
		return x.IngressRules
	}
	return nil
}

func (x *CreateSecurityProfileRequest) GetEgressRules() []*ACLRule {
	if x != nil {
		return x.EgressRules
	}
	return nil
}

func (x *CreateSecurityProfileRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type GetSecurityProfileRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SecurityProfileId string                 `protobuf:"bytes,1,opt,name=security_profile_id,json=securityProfileId,proto3" json:"security_profile_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetSecurityProfileRequest) Reset() {
	*x = GetSecurityProfileRequest{}
	mi := &file_pilab_network_v2_qos_security_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecurityProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecurityProfileRequest) ProtoMessage() {}

func (x *GetSecurityProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pilab_network_v2_qos_security_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecurityProfileRequest.ProtoReflect.Descriptor instead.
func (*GetSecurityProfileRequest) Descriptor() ([]byte, []int) {
	return file_pilab_network_v2_qos_security_service_proto_rawDescGZIP(), []int{12}
}

func (x *GetSecurityProfileRequest) GetSecurityProfileId() string {
	if x != nil {
		return x.SecurityProfileId
	}
	return ""
}

type ListSecurityProfilesRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	TenantId      string                  `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Cursor        *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit         int32                   `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSecurityProfilesRequest) Reset() {
	*x = ListSecurityProfilesRequest{}
	mi := &file_pilab_network_v2_qos_security_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecurityProfilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecurityProfilesRequest) ProtoMessage() {}

func (x *ListSecurityProfilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pilab_network_v2_qos_security_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecurityProfilesRequest.ProtoReflect.Descriptor instead.
func (*ListSecurityProfilesRequest) Descriptor() ([]byte, []int) {
	return file_pilab_network_v2_qos_security_service_proto_rawDescGZIP(), []int{13}
}

func (x *ListSecurityProfilesRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListSecurityProfilesRequest) GetCursor() *wrapperspb.StringValue {
	if x != nil {
		return x.Cursor
	}
	return nil
}

func (x *ListSecurityProfilesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListSecurityProfilesResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Profiles      []*SecurityProfile      `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty"`
	NextCursor    *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	Total         int32                   `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSecurityProfilesResponse) Reset() {
	*x = ListSecurityProfilesResponse{}
	mi := &file_pilab_network_v2_qos_security_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecurityProfilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecurityProfilesResponse) ProtoMessage() {}

func (x *ListSecurityProfilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pilab_network_v2_qos_security_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecurityProfilesResponse.ProtoReflect.Descriptor instead.
func (*ListSecurityProfilesResponse) Descriptor() ([]byte, []int) {
	return file_pilab_network_v2_qos_security_service_proto_rawDescGZIP(), []int{14}
}

func (x *ListSecurityProfilesResponse) GetProfiles() []*SecurityProfile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

func (x *ListSecurityProfilesResponse) GetNextCursor() *wrapperspb.StringValue {
	if x != nil {
		return x.NextCursor
	}
	return nil
}

func (x *ListSecurityProfilesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type UpdateSecurityProfileRequest struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	SecurityProfileId         string                 `protobuf:"bytes,1,opt,name=security_profile_id,json=securityProfileId,proto3" json:"security_profile_id,omitempty"`
	Name                      string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	MacSpoofProtectionEnabled bool                   `protobuf:"varint,3,opt,name=mac_spoof_protection_enabled,json=macSpoofProtectionEnabled,proto3" json:"mac_spoof_protection_enabled,omitempty"`
	IpSpoofProtectionEnabled  bool                   `protobuf:"varint,4,opt,name=ip_spoof_protection_enabled,json=ipSpoofProtectionEnabled,proto3" json:"ip_spoof_protection_enabled,omitempty"`
	ArpSpoofProtectionEnabled bool                   `protobuf:"varint,5,opt,name=arp_spoof_protection_enabled,json=arpSpoofProtectionEnabled,proto3" json:"arp_spoof_protection_enabled,omitempty"`
	AllowedMacAddresses       []string               `protobuf:"bytes,6,rep,name=allowed_mac_addresses,json=allowedMacAddresses,proto3" json:"allowed_mac_addresses,omitempty"`
	AllowedIpAddresses        []string               `protobuf:"bytes,7,rep,name=allowed_ip_addresses,json=allowedIpAddresses,proto3" json:"allowed_ip_addresses,omitempty"`
	Metadata                  map[string]string      `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *UpdateSecurityProfileRequest) Reset() {
	*x = UpdateSecurityProfileRequest{}
	mi := &file_pilab_network_v2_qos_security_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSecurityProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSecurityProfileRequest) ProtoMessage() {}

func (x *UpdateSecurityProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pilab_network_v2_qos_security_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSecurityProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateSecurityProfileRequest) Descriptor() ([]byte, []int) {
	return file_pilab_network_v2_qos_security_service_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateSecurityProfileRequest) GetSecurityProfileId() string {
	if x != nil {
		return x.SecurityProfileId
	}
	return ""
}

func (x *UpdateSecurityProfileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateSecurityProfileRequest) GetMacSpoofProtectionEnabled() bool {
	if x != nil {
		return x.MacSpoofProtectionEnabled
	}
	return false
}

func (x *UpdateSecurityProfileRequest) GetIpSpoofProtectionEnabled() bool {
	if x != nil {
		return x.IpSpoofProtectionEnabled
	}
	return false
}

func (x *UpdateSecurityProfileRequest) GetArpSpoofProtectionEnabled() bool {
	if x != nil {
		return x.ArpSpoofProtectionEnabled
	}
	return false
}

func (x *UpdateSecurityProfileRequest) GetAllowedMacAddresses() []string {
	if x != nil {
		return x.AllowedMacAddresses
	}
	return nil
}

func (x *UpdateSecurityProfileRequest) GetAllowedIpAddresses() []string {
	if x != nil {
		return x.AllowedIpAddresses
	}
	return nil
}

func (x *UpdateSecurityProfileRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type DeleteSecurityProfileRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SecurityProfileId string                 `protobuf:"bytes,1,opt,name=security_profile_id,json=securityProfileId,proto3" json:"security_profile_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DeleteSecurityProfileRequest) Reset() {
	*x = DeleteSecurityProfileRequest{}
	mi := &file_pilab_network_v2_qos_security_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSecurityProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSecurityProfileRequest) ProtoMessage() {}

func (x *DeleteSecurityProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pilab_network_v2_qos_security_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSecurityProfileRequest.ProtoReflect.Descriptor instead.
func (*DeleteSecurityProfileRequest) Descriptor() ([]byte, []int) {
	return file_pilab_network_v2_qos_security_service_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteSecurityProfileRequest) GetSecurityProfileId() string {
	if x != nil {
		return x.SecurityProfileId
	}
	return ""
}

type ApplySecurityProfileRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SecurityProfileId string                 `protobuf:"bytes,1,opt,name=security_profile_id,json=securityProfileId,proto3" json:"security_profile_id,omitempty"`
	PortId            string                 `protobuf:"bytes,2,opt,name=port_id,json=portId,proto3" json:"port_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ApplySecurityProfileRequest) Reset() {
	*x = ApplySecurityProfileRequest{}
	mi := &file_pilab_network_v2_qos_security_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplySecurityProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplySecurityProfileRequest) ProtoMessage() {}

func (x *ApplySecurityProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pilab_network_v2_qos_security_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplySecurityProfileRequest.ProtoReflect.Descriptor instead.
func (*ApplySecurityProfileRequest) Descriptor() ([]byte, []int) {
	return file_pilab_network_v2_qos_security_service_proto_rawDescGZIP(), []int{17}
}

func (x *ApplySecurityProfileRequest) GetSecurityProfileId() string {
	if x != nil {
		return x.SecurityProfileId
	}
	return ""
}

func (x *ApplySecurityProfileRequest) GetPortId() string {
	if x != nil {
		return x.PortId
	}
	return ""
}

type RemoveSecurityProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PortId        string                 `protobuf:"bytes,1,opt,name=port_id,json=portId,proto3" json:"port_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveSecurityProfileRequest) Reset() {
	*x = RemoveSecurityProfileRequest{}
	mi := &file_pilab_network_v2_qos_security_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveSecurityProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSecurityProfileRequest) ProtoMessage() {}

func (x *RemoveSecurityProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pilab_network_v2_qos_security_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSecurityProfileRequest.ProtoReflect.Descriptor instead.
func (*RemoveSecurityProfileRequest) Descriptor() ([]byte, []int) {
	return file_pilab_network_v2_qos_security_service_proto_rawDescGZIP(), []int{18}
}

func (x *RemoveSecurityProfileRequest) GetPortId() string {
	if x != nil {
		return x.PortId
	}
	return ""
}

type AddACLRuleRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SecurityProfileId string                 `protobuf:"bytes,1,opt,name=security_profile_id,json=securityProfileId,proto3" json:"security_profile_id,omitempty"`
	Rule              *ACLRule               `protobuf:"bytes,2,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AddACLRuleRequest) Reset() {
	*x = AddACLRuleRequest{}
	mi := &file_pilab_network_v2_qos_security_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddACLRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddACLRuleRequest) ProtoMessage() {}

func (x *AddACLRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pilab_network_v2_qos_security_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddACLRuleRequest.ProtoReflect.Descriptor instead.
func (*AddACLRuleRequest) Descriptor() ([]byte, []int) {
	return file_pilab_network_v2_qos_security_service_proto_rawDescGZIP(), []int{19}
}

func (x *AddACLRuleRequest) GetSecurityProfileId() string {
	if x != nil {
		return x.SecurityProfileId
	}
	return ""
}

func (x *AddACLRuleRequest) GetRule() *ACLRule {
	if x != nil {
		return x.Rule
	}
	return nil
}

type UpdateACLRuleRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SecurityProfileId string                 `protobuf:"bytes,1,opt,name=security_profile_id,json=securityProfileId,proto3" json:"security_profile_id,omitempty"`
	Rule              *ACLRule               `protobuf:"bytes,2,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateACLRuleRequest) Reset() {
	*x = UpdateACLRuleRequest{}
	mi := &file_pilab_network_v2_qos_security_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateACLRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateACLRuleRequest) ProtoMessage() {}

func (x *UpdateACLRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pilab_network_v2_qos_security_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateACLRuleRequest.ProtoReflect.Descriptor instead.
func (*UpdateACLRuleRequest) Descriptor() ([]byte, []int) {
	return file_pilab_network_v2_qos_security_service_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateACLRuleRequest) GetSecurityProfileId() string {
	if x != nil {
		return x.SecurityProfileId
	}
	return ""
}

func (x *UpdateACLRuleRequest) GetRule() *ACLRule {
	if x != nil {
		return x.Rule
	}
	return nil
}

type RemoveACLRuleRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SecurityProfileId string                 `protobuf:"bytes,1,opt,name=security_profile_id,json=securityProfileId,proto3" json:"security_profile_id,omitempty"`
	RuleId            string                 `protobuf:"bytes,2,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RemoveACLRuleRequest) Reset() {
	*x = RemoveACLRuleRequest{}
	mi := &file_pilab_network_v2_qos_security_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveACLRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveACLRuleRequest) ProtoMessage() {}

func (x *RemoveACLRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pilab_network_v2_qos_security_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveACLRuleRequest.ProtoReflect.Descriptor instead.
func (*RemoveACLRuleRequest) Descriptor() ([]byte, []int) {
	return file_pilab_network_v2_qos_security_service_proto_rawDescGZIP(), []int{21}
}

func (x *RemoveACLRuleRequest) GetSecurityProfileId() string {
	if x != nil {
		return x.SecurityProfileId
	}
	return ""
}

func (x *RemoveACLRuleRequest) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

type ReorderACLRulesRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SecurityProfileId string                 `protobuf:"bytes,1,opt,name=security_profile_id,json=securityProfileId,proto3" json:"security_profile_id,omitempty"`
	Rules             []*ACLRule             `protobuf:"bytes,2,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ReorderACLRulesRequest) Reset() {
	*x = ReorderACLRulesRequest{}
	mi := &file_pilab_network_v2_qos_security_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReorderACLRulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReorderACLRulesRequest) ProtoMessage() {}

func (x *ReorderACLRulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pilab_network_v2_qos_security_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReorderACLRulesRequest.ProtoReflect.Descriptor instead.
func (*ReorderACLRulesRequest) Descriptor() ([]byte, []int) {
	return file_pilab_network_v2_qos_security_service_proto_rawDescGZIP(), []int{22}
}

func (x *ReorderACLRulesRequest) GetSecurityProfileId() string {
	if x != nil {
		return x.SecurityProfileId
	}
	return ""
}

func (x *ReorderACLRulesRequest) GetRules() []*ACLRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

var File_pilab_network_v2_qos_security_service_proto protoreflect.FileDescriptor

const file_pilab_network_v2_qos_security_service_proto_rawDesc = "" +
	"\n" +
	"+pilab/network/v2/qos_security_service.proto\x12\x10pilab.network.v2\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a%pilab/network/v2/network_common.proto\"\xc5\x05\n" +
	"\n" +
	"QoSProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12F\n" +
	"\x0epriority_class\x18\x04 \x01(\x0e2\x1f.pilab.network.v2.PriorityClassR\rpriorityClass\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12@\n" +
	"\ringress_limit\x18\x06 \x01(\v2\x1b.pilab.network.v2.RateLimitR\fingressLimit\x12>\n" +
	"\fegress_limit\x18\a \x01(\v2\x1b.pilab.network.v2.RateLimitR\vegressLimit\x12\x14\n" +
	"\x05burst\x18\b \x01(\x03R\x05burst\x12!\n" +
	"\fburst_buffer\x18\t \x01(\x03R\vburstBuffer\x12\x18\n" +
	"\aenabled\x18\n" +
	" \x01(\bR\aenabled\x12<\n" +
	"\talgorithm\x18\v \x01(\x0e2\x1e.pilab.network.v2.QoSAlgorithmR\talgorithm\x12F\n" +
	"\bmetadata\x18\f \x03(\v2*.pilab.network.v2.QoSProfile.MetadataEntryR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbf\x04\n" +
	"\x17CreateQoSProfileRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12F\n" +
	"\x0epriority_class\x18\x03 \x01(\x0e2\x1f.pilab.network.v2.PriorityClassR\rpriorityClass\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12@\n" +
	"\ringress_limit\x18\x05 \x01(\v2\x1b.pilab.network.v2.RateLimitR\fingressLimit\x12>\n" +
	"\fegress_limit\x18\x06 \x01(\v2\x1b.pilab.network.v2.RateLimitR\vegressLimit\x12\x14\n" +
	"\x05burst\x18\a \x01(\x03R\x05burst\x12!\n" +
	"\fburst_buffer\x18\b \x01(\x03R\vburstBuffer\x12<\n" +
	"\talgorithm\x18\t \x01(\x0e2\x1e.pilab.network.v2.QoSAlgorithmR\talgorithm\x12S\n" +
	"\bmetadata\x18\n" +
	" \x03(\v27.pilab.network.v2.CreateQoSProfileRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"<\n" +
	"\x14GetQoSProfileRequest\x12$\n" +
	"\x0eqos_profile_id\x18\x01 \x01(\tR\fqosProfileId\"\x81\x01\n" +
	"\x16ListQoSProfilesRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x124\n" +
	"\x06cursor\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\x06cursor\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\xa8\x01\n" +
	"\x17ListQoSProfilesResponse\x128\n" +
	"\bprofiles\x18\x01 \x03(\v2\x1c.pilab.network.v2.QoSProfileR\bprofiles\x12=\n" +
	"\vnext_cursor\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\n" +
	"nextCursor\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total\"\x97\x03\n" +
	"\x17UpdateQoSProfileRequest\x12$\n" +
	"\x0eqos_profile_id\x18\x01 \x01(\tR\fqosProfileId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12@\n" +
	"\ringress_limit\x18\x03 \x01(\v2\x1b.pilab.network.v2.RateLimitR\fingressLimit\x12>\n" +
	"\fegress_limit\x18\x04 \x01(\v2\x1b.pilab.network.v2.RateLimitR\vegressLimit\x12\x14\n" +
	"\x05burst\x18\x05 \x01(\x03R\x05burst\x12\x18\n" +
	"\aenabled\x18\x06 \x01(\bR\aenabled\x12S\n" +
	"\bmetadata\x18\a \x03(\v27.pilab.network.v2.UpdateQoSProfileRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"?\n" +
	"\x17DeleteQoSProfileRequest\x12$\n" +
	"\x0eqos_profile_id\x18\x01 \x01(\tR\fqosProfileId\"\xad\x01\n" +
	"\x16ApplyQoSProfileRequest\x12$\n" +
	"\x0eqos_profile_id\x18\x01 \x01(\tR\fqosProfileId\x12\x17\n" +
	"\aport_id\x18\x02 \x01(\tR\x06portId\x12\x1d\n" +
	"\n" +
	"network_id\x18\x03 \x01(\tR\tnetworkId\x125\n" +
	"\x06target\x18\x04 \x01(\x0e2\x1d.pilab.network.v2.ApplyTargetR\x06target\"\xae\x01\n" +
	"\x17RemoveQoSProfileRequest\x12$\n" +
	"\x0eqos_profile_id\x18\x01 \x01(\tR\fqosProfileId\x12\x17\n" +
	"\aport_id\x18\x02 \x01(\tR\x06portId\x12\x1d\n" +
	"\n" +
	"network_id\x18\x03 \x01(\tR\tnetworkId\x125\n" +
	"\x06target\x18\x04 \x01(\x0e2\x1d.pilab.network.v2.ApplyTargetR\x06target\"\xfa\x06\n" +
	"\x0fSecurityProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12?\n" +
	"\x1cmac_spoof_protection_enabled\x18\x05 \x01(\bR\x19macSpoofProtectionEnabled\x12=\n" +
	"\x1bip_spoof_protection_enabled\x18\x06 \x01(\bR\x18ipSpoofProtectionEnabled\x12?\n" +
	"\x1carp_spoof_protection_enabled\x18\a \x01(\bR\x19arpSpoofProtectionEnabled\x12+\n" +
	"\x11allow_promiscuous\x18\b \x01(\bR\x10allowPromiscuous\x122\n" +
	"\x15port_security_enabled\x18\t \x01(\bR\x13portSecurityEnabled\x122\n" +
	"\x15allowed_mac_addresses\x18\n" +
	" \x03(\tR\x13allowedMacAddresses\x120\n" +
	"\x14allowed_ip_addresses\x18\v \x03(\tR\x12allowedIpAddresses\x12>\n" +
	"\ringress_rules\x18\f \x03(\v2\x19.pilab.network.v2.ACLRuleR\fingressRules\x12<\n" +
	"\fegress_rules\x18\r \x03(\v2\x19.pilab.network.v2.ACLRuleR\vegressRules\x12K\n" +
	"\bmetadata\x18\x0e \x03(\v2/.pilab.network.v2.SecurityProfile.MetadataEntryR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd8\x04\n" +
	"\aACLRule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x05R\bpriority\x129\n" +
	"\tdirection\x18\x04 \x01(\x0e2\x1b.pilab.network.v2.DirectionR\tdirection\x123\n" +
	"\x06action\x18\x05 \x01(\x0e2\x1b.pilab.network.v2.ACNActionR\x06action\x126\n" +
	"\bprotocol\x18\x06 \x01(\x0e2\x1a.pilab.network.v2.ProtocolR\bprotocol\x12\x19\n" +
	"\bsrc_cidr\x18\a \x01(\tR\asrcCidr\x12\x19\n" +
	"\bdst_cidr\x18\b \x01(\tR\adstCidr\x12$\n" +
	"\x0esrc_port_start\x18\t \x01(\rR\fsrcPortStart\x12 \n" +
	"\fsrc_port_end\x18\n" +
	" \x01(\rR\n" +
	"srcPortEnd\x12$\n" +
	"\x0edst_port_start\x18\v \x01(\rR\fdstPortStart\x12 \n" +
	"\fdst_port_end\x18\f \x01(\rR\n" +
	"dstPortEnd\x12 \n" +
	"\vdescription\x18\r \x01(\tR\vdescription\x12\x1f\n" +
	"\vlog_enabled\x18\x0e \x01(\bR\n" +
	"logEnabled\x12\x1a\n" +
	"\bstateful\x18\x0f \x01(\bR\bstateful\x12!\n" +
	"\fpacket_count\x18\x10 \x01(\x03R\vpacketCount\x12\x1d\n" +
	"\n" +
	"byte_count\x18\x11 \x01(\x03R\tbyteCount\"\x8e\x06\n" +
	"\x1cCreateSecurityProfileRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12?\n" +
	"\x1cmac_spoof_protection_enabled\x18\x04 \x01(\bR\x19macSpoofProtectionEnabled\x12=\n" +
	"\x1bip_spoof_protection_enabled\x18\x05 \x01(\bR\x18ipSpoofProtectionEnabled\x12?\n" +
	"\x1carp_spoof_protection_enabled\x18\x06 \x01(\bR\x19arpSpoofProtectionEnabled\x12+\n" +
	"\x11allow_promiscuous\x18\a \x01(\bR\x10allowPromiscuous\x122\n" +
	"\x15port_security_enabled\x18\b \x01(\bR\x13portSecurityEnabled\x122\n" +
	"\x15allowed_mac_addresses\x18\t \x03(\tR\x13allowedMacAddresses\x120\n" +
	"\x14allowed_ip_addresses\x18\n" +
	" \x03(\tR\x12allowedIpAddresses\x12>\n" +
	"\ringress_rules\x18\v \x03(\v2\x19.pilab.network.v2.ACLRuleR\fingressRules\x12<\n" +
	"\fegress_rules\x18\f \x03(\v2\x19.pilab.network.v2.ACLRuleR\vegressRules\x12X\n" +
	"\bmetadata\x18\r \x03(\v2<.pilab.network.v2.CreateSecurityProfileRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"K\n" +
	"\x19GetSecurityProfileRequest\x12.\n" +
	"\x13security_profile_id\x18\x01 \x01(\tR\x11securityProfileId\"\x86\x01\n" +
	"\x1bListSecurityProfilesRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x124\n" +
	"\x06cursor\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\x06cursor\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\xb2\x01\n" +
	"\x1cListSecurityProfilesResponse\x12=\n" +
	"\bprofiles\x18\x01 \x03(\v2!.pilab.network.v2.SecurityProfileR\bprofiles\x12=\n" +
	"\vnext_cursor\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\n" +
	"nextCursor\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total\"\xa0\x04\n" +
	"\x1cUpdateSecurityProfileRequest\x12.\n" +
	"\x13security_profile_id\x18\x01 \x01(\tR\x11securityProfileId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12?\n" +
	"\x1cmac_spoof_protection_enabled\x18\x03 \x01(\bR\x19macSpoofProtectionEnabled\x12=\n" +
	"\x1bip_spoof_protection_enabled\x18\x04 \x01(\bR\x18ipSpoofProtectionEnabled\x12?\n" +
	"\x1carp_spoof_protection_enabled\x18\x05 \x01(\bR\x19arpSpoofProtectionEnabled\x122\n" +
	"\x15allowed_mac_addresses\x18\x06 \x03(\tR\x13allowedMacAddresses\x120\n" +
	"\x14allowed_ip_addresses\x18\a \x03(\tR\x12allowedIpAddresses\x12X\n" +
	"\bmetadata\x18\b \x03(\v2<.pilab.network.v2.UpdateSecurityProfileRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"N\n" +
	"\x1cDeleteSecurityProfileRequest\x12.\n" +
	"\x13security_profile_id\x18\x01 \x01(\tR\x11securityProfileId\"f\n" +
	"\x1bApplySecurityProfileRequest\x12.\n" +
	"\x13security_profile_id\x18\x01 \x01(\tR\x11securityProfileId\x12\x17\n" +
	"\aport_id\x18\x02 \x01(\tR\x06portId\"7\n" +
	"\x1cRemoveSecurityProfileRequest\x12\x17\n" +
	"\aport_id\x18\x01 \x01(\tR\x06portId\"r\n" +
	"\x11AddACLRuleRequest\x12.\n" +
	"\x13security_profile_id\x18\x01 \x01(\tR\x11securityProfileId\x12-\n" +
	"\x04rule\x18\x02 \x01(\v2\x19.pilab.network.v2.ACLRuleR\x04rule\"u\n" +
	"\x14UpdateACLRuleRequest\x12.\n" +
	"\x13security_profile_id\x18\x01 \x01(\tR\x11securityProfileId\x12-\n" +
	"\x04rule\x18\x02 \x01(\v2\x19.pilab.network.v2.ACLRuleR\x04rule\"_\n" +
	"\x14RemoveACLRuleRequest\x12.\n" +
	"\x13security_profile_id\x18\x01 \x01(\tR\x11securityProfileId\x12\x17\n" +
	"\arule_id\x18\x02 \x01(\tR\x06ruleId\"y\n" +
	"\x16ReorderACLRulesRequest\x12.\n" +
	"\x13security_profile_id\x18\x01 \x01(\tR\x11securityProfileId\x12/\n" +
	"\x05rules\x18\x02 \x03(\v2\x19.pilab.network.v2.ACLRuleR\x05rules2\xae\r\n" +
	"\x12QoSSecurityService\x12[\n" +
	"\x10CreateQoSProfile\x12).pilab.network.v2.CreateQoSProfileRequest\x1a\x1c.pilab.network.v2.QoSProfile\x12U\n" +
	"\rGetQoSProfile\x12&.pilab.network.v2.GetQoSProfileRequest\x1a\x1c.pilab.network.v2.QoSProfile\x12f\n" +
	"\x0fListQoSProfiles\x12(.pilab.network.v2.ListQoSProfilesRequest\x1a).pilab.network.v2.ListQoSProfilesResponse\x12[\n" +
	"\x10UpdateQoSProfile\x12).pilab.network.v2.UpdateQoSProfileRequest\x1a\x1c.pilab.network.v2.QoSProfile\x12U\n" +
	"\x10DeleteQoSProfile\x12).pilab.network.v2.DeleteQoSProfileRequest\x1a\x16.google.protobuf.Empty\x12S\n" +
	"\x0fApplyQoSProfile\x12(.pilab.network.v2.ApplyQoSProfileRequest\x1a\x16.google.protobuf.Empty\x12U\n" +
	"\x10RemoveQoSProfile\x12).pilab.network.v2.RemoveQoSProfileRequest\x1a\x16.google.protobuf.Empty\x12j\n" +
	"\x15CreateSecurityProfile\x12..pilab.network.v2.CreateSecurityProfileRequest\x1a!.pilab.network.v2.SecurityProfile\x12d\n" +
	"\x12GetSecurityProfile\x12+.pilab.network.v2.GetSecurityProfileRequest\x1a!.pilab.network.v2.SecurityProfile\x12u\n" +
	"\x14ListSecurityProfiles\x12-.pilab.network.v2.ListSecurityProfilesRequest\x1a..pilab.network.v2.ListSecurityProfilesResponse\x12j\n" +
	"\x15UpdateSecurityProfile\x12..pilab.network.v2.UpdateSecurityProfileRequest\x1a!.pilab.network.v2.SecurityProfile\x12_\n" +
	"\x15DeleteSecurityProfile\x12..pilab.network.v2.DeleteSecurityProfileRequest\x1a\x16.google.protobuf.Empty\x12]\n" +
	"\x14ApplySecurityProfile\x12-.pilab.network.v2.ApplySecurityProfileRequest\x1a\x16.google.protobuf.Empty\x12_\n" +
	"\x15RemoveSecurityProfile\x12..pilab.network.v2.RemoveSecurityProfileRequest\x1a\x16.google.protobuf.Empty\x12L\n" +
	"\n" +
	"AddACLRule\x12#.pilab.network.v2.AddACLRuleRequest\x1a\x19.pilab.network.v2.ACLRule\x12R\n" +
	"\rUpdateACLRule\x12&.pilab.network.v2.UpdateACLRuleRequest\x1a\x19.pilab.network.v2.ACLRule\x12O\n" +
	"\rRemoveACLRule\x12&.pilab.network.v2.RemoveACLRuleRequest\x1a\x16.google.protobuf.Empty\x12S\n" +
	"\x0fReorderACLRules\x12(.pilab.network.v2.ReorderACLRulesRequest\x1a\x16.google.protobuf.EmptyB5Z3go.pilab.hu/cloud/virtpb/pilab/network/v2;networkv2b\x06proto3"

var (
	file_pilab_network_v2_qos_security_service_proto_rawDescOnce sync.Once
	file_pilab_network_v2_qos_security_service_proto_rawDescData []byte
)

func file_pilab_network_v2_qos_security_service_proto_rawDescGZIP() []byte {
	file_pilab_network_v2_qos_security_service_proto_rawDescOnce.Do(func() {
		file_pilab_network_v2_qos_security_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pilab_network_v2_qos_security_service_proto_rawDesc), len(file_pilab_network_v2_qos_security_service_proto_rawDesc)))
	})
	return file_pilab_network_v2_qos_security_service_proto_rawDescData
}

var file_pilab_network_v2_qos_security_service_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_pilab_network_v2_qos_security_service_proto_goTypes = []any{
	(*QoSProfile)(nil),                   // 0: pilab.network.v2.QoSProfile
	(*CreateQoSProfileRequest)(nil),      // 1: pilab.network.v2.CreateQoSProfileRequest
	(*GetQoSProfileRequest)(nil),         // 2: pilab.network.v2.GetQoSProfileRequest
	(*ListQoSProfilesRequest)(nil),       // 3: pilab.network.v2.ListQoSProfilesRequest
	(*ListQoSProfilesResponse)(nil),      // 4: pilab.network.v2.ListQoSProfilesResponse
	(*UpdateQoSProfileRequest)(nil),      // 5: pilab.network.v2.UpdateQoSProfileRequest
	(*DeleteQoSProfileRequest)(nil),      // 6: pilab.network.v2.DeleteQoSProfileRequest
	(*ApplyQoSProfileRequest)(nil),       // 7: pilab.network.v2.ApplyQoSProfileRequest
	(*RemoveQoSProfileRequest)(nil),      // 8: pilab.network.v2.RemoveQoSProfileRequest
	(*SecurityProfile)(nil),              // 9: pilab.network.v2.SecurityProfile
	(*ACLRule)(nil),                      // 10: pilab.network.v2.ACLRule
	(*CreateSecurityProfileRequest)(nil), // 11: pilab.network.v2.CreateSecurityProfileRequest
	(*GetSecurityProfileRequest)(nil),    // 12: pilab.network.v2.GetSecurityProfileRequest
	(*ListSecurityProfilesRequest)(nil),  // 13: pilab.network.v2.ListSecurityProfilesRequest
	(*ListSecurityProfilesResponse)(nil), // 14: pilab.network.v2.ListSecurityProfilesResponse
	(*UpdateSecurityProfileRequest)(nil), // 15: pilab.network.v2.UpdateSecurityProfileRequest
	(*DeleteSecurityProfileRequest)(nil), // 16: pilab.network.v2.DeleteSecurityProfileRequest
	(*ApplySecurityProfileRequest)(nil),  // 17: pilab.network.v2.ApplySecurityProfileRequest
	(*RemoveSecurityProfileRequest)(nil), // 18: pilab.network.v2.RemoveSecurityProfileRequest
	(*AddACLRuleRequest)(nil),            // 19: pilab.network.v2.AddACLRuleRequest
	(*UpdateACLRuleRequest)(nil),         // 20: pilab.network.v2.UpdateACLRuleRequest
	(*RemoveACLRuleRequest)(nil),         // 21: pilab.network.v2.RemoveACLRuleRequest
	(*ReorderACLRulesRequest)(nil),       // 22: pilab.network.v2.ReorderACLRulesRequest
	nil,                                  // 23: pilab.network.v2.QoSProfile.MetadataEntry
	nil,                                  // 24: pilab.network.v2.CreateQoSProfileRequest.MetadataEntry
	nil,                                  // 25: pilab.network.v2.UpdateQoSProfileRequest.MetadataEntry
	nil,                                  // 26: pilab.network.v2.SecurityProfile.MetadataEntry
	nil,                                  // 27: pilab.network.v2.CreateSecurityProfileRequest.MetadataEntry
	nil,                                  // 28: pilab.network.v2.UpdateSecurityProfileRequest.MetadataEntry
	(PriorityClass)(0),                   // 29: pilab.network.v2.PriorityClass
	(*RateLimit)(nil),                    // 30: pilab.network.v2.RateLimit
	(QoSAlgorithm)(0),                    // 31: pilab.network.v2.QoSAlgorithm
	(*timestamppb.Timestamp)(nil),        // 32: google.protobuf.Timestamp
	(*wrapperspb.StringValue)(nil),       // 33: google.protobuf.StringValue
	(ApplyTarget)(0),                     // 34: pilab.network.v2.ApplyTarget
	(Direction)(0),                       // 35: pilab.network.v2.Direction
	(ACNAction)(0),                       // 36: pilab.network.v2.ACNAction
	(Protocol)(0),                        // 37: pilab.network.v2.Protocol
	(*emptypb.Empty)(nil),                // 38: google.protobuf.Empty
}
var file_pilab_network_v2_qos_security_service_proto_depIdxs = []int32{
	29, // 0: pilab.network.v2.QoSProfile.priority_class:type_name -> pilab.network.v2.PriorityClass
	30, // 1: pilab.network.v2.QoSProfile.ingress_limit:type_name -> pilab.network.v2.RateLimit
	30, // 2: pilab.network.v2.QoSProfile.egress_limit:type_name -> pilab.network.v2.RateLimit
	31, // 3: pilab.network.v2.QoSProfile.algorithm:type_name -> pilab.network.v2.QoSAlgorithm
	23, // 4: pilab.network.v2.QoSProfile.metadata:type_name -> pilab.network.v2.QoSProfile.MetadataEntry
	32, // 5: pilab.network.v2.QoSProfile.created_at:type_name -> google.protobuf.Timestamp
	32, // 6: pilab.network.v2.QoSProfile.updated_at:type_name -> google.protobuf.Timestamp
	29, // 7: pilab.network.v2.CreateQoSProfileRequest.priority_class:type_name -> pilab.network.v2.PriorityClass
	30, // 8: pilab.network.v2.CreateQoSProfileRequest.ingress_limit:type_name -> pilab.network.v2.RateLimit
	30, // 9: pilab.network.v2.CreateQoSProfileRequest.egress_limit:type_name -> pilab.network.v2.RateLimit
	31, // 10: pilab.network.v2.CreateQoSProfileRequest.algorithm:type_name -> pilab.network.v2.QoSAlgorithm
	24, // 11: pilab.network.v2.CreateQoSProfileRequest.metadata:type_name -> pilab.network.v2.CreateQoSProfileRequest.MetadataEntry
	33, // 12: pilab.network.v2.ListQoSProfilesRequest.cursor:type_name -> google.protobuf.StringValue
	0,  // 13: pilab.network.v2.ListQoSProfilesResponse.profiles:type_name -> pilab.network.v2.QoSProfile
	33, // 14: pilab.network.v2.ListQoSProfilesResponse.next_cursor:type_name -> google.protobuf.StringValue
	30, // 15: pilab.network.v2.UpdateQoSProfileRequest.ingress_limit:type_name -> pilab.network.v2.RateLimit
	30, // 16: pilab.network.v2.UpdateQoSProfileRequest.egress_limit:type_name -> pilab.network.v2.RateLimit
	25, // 17: pilab.network.v2.UpdateQoSProfileRequest.metadata:type_name -> pilab.network.v2.UpdateQoSProfileRequest.MetadataEntry
	34, // 18: pilab.network.v2.ApplyQoSProfileRequest.target:type_name -> pilab.network.v2.ApplyTarget
	34, // 19: pilab.network.v2.RemoveQoSProfileRequest.target:type_name -> pilab.network.v2.ApplyTarget
	10, // 20: pilab.network.v2.SecurityProfile.ingress_rules:type_name -> pilab.network.v2.ACLRule
	10, // 21: pilab.network.v2.SecurityProfile.egress_rules:type_name -> pilab.network.v2.ACLRule
	26, // 22: pilab.network.v2.SecurityProfile.metadata:type_name -> pilab.network.v2.SecurityProfile.MetadataEntry
	32, // 23: pilab.network.v2.SecurityProfile.created_at:type_name -> google.protobuf.Timestamp
	32, // 24: pilab.network.v2.SecurityProfile.updated_at:type_name -> google.protobuf.Timestamp
	35, // 25: pilab.network.v2.ACLRule.direction:type_name -> pilab.network.v2.Direction
	36, // 26: pilab.network.v2.ACLRule.action:type_name -> pilab.network.v2.ACNAction
	37, // 27: pilab.network.v2.ACLRule.protocol:type_name -> pilab.network.v2.Protocol
	10, // 28: pilab.network.v2.CreateSecurityProfileRequest.ingress_rules:type_name -> pilab.network.v2.ACLRule
	10, // 29: pilab.network.v2.CreateSecurityProfileRequest.egress_rules:type_name -> pilab.network.v2.ACLRule
	27, // 30: pilab.network.v2.CreateSecurityProfileRequest.metadata:type_name -> pilab.network.v2.CreateSecurityProfileRequest.MetadataEntry
	33, // 31: pilab.network.v2.ListSecurityProfilesRequest.cursor:type_name -> google.protobuf.StringValue
	9,  // 32: pilab.network.v2.ListSecurityProfilesResponse.profiles:type_name -> pilab.network.v2.SecurityProfile
	33, // 33: pilab.network.v2.ListSecurityProfilesResponse.next_cursor:type_name -> google.protobuf.StringValue
	28, // 34: pilab.network.v2.UpdateSecurityProfileRequest.metadata:type_name -> pilab.network.v2.UpdateSecurityProfileRequest.MetadataEntry
	10, // 35: pilab.network.v2.AddACLRuleRequest.rule:type_name -> pilab.network.v2.ACLRule
	10, // 36: pilab.network.v2.UpdateACLRuleRequest.rule:type_name -> pilab.network.v2.ACLRule
	10, // 37: pilab.network.v2.ReorderACLRulesRequest.rules:type_name -> pilab.network.v2.ACLRule
	1,  // 38: pilab.network.v2.QoSSecurityService.CreateQoSProfile:input_type -> pilab.network.v2.CreateQoSProfileRequest
	2,  // 39: pilab.network.v2.QoSSecurityService.GetQoSProfile:input_type -> pilab.network.v2.GetQoSProfileRequest
	3,  // 40: pilab.network.v2.QoSSecurityService.ListQoSProfiles:input_type -> pilab.network.v2.ListQoSProfilesRequest
	5,  // 41: pilab.network.v2.QoSSecurityService.UpdateQoSProfile:input_type -> pilab.network.v2.UpdateQoSProfileRequest
	6,  // 42: pilab.network.v2.QoSSecurityService.DeleteQoSProfile:input_type -> pilab.network.v2.DeleteQoSProfileRequest
	7,  // 43: pilab.network.v2.QoSSecurityService.ApplyQoSProfile:input_type -> pilab.network.v2.ApplyQoSProfileRequest
	8,  // 44: pilab.network.v2.QoSSecurityService.RemoveQoSProfile:input_type -> pilab.network.v2.RemoveQoSProfileRequest
	11, // 45: pilab.network.v2.QoSSecurityService.CreateSecurityProfile:input_type -> pilab.network.v2.CreateSecurityProfileRequest
	12, // 46: pilab.network.v2.QoSSecurityService.GetSecurityProfile:input_type -> pilab.network.v2.GetSecurityProfileRequest
	13, // 47: pilab.network.v2.QoSSecurityService.ListSecurityProfiles:input_type -> pilab.network.v2.ListSecurityProfilesRequest
	15, // 48: pilab.network.v2.QoSSecurityService.UpdateSecurityProfile:input_type -> pilab.network.v2.UpdateSecurityProfileRequest
	16, // 49: pilab.network.v2.QoSSecurityService.DeleteSecurityProfile:input_type -> pilab.network.v2.DeleteSecurityProfileRequest
	17, // 50: pilab.network.v2.QoSSecurityService.ApplySecurityProfile:input_type -> pilab.network.v2.ApplySecurityProfileRequest
	18, // 51: pilab.network.v2.QoSSecurityService.RemoveSecurityProfile:input_type -> pilab.network.v2.RemoveSecurityProfileRequest
	19, // 52: pilab.network.v2.QoSSecurityService.AddACLRule:input_type -> pilab.network.v2.AddACLRuleRequest
	20, // 53: pilab.network.v2.QoSSecurityService.UpdateACLRule:input_type -> pilab.network.v2.UpdateACLRuleRequest
	21, // 54: pilab.network.v2.QoSSecurityService.RemoveACLRule:input_type -> pilab.network.v2.RemoveACLRuleRequest
	22, // 55: pilab.network.v2.QoSSecurityService.ReorderACLRules:input_type -> pilab.network.v2.ReorderACLRulesRequest
	0,  // 56: pilab.network.v2.QoSSecurityService.CreateQoSProfile:output_type -> pilab.network.v2.QoSProfile
	0,  // 57: pilab.network.v2.QoSSecurityService.GetQoSProfile:output_type -> pilab.network.v2.QoSProfile
	4,  // 58: pilab.network.v2.QoSSecurityService.ListQoSProfiles:output_type -> pilab.network.v2.ListQoSProfilesResponse
	0,  // 59: pilab.network.v2.QoSSecurityService.UpdateQoSProfile:output_type -> pilab.network.v2.QoSProfile
	38, // 60: pilab.network.v2.QoSSecurityService.DeleteQoSProfile:output_type -> google.protobuf.Empty
	38, // 61: pilab.network.v2.QoSSecurityService.ApplyQoSProfile:output_type -> google.protobuf.Empty
	38, // 62: pilab.network.v2.QoSSecurityService.RemoveQoSProfile:output_type -> google.protobuf.Empty
	9,  // 63: pilab.network.v2.QoSSecurityService.CreateSecurityProfile:output_type -> pilab.network.v2.SecurityProfile
	9,  // 64: pilab.network.v2.QoSSecurityService.GetSecurityProfile:output_type -> pilab.network.v2.SecurityProfile
	14, // 65: pilab.network.v2.QoSSecurityService.ListSecurityProfiles:output_type -> pilab.network.v2.ListSecurityProfilesResponse
	9,  // 66: pilab.network.v2.QoSSecurityService.UpdateSecurityProfile:output_type -> pilab.network.v2.SecurityProfile
	38, // 67: pilab.network.v2.QoSSecurityService.DeleteSecurityProfile:output_type -> google.protobuf.Empty
	38, // 68: pilab.network.v2.QoSSecurityService.ApplySecurityProfile:output_type -> google.protobuf.Empty
	38, // 69: pilab.network.v2.QoSSecurityService.RemoveSecurityProfile:output_type -> google.protobuf.Empty
	10, // 70: pilab.network.v2.QoSSecurityService.AddACLRule:output_type -> pilab.network.v2.ACLRule
	10, // 71: pilab.network.v2.QoSSecurityService.UpdateACLRule:output_type -> pilab.network.v2.ACLRule
	38, // 72: pilab.network.v2.QoSSecurityService.RemoveACLRule:output_type -> google.protobuf.Empty
	38, // 73: pilab.network.v2.QoSSecurityService.ReorderACLRules:output_type -> google.protobuf.Empty
	56, // [56:74] is the sub-list for method output_type
	38, // [38:56] is the sub-list for method input_type
	38, // [38:38] is the sub-list for extension type_name
	38, // [38:38] is the sub-list for extension extendee
	0,  // [0:38] is the sub-list for field type_name
}

func init() { file_pilab_network_v2_qos_security_service_proto_init() }
func file_pilab_network_v2_qos_security_service_proto_init() {
	if File_pilab_network_v2_qos_security_service_proto != nil {
		return
	}
	file_pilab_network_v2_network_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pilab_network_v2_qos_security_service_proto_rawDesc), len(file_pilab_network_v2_qos_security_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pilab_network_v2_qos_security_service_proto_goTypes,
		DependencyIndexes: file_pilab_network_v2_qos_security_service_proto_depIdxs,
		MessageInfos:      file_pilab_network_v2_qos_security_service_proto_msgTypes,
	}.Build()
	File_pilab_network_v2_qos_security_service_proto = out.File
	file_pilab_network_v2_qos_security_service_proto_goTypes = nil
	file_pilab_network_v2_qos_security_service_proto_depIdxs = nil
}
